/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version "17".0 		*/
/*  Created On : "06"-mrt-2025 "15":00:06 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Aanvraagdata" CASCADE
;

DROP TABLE IF EXISTS "Aanvraagofmelding" CASCADE
;

DROP TABLE IF EXISTS "Afspraakstatus" CASCADE
;

DROP TABLE IF EXISTS "Artikel" CASCADE
;

DROP TABLE IF EXISTS "Balieafspraak" CASCADE
;

DROP TABLE IF EXISTS "Externebron" CASCADE
;

DROP TABLE IF EXISTS "Formuliersoort" CASCADE
;

DROP TABLE IF EXISTS "Formuliersoortveld" CASCADE
;

DROP TABLE IF EXISTS "Klantbeoordeling" CASCADE
;

DROP TABLE IF EXISTS "Klantbeoordelingreden" CASCADE
;

DROP TABLE IF EXISTS "Kp_aanvraagofmelding_onderwerp" CASCADE
;

DROP TABLE IF EXISTS "Kp_balieafspraak_productofdien" CASCADE
;

DROP TABLE IF EXISTS "Kp_formuliersoort_zaaktype" CASCADE
;

DROP TABLE IF EXISTS "Kp_klantcontact_productofdiens" CASCADE
;

DROP TABLE IF EXISTS "Kp_organisatorischeeenheid_kla" CASCADE
;

DROP TABLE IF EXISTS "Kp_productofdienst_klantbeoord" CASCADE
;

DROP TABLE IF EXISTS "Mor_aanvraagofmelding" CASCADE
;

DROP TABLE IF EXISTS "Onderwerp" CASCADE
;

DROP TABLE IF EXISTS "Productofdienst" CASCADE
;

DROP TABLE IF EXISTS "Telefoononderwerp" CASCADE
;

DROP TABLE IF EXISTS "Telefoonstatus" CASCADE
;

DROP TABLE IF EXISTS "Telefoontje" CASCADE
;

/* Create Tables */

CREATE TABLE "Aanvraagdata"
(
	"Data" text NULL,
	"Veld" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AanvraagdataID" integer NOT NULL,
	"FormuliersoortveldID" integer NULL,
	"AanvraagofmeldingID" integer NULL
)
;

CREATE TABLE "Aanvraagofmelding"
(
	"Afgehandeld" boolean NULL,
	"Categorie" varchar(200) NULL,
	"Categoriecode" varchar(80) NULL,
	"Datumaanmaak" date NULL,
	"Datumafhandeling" date NULL,
	"Datumbeginstatus" date NULL,
	"Datumeindestatus" date NULL,
	"Hoofdcategorie" varchar(80) NULL,
	"Hoofdcategoriecode" varchar(80) NULL,
	"Identificatie" varchar(40) NULL,
	"Kanaal" varchar(80) NULL,
	"Onderwerp" varchar(200) NULL,
	"Onderwerpcode" varchar(80) NULL,
	"Soort" varchar(80) NULL,	-- Sluit aan op soorten uit Suite4Omgevingsdiensten: aanvraag, melding.... 
	"Status" varchar(80) NULL,
	"Statuscode" varchar(80) NULL,
	"Statusvolgorde" varchar(80) NULL,
	"Subcategorie" varchar(200) NULL,
	"Subcategoriecode" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AanvraagofmeldingID" integer NOT NULL,
	"FormuliersoortID" integer NULL,
	"IndienerID" integer NULL,
	"KlantcontactID" integer NULL,
	"RechtspersoonID" integer NULL
)
;

CREATE TABLE "Afspraakstatus"
(
	"Status" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AfspraakstatusID" integer NOT NULL
)
;

CREATE TABLE "Artikel"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ArtikelID" integer NOT NULL
)
;

CREATE TABLE "Balieafspraak"
(
	"Eindtijdgepland" timestamp without time zone NULL,
	"Notitie" text NULL,
	"Starttijdgepland" timestamp without time zone NULL,
	"Tijdaangemaakt" timestamp without time zone NULL,
	"Tijdsduurgepland" integer NULL,	-- Werkelijke tijdsduur in minuten
	"Toelichting" text NULL,
	"Wachttijdnastartafspraak" integer NULL,	-- Tijdsduur die iemand moet wachten na de starttijd van de afspraak
	"Wachttijdtotaal" integer NULL,	-- Wachttijd inclusief de tijd dat iemand te vroeg voor de afspraak verschijnt en de tijd dat iemand moet wachten na de geplande starttijd van de afspraak
	"Wachttijdvoorstartafspraak" integer NULL,	-- Tijdsduur dat iemand te vroeg is voor de afspraak
	"Werkelijketijdsduur" integer NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"BalieafspraakID" integer NOT NULL,
	"AfspraakstatusID" integer NULL,
	"MedewerkerID" integer NULL,
	"VestigingvanzaakbehandelendeID" integer NULL,
	"ZaakID" integer NULL
)
;

CREATE TABLE "Externebron"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ExternebronID" integer NOT NULL
)
;

CREATE TABLE "Formuliersoort"
(
	"Ingebruik" boolean NULL,
	"Naam" varchar(80) NULL,
	"Onderwerp" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"FormuliersoortID" integer NOT NULL
)
;

CREATE TABLE "Formuliersoortveld"
(
	"Helptekst" text NULL,
	"Isverplicht" boolean NULL,
	"Label" varchar(80) NULL,
	"Maxlengte" integer NULL,
	"Veldnaam" varchar(40) NULL,
	"Veldtype" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"FormuliersoortveldID" integer NOT NULL,
	"FormuliersoortID" integer NULL
)
;

CREATE TABLE "Klantbeoordeling"
(
	"Beoordeling" varchar(10) NULL,	-- cijfer voor de beoordeling (getal tussen 0 en "10")
	"Categorie" varchar(50) NULL,
	"Contactopnemen" boolean NULL,	-- of de klant het al dan niet goed vind dat naar aanleiding van zijn/haar beoordeling contact wordt opgenomen
	"Ddbeoordeling" date NULL,	-- datum en tijdstip van de klantbeoordeling
	"Kanaal" varchar(100) NULL,	-- waar de beoordeling is uitgevoerd, te weten op de website, naar aanleiding van een webformulier of na schriftelijke uitvraag vanuit onze organisatie
	"Onderwerp" varchar(50) NULL,
	"Subcategorie" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KlantbeoordelingID" integer NOT NULL,
	"BetrokkeneID" integer NULL,
	"ZaakID" integer NULL
)
;

CREATE TABLE "Klantbeoordelingreden"
(
	"Reden" varchar(100) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KlantbeoordelingredenID" integer NOT NULL,
	"KlantbeoordelingID" integer NULL
)
;

CREATE TABLE "Kp_aanvraagofmelding_onderwerp"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OnderwerpID" integer NULL,
	"AanvraagofmeldingID" integer NULL
)
;

CREATE TABLE "Kp_balieafspraak_productofdien"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ProductofdienstID" integer NULL,
	"BalieafspraakID" integer NULL
)
;

CREATE TABLE "Kp_formuliersoort_zaaktype"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"FormuliersoortID" integer NULL,
	"ZaaktypeID" integer NULL
)
;

CREATE TABLE "Kp_klantcontact_productofdiens"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ProductofdienstID" integer NULL,
	"KlantcontactID" integer NULL
)
;

CREATE TABLE "Kp_organisatorischeeenheid_kla"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KlantbeoordelingID" integer NULL,
	"OrganisatorischeeenheidID" integer NULL
)
;

CREATE TABLE "Kp_productofdienst_klantbeoord"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KlantbeoordelingID" integer NULL,
	"ProductofdienstID" integer NULL
)
;

CREATE TABLE "Mor_aanvraagofmelding"
(
	"Locatie_lat" double precision,
	"Locatie_long" double precision,
	"Locatie_rdx" double precision,
	"Locatie_rdy" double precision,
	"Locatieomschrijving" varchar(300) NULL,
	"Meldingomschrijving" varchar(40) NULL,
	"Meldingtekst" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Mor-aanvraagofmeldingID" integer NOT NULL,
	"Mor_aanvraagofmeldingID" integer NULL
)
;

CREATE TABLE "Onderwerp"
(
	"Isactief" boolean NULL,
	"Naam" varchar(80) NULL,
	"Toelichting" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OnderwerpID" integer NOT NULL
)
;

CREATE TABLE "Productofdienst"
(
	"Afhandeltijd" integer NULL,	-- Standaard afhandeltijd in minuten
	"Ingebruik" boolean NULL,
	"Naam" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ProductofdienstID" integer NOT NULL
)
;

CREATE TABLE "Telefoononderwerp"
(
	"Onderwerp" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"TelefoononderwerpID" integer NOT NULL
)
;

CREATE TABLE "Telefoonstatus"
(
	"Contactconnectionstate" varchar(20) NULL,
	"Status" varchar(20) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"TelefoonstatusID" integer NOT NULL
)
;

CREATE TABLE "Telefoontje"
(
	"Afhandeltijdnagesprek" integer NULL,	-- De tijd die de medewerker nodig heeft om het telefoontje af te handelen totdat hij/zij klaar is voor een volgend telefoontje
	"Deltaisdnconnectie" integer NULL,	-- De totale tijd dat er een teelfoonverbinding was minus totale wachttijd, spreektijd en on hold-tijd.
	"Eindtijd" timestamp without time zone NULL,	-- Het moment dat de telefooncentrale het telefoontjes beeindigd
	"Starttijd" timestamp without time zone NULL,	-- Het moment dat de telefooncentrale een telefoontje in behandeling neemt. Dit ligt voor de starttijd van het klantcontact
	"Totaleonholdtijd" integer NULL,	-- De totale tijd dat een beller tussen klantcontacten "on hold" wordt gezet.
	"Totalespreektijd" integer NULL,	-- De totale tijd dat met een (of meer) medewerkers van de gemeente wordt gebeld.
	"Totaletijdsduur" integer NULL,	-- Tijd tussen start- en eindtijd van telefoontje
	"Totalewachttijd" integer NULL,	-- De tijd tussen de starttijd van het telefoontje en het moment dat het telefoontje voor het eerst wordt opgenomen, of het telefoontje wordt afgesloten 
	"Trackid" varchar(20) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"TelefoontjeID" integer NOT NULL,
	"TelefoononderwerpID" integer NULL,
	"TelefoonstatusID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Aanvraagdata" ADD CONSTRAINT "PK_Aanvraagdata"
	PRIMARY KEY ("AanvraagdataID")
;

ALTER TABLE "Aanvraagofmelding" ADD CONSTRAINT "PK_Aanvraagofmelding"
	PRIMARY KEY ("AanvraagofmeldingID")
;

ALTER TABLE "Afspraakstatus" ADD CONSTRAINT "PK_Afspraakstatus"
	PRIMARY KEY ("AfspraakstatusID")
;

ALTER TABLE "Artikel" ADD CONSTRAINT "PK_Artikel"
	PRIMARY KEY ("ArtikelID")
;

ALTER TABLE "Balieafspraak" ADD CONSTRAINT "PK_Balieafspraak"
	PRIMARY KEY ("BalieafspraakID")
;

ALTER TABLE "Externebron" ADD CONSTRAINT "PK_Externebron"
	PRIMARY KEY ("ExternebronID")
;

ALTER TABLE "Formuliersoort" ADD CONSTRAINT "PK_Formuliersoort"
	PRIMARY KEY ("FormuliersoortID")
;

ALTER TABLE "Formuliersoortveld" ADD CONSTRAINT "PK_Formuliersoortveld"
	PRIMARY KEY ("FormuliersoortveldID")
;

ALTER TABLE "Klantbeoordeling" ADD CONSTRAINT "PK_Klantbeoordeling"
	PRIMARY KEY ("KlantbeoordelingID")
;

ALTER TABLE "Klantbeoordelingreden" ADD CONSTRAINT "PK_Klantbeoordelingreden"
	PRIMARY KEY ("KlantbeoordelingredenID")
;

ALTER TABLE "Mor_aanvraagofmelding" ADD CONSTRAINT "PK_Mor_aanvraagofmelding"
	PRIMARY KEY ("Mor-aanvraagofmeldingID")
;

ALTER TABLE "Onderwerp" ADD CONSTRAINT "PK_Onderwerp"
	PRIMARY KEY ("OnderwerpID")
;

ALTER TABLE "Productofdienst" ADD CONSTRAINT "PK_Productofdienst"
	PRIMARY KEY ("ProductofdienstID")
;

ALTER TABLE "Telefoononderwerp" ADD CONSTRAINT "PK_Telefoononderwerp"
	PRIMARY KEY ("TelefoononderwerpID")
;

ALTER TABLE "Telefoonstatus" ADD CONSTRAINT "PK_Telefoonstatus"
	PRIMARY KEY ("TelefoonstatusID")
;

ALTER TABLE "Telefoontje" ADD CONSTRAINT "PK_Telefoontje"
	PRIMARY KEY ("TelefoontjeID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Aanvraagdata" ADD CONSTRAINT "FK_Aanvraagdata_Formuliersoortveld"
	FOREIGN KEY ("FormuliersoortveldID") REFERENCES "Formuliersoortveld" ("FormuliersoortveldID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Aanvraagdata" ADD CONSTRAINT "fk_heeftData_aanvraagofmelding"
	FOREIGN KEY ("AanvraagofmeldingID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Aanvraagofmelding" ADD CONSTRAINT "FK_Aanvraagofmelding_Formuliersoort"
	FOREIGN KEY ("FormuliersoortID") REFERENCES "Formuliersoort" ("FormuliersoortID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Aanvraagofmelding" ADD CONSTRAINT "FK_Aanvraagofmelding_Indiener"
	FOREIGN KEY ("IndienerID") REFERENCES "Indiener" ("IndienerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Aanvraagofmelding" ADD CONSTRAINT "fk_kanLeidenTot_klantcontact"
	FOREIGN KEY ("KlantcontactID") REFERENCES "Klantcontact" ("KlantcontactID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Aanvraagofmelding" ADD CONSTRAINT "FK_Aanvraagofmelding_Rechtspersoon"
	FOREIGN KEY ("RechtspersoonID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Balieafspraak" ADD CONSTRAINT "FK_Balieafspraak_Afspraakstatus"
	FOREIGN KEY ("AfspraakstatusID") REFERENCES "Afspraakstatus" ("AfspraakstatusID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Balieafspraak" ADD CONSTRAINT "FK_Balieafspraak_Medewerker"
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Balieafspraak" ADD CONSTRAINT "FK_Balieafspraak_Vestigingvanzaakbehandelendeor"
	FOREIGN KEY ("VestigingvanzaakbehandelendeID") REFERENCES "Vestigingvanzaakbehandelendeor" ("VestigingvanzaakbehandelendeorganisatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Balieafspraak" ADD CONSTRAINT "FK_Balieafspraak_Zaak"
	FOREIGN KEY ("ZaakID") REFERENCES "Zaak" ("ZaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Formuliersoortveld" ADD CONSTRAINT "fk_heeftVelden_formuliersoort"
	FOREIGN KEY ("FormuliersoortID") REFERENCES "Formuliersoort" ("FormuliersoortID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Klantbeoordeling" ADD CONSTRAINT fk_doet_betrokkene
	FOREIGN KEY ("BetrokkeneID") REFERENCES "Betrokkene" ("BetrokkeneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Klantbeoordeling" ADD CONSTRAINT fk_heeft_zaak
	FOREIGN KEY ("ZaakID") REFERENCES "Zaak" ("ZaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Klantbeoordelingreden" ADD CONSTRAINT fk_heeft_klantbeoordeling
	FOREIGN KEY ("KlantbeoordelingID") REFERENCES "Klantbeoordeling" ("KlantbeoordelingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_aanvraagofmelding_onderwerp" ADD CONSTRAINT "Fk_kp_aanvraagofmelding_onderwerp_onderwerp"
	FOREIGN KEY ("OnderwerpID") REFERENCES "Onderwerp" ("OnderwerpID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_aanvraagofmelding_onderwerp" ADD CONSTRAINT "Fk_kp_aanvraagofmelding_onderwerp_aanvraagofmelding"
	FOREIGN KEY ("AanvraagofmeldingID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_balieafspraak_productofdien" ADD CONSTRAINT "Fk_kp_balieafspraak_productofdien_productofdienst"
	FOREIGN KEY ("ProductofdienstID") REFERENCES "Productofdienst" ("ProductofdienstID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_balieafspraak_productofdien" ADD CONSTRAINT "Fk_kp_balieafspraak_productofdien_balieafspraak"
	FOREIGN KEY ("BalieafspraakID") REFERENCES "Balieafspraak" ("BalieafspraakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_formuliersoort_zaaktype" ADD CONSTRAINT "Fk_kp_formuliersoort_zaaktype_formuliersoort"
	FOREIGN KEY ("FormuliersoortID") REFERENCES "Formuliersoort" ("FormuliersoortID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_formuliersoort_zaaktype" ADD CONSTRAINT "Fk_kp_formuliersoort_zaaktype_zaaktype"
	FOREIGN KEY ("ZaaktypeID") REFERENCES "Zaaktype" ("ZaaktypeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_klantcontact_productofdiens" ADD CONSTRAINT "Fk_kp_klantcontact_productofdiens_productofdienst"
	FOREIGN KEY ("ProductofdienstID") REFERENCES "Productofdienst" ("ProductofdienstID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_klantcontact_productofdiens" ADD CONSTRAINT "Fk_kp_klantcontact_productofdiens_klantcontact"
	FOREIGN KEY ("KlantcontactID") REFERENCES "Klantcontact" ("KlantcontactID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_organisatorischeeenheid_kla" ADD CONSTRAINT "Fk_kp_organisatorischeeenheid_kla_klantbeoordeling"
	FOREIGN KEY ("KlantbeoordelingID") REFERENCES "Klantbeoordeling" ("KlantbeoordelingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_organisatorischeeenheid_kla" ADD CONSTRAINT "Fk_kp_organisatorischeeenheid_kla_organisatorischeeenheid"
	FOREIGN KEY ("OrganisatorischeeenheidID") REFERENCES "Organisatorischeeenheid" ("OrganisatorischeeenheidID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_productofdienst_klantbeoord" ADD CONSTRAINT "Fk_kp_productofdienst_klantbeoord_klantbeoordeling"
	FOREIGN KEY ("KlantbeoordelingID") REFERENCES "Klantbeoordeling" ("KlantbeoordelingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_productofdienst_klantbeoord" ADD CONSTRAINT "Fk_kp_productofdienst_klantbeoord_productofdienst"
	FOREIGN KEY ("ProductofdienstID") REFERENCES "Productofdienst" ("ProductofdienstID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Mor_aanvraagofmelding" ADD CONSTRAINT "Fk_mor_aanvraagofmelding_aanvraagofmelding"
	FOREIGN KEY ("Mor_aanvraagofmeldingID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Onderwerp" ADD CONSTRAINT "FK_Onderwerp_Onderwerp"
	FOREIGN KEY ("OnderwerpID") REFERENCES "Onderwerp" ("OnderwerpID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Telefoontje" ADD CONSTRAINT fk_heeft_telefoononderwerp
	FOREIGN KEY ("TelefoononderwerpID") REFERENCES "Telefoononderwerp" ("TelefoononderwerpID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Telefoontje" ADD CONSTRAINT "FK_Telefoontje_Telefoonstatus"
	FOREIGN KEY ("TelefoonstatusID") REFERENCES "Telefoonstatus" ("TelefoonstatusID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Aanvraagdata"
	IS 'Bron: GEN_REQ_DATA
ID: REQ_DATA icm VELD_NAAM Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Aanvraagdata"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Aanvraagdata"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Aanvraagdata"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Aanvraagdata"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Aanvraagdata"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Aanvraagdata"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Aanvraagdata"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Aanvraagdata"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Aanvraagofmelding"
	IS 'Komt overeen met een VJV

Bron: GEM_VJV (Distinct op REQ_ID)
ID: REQ_ID Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Aanvraagofmelding"."Soort"
	IS 'Sluit aan op soorten uit Suite4Omgevingsdiensten: aanvraag, melding.... '
;

COMMENT ON COLUMN "Aanvraagofmelding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Aanvraagofmelding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Aanvraagofmelding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Aanvraagofmelding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Aanvraagofmelding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Aanvraagofmelding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Aanvraagofmelding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Aanvraagofmelding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Afspraakstatus"
	IS 'de toestand van de afspraak Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Afspraakstatus"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Afspraakstatus"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Afspraakstatus"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Afspraakstatus"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Afspraakstatus"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Afspraakstatus"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Afspraakstatus"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Afspraakstatus"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Artikel"
	IS 'Tekst die is gemaakt om gepubliceerd te worden als een onafhankelijk deel van een tijdschrift, krant, encyclopedie of ander werk Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Artikel"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Artikel"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Artikel"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Artikel"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Artikel"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Artikel"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Artikel"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Artikel"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Balieafspraak"
	IS 'Balieafspraken zijn afspraken voor een klantcontact. Dit ongeacht of deze werkelijk heeft plaatsgevonden of gaat plaatsvinden, soms liggen deze in de toekomst of is iemand niet op komen dagen, of iets anders waardoor het klantcontact nog niet heeft plaatsgevonden. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Balieafspraak"."Tijdsduurgepland"
	IS 'Werkelijke tijdsduur in minuten'
;

COMMENT ON COLUMN "Balieafspraak"."Wachttijdnastartafspraak"
	IS 'Tijdsduur die iemand moet wachten na de starttijd van de afspraak'
;

COMMENT ON COLUMN "Balieafspraak"."Wachttijdtotaal"
	IS 'Wachttijd inclusief de tijd dat iemand te vroeg voor de afspraak verschijnt en de tijd dat iemand moet wachten na de geplande starttijd van de afspraak'
;

COMMENT ON COLUMN "Balieafspraak"."Wachttijdvoorstartafspraak"
	IS 'Tijdsduur dat iemand te vroeg is voor de afspraak'
;

COMMENT ON COLUMN "Balieafspraak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Balieafspraak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Balieafspraak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Balieafspraak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Balieafspraak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Balieafspraak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Balieafspraak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Balieafspraak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Externebron"
	IS 'Bron buiten de eigen organisatie Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Externebron"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Externebron"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Externebron"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Externebron"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Externebron"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Externebron"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Externebron"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Externebron"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Formuliersoort"
	IS 'Bron: GEM_FORM
ID: FORM_ID Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Formuliersoort"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Formuliersoort"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Formuliersoort"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Formuliersoort"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Formuliersoort"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Formuliersoort"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Formuliersoort"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Formuliersoort"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Formuliersoortveld"
	IS 'Bron: GEM_VELD
ID: FORM_ID en VELD_NAAM Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Formuliersoortveld"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Formuliersoortveld"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Formuliersoortveld"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Formuliersoortveld"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Formuliersoortveld"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Formuliersoortveld"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Formuliersoortveld"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Formuliersoortveld"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Klantbeoordeling"
	IS 'goed- of afkeurende uitspraak; = mening, opvatting Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Klantbeoordeling"."Beoordeling"
	IS 'cijfer voor de beoordeling (getal tussen 0 en "10")'
;

COMMENT ON COLUMN "Klantbeoordeling"."Contactopnemen"
	IS 'of de klant het al dan niet goed vind dat naar aanleiding van zijn/haar beoordeling contact wordt opgenomen'
;

COMMENT ON COLUMN "Klantbeoordeling"."Ddbeoordeling"
	IS 'datum en tijdstip van de klantbeoordeling'
;

COMMENT ON COLUMN "Klantbeoordeling"."Kanaal"
	IS 'waar de beoordeling is uitgevoerd, te weten op de website, naar aanleiding van een webformulier of na schriftelijke uitvraag vanuit onze organisatie'
;

COMMENT ON COLUMN "Klantbeoordeling"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Klantbeoordeling"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Klantbeoordeling"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Klantbeoordeling"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Klantbeoordeling"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Klantbeoordeling"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Klantbeoordeling"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Klantbeoordeling"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Klantbeoordelingreden"
	IS 'Reden voor de beoordeling Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Klantbeoordelingreden"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Klantbeoordelingreden"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Klantbeoordelingreden"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Klantbeoordelingreden"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Klantbeoordelingreden"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Klantbeoordelingreden"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Klantbeoordelingreden"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Klantbeoordelingreden"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_aanvraagofmelding_onderwerp"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_aanvraagofmelding_onderwerp"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_aanvraagofmelding_onderwerp"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_aanvraagofmelding_onderwerp"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_aanvraagofmelding_onderwerp"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_aanvraagofmelding_onderwerp"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_aanvraagofmelding_onderwerp"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_aanvraagofmelding_onderwerp"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_balieafspraak_productofdien"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_balieafspraak_productofdien"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_balieafspraak_productofdien"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_balieafspraak_productofdien"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_balieafspraak_productofdien"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_balieafspraak_productofdien"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_balieafspraak_productofdien"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_balieafspraak_productofdien"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_formuliersoort_zaaktype"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_formuliersoort_zaaktype"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_formuliersoort_zaaktype"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_formuliersoort_zaaktype"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_formuliersoort_zaaktype"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_formuliersoort_zaaktype"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_formuliersoort_zaaktype"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_formuliersoort_zaaktype"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_klantcontact_productofdiens"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_klantcontact_productofdiens"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_klantcontact_productofdiens"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_klantcontact_productofdiens"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_klantcontact_productofdiens"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_klantcontact_productofdiens"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_klantcontact_productofdiens"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_klantcontact_productofdiens"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_organisatorischeeenheid_kla"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_organisatorischeeenheid_kla"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_organisatorischeeenheid_kla"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_organisatorischeeenheid_kla"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_organisatorischeeenheid_kla"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_organisatorischeeenheid_kla"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_organisatorischeeenheid_kla"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_organisatorischeeenheid_kla"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_productofdienst_klantbeoord"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_productofdienst_klantbeoord"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_productofdienst_klantbeoord"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_productofdienst_klantbeoord"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_productofdienst_klantbeoord"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_productofdienst_klantbeoord"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_productofdienst_klantbeoord"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_productofdienst_klantbeoord"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Mor_aanvraagofmelding"
	IS 'Bericht van een inwoner over een gebrek of opvallendheid in de openbare ruimte Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Mor_aanvraagofmelding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Mor_aanvraagofmelding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Mor_aanvraagofmelding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Mor_aanvraagofmelding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Mor_aanvraagofmelding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Mor_aanvraagofmelding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Mor_aanvraagofmelding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Mor_aanvraagofmelding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Onderwerp"
	IS 'Bron: GEM_VJV_ONDERWERP
ID: ONDERWERP_ID Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Onderwerp"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Onderwerp"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Onderwerp"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Onderwerp"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Onderwerp"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Onderwerp"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Onderwerp"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Onderwerp"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Productofdienst"
	IS 'Bron: QP_CALENDAR.CFM_SERVICES Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Productofdienst"."Afhandeltijd"
	IS 'Standaard afhandeltijd in minuten'
;

COMMENT ON COLUMN "Productofdienst"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Productofdienst"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Productofdienst"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Productofdienst"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Productofdienst"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Productofdienst"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Productofdienst"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Productofdienst"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Telefoononderwerp"
	IS 'Onderwerp waarover het telefooncontact gaat Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Telefoononderwerp"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Telefoononderwerp"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Telefoononderwerp"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Telefoononderwerp"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Telefoononderwerp"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Telefoononderwerp"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Telefoononderwerp"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Telefoononderwerp"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Telefoonstatus"
	IS '
 ABANDONEDALERTING: “Opgehangen tijdens overgaan telefoon”
 DROPPEDCANCELED: “Opgehangen door systeem”
 ABANDONEDQUEUED: “Opgehangen tijdens wachten, zonder boodschap. ”
 CONNECTEDDIRECT: “Direct verbonden”
 CONNECTEDQUEUEDANNOUNCE: “Verbonden na wachtrij met boodschap”
 AbandonedQUEUEDANNOUNCE: “Opgehangen in wachtrij met boodschap”
 DroppedBusy: “Opgehangen door systeem, te druk”
 REJECTED: “Geweigerd door systeem”
 Droppedoverload: “Opgehangen door systeem vanwege overbelasting”
 Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Telefoonstatus"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Telefoonstatus"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Telefoonstatus"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Telefoonstatus"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Telefoonstatus"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Telefoonstatus"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Telefoonstatus"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Telefoonstatus"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Telefoontje"
	IS 'De telefoontgesprekken zijn alle keren dat iemand naar de gemeente belt en het telefoonsysteem neemt deze telefoongesprekken aan. Ongeacht of iemand daarna ophangt, door het systeem uit de wachtrij wordt gezet, doorverbonden wordt met een derde partij of er werkelijk wordt opgenomen.      Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Telefoontje"."Afhandeltijdnagesprek"
	IS 'De tijd die de medewerker nodig heeft om het telefoontje af te handelen totdat hij/zij klaar is voor een volgend telefoontje'
;

COMMENT ON COLUMN "Telefoontje"."Deltaisdnconnectie"
	IS 'De totale tijd dat er een teelfoonverbinding was minus totale wachttijd, spreektijd en on hold-tijd.'
;

COMMENT ON COLUMN "Telefoontje"."Eindtijd"
	IS 'Het moment dat de telefooncentrale het telefoontjes beeindigd'
;

COMMENT ON COLUMN "Telefoontje"."Starttijd"
	IS 'Het moment dat de telefooncentrale een telefoontje in behandeling neemt. Dit ligt voor de starttijd van het klantcontact'
;

COMMENT ON COLUMN "Telefoontje"."Totaleonholdtijd"
	IS 'De totale tijd dat een beller tussen klantcontacten "on hold" wordt gezet.'
;

COMMENT ON COLUMN "Telefoontje"."Totalespreektijd"
	IS 'De totale tijd dat met een (of meer) medewerkers van de gemeente wordt gebeld.'
;

COMMENT ON COLUMN "Telefoontje"."Totaletijdsduur"
	IS 'Tijd tussen start- en eindtijd van telefoontje'
;

COMMENT ON COLUMN "Telefoontje"."Totalewachttijd"
	IS 'De tijd tussen de starttijd van het telefoontje en het moment dat het telefoontje voor het eerst wordt opgenomen, of het telefoontje wordt afgesloten '
;

COMMENT ON COLUMN "Telefoontje"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Telefoontje"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Telefoontje"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Telefoontje"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Telefoontje"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Telefoontje"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Telefoontje"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Telefoontje"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
