/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version "17".0 		*/
/*  Created On : "06"-mrt-2025 "13":31:53 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Enum_aantalGehinderden" CASCADE
;

DROP TABLE IF EXISTS "Enum_hindercategorie" CASCADE
;

DROP TABLE IF EXISTS "Enum_hinderklasse" CASCADE
;

DROP TABLE IF EXISTS "Enum_stremmingstatus" CASCADE
;

DROP TABLE IF EXISTS "Kp_stremming_wegdeel" CASCADE
;

DROP TABLE IF EXISTS "Stremming" CASCADE
;

DROP TABLE IF EXISTS "Strooidag" CASCADE
;

DROP TABLE IF EXISTS "Strooiroute" CASCADE
;

DROP TABLE IF EXISTS "Strooirouteuitvoering" CASCADE
;

DROP TABLE IF EXISTS "Verkeersbesluit" CASCADE
;

DROP TABLE IF EXISTS "Verkeerstelling" CASCADE
;

DROP TABLE IF EXISTS "Vloginfo" CASCADE
;

/* Create Tables */

CREATE TABLE "Enum_aantalGehinderden"
(
	"minder dan 1000" varchar(50) NULL,
	"1.000 tot 10.000" varchar(50) NULL,
	"10.000 tot 100.000" varchar(50) NULL,
	"100.000 tot 1.000.000" varchar(50) NULL,
	"meer dan 1.000.000" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_hindercategorie"
(
	"A" varchar(50) NULL,
	"B" varchar(50) NULL,
	"C" varchar(50) NULL,
	"D" varchar(50) NULL,
	"E" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_hinderklasse"
(
	"Klasse 0: Geen hinder" varchar(50) NULL,
	"Klasse 1: Kleine hinder" varchar(50) NULL,	-- Geen file: vertraging < 5 minuten
	"Klasse 2: Matige hinder" varchar(50) NULL,	-- 5 tot "10" minuten vertraging door file of omrijden
	"Klasse 3: Grote hinder" varchar(50) NULL,	-- "10" tot "30" minuten vertraging door file of omrijden
	"Klasse 4: Zeer grote hinder" varchar(50) NULL,	-- > "30" minuten vertraging door file of omrijden
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_stremmingstatus"
(
	"Afgerond" integer NULL,
	"In Uitvoering" integer NULL,
	"Gepulbliceerd" integer NULL,
	"Aangemeld" integer NULL,
	"Plan Afhandelen" integer NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Kp_stremming_wegdeel"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"StremmingID" integer NULL,
	"WegdeelID" integer NULL
)
;

CREATE TABLE "Stremming"
(
	"Aantalgehinderden" varchar(50) NULL,
	"Datumaanmelding" timestamp without time zone NULL,
	"Datumeinde" timestamp without time zone NULL,
	"Datumstart" timestamp without time zone NULL,
	"Datumwijziging" timestamp without time zone NULL,
	"Delentoegestaan" boolean NULL,
	"Geschiktvoorpublicatie" boolean NULL,
	"Hinderklasse" varchar(50) NULL,
	"Locatie" varchar(50) NULL,
	"Naam" varchar(250) NULL,
	"Status" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"StremmingID" integer NOT NULL,
	"MedewerkerID" integer NULL
)
;

CREATE TABLE "Strooidag"
(
	"Datum" date NULL,
	"Maximumtemperatuur" double precision,
	"Minimumtemperatuur" double precision,
	"Tijdmaximumtemperatuur" time without time zone NULL,
	"Tijdminimumtemperatuur" time without time zone NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"StrooidagID" integer NOT NULL
)
;

CREATE TABLE "Strooiroute"
(
	"Route" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"StrooirouteID" integer NOT NULL
)
;

CREATE TABLE "Strooirouteuitvoering"
(
	"Geplandeinde" timestamp without time zone NULL,
	"Geplandstart" timestamp without time zone NULL,
	"Route" varchar(50) NULL,
	"Werkelijkeinde" timestamp without time zone NULL,
	"Werkelijkestart" timestamp without time zone NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"StrooirouteuitvoeringID" integer NOT NULL,
	"StrooidagID" integer NULL,
	"StrooirouteID" integer NULL
)
;

CREATE TABLE "Verkeersbesluit"
(
	"Datumbesluit" date NULL,
	"Datumeinde" timestamp without time zone NULL,
	"Datumstart" timestamp without time zone NULL,
	"Huisnummer" varchar(40) NULL,
	"Postcode" varchar(6) NULL,
	"Referentienummer" varchar(80) NULL,
	"Straat" varchar(200) NULL,
	"Titel" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VerkeersbesluitID" integer NOT NULL
)
;

CREATE TABLE "Verkeerstelling"
(
	"Aantal" integer NULL,
	"Tijdtot" timestamp without time zone NULL,
	"Tijdvanaf" timestamp without time zone NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VerkeerstellingID" integer NOT NULL,
	"SensorID" integer NULL
)
;

CREATE TABLE "Vloginfo"
(
	"Detectieverkeer" integer NULL,
	"Eindegroen" boolean NULL,
	"Snelheid" integer NULL,
	"Startgroen" boolean NULL,
	"Tijdstip" timestamp without time zone NULL,
	"Verkeerwilgroen" boolean NULL,
	"Wachttijd" integer NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VloginfoID" integer NOT NULL,
	"KastID" integer NULL,
	"PaalID" integer NULL,
	"SensorID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Enum_aantalGehinderden" ADD CONSTRAINT "PK_Enum_aantalGehinderden"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_hindercategorie" ADD CONSTRAINT "PK_Enum_hindercategorie"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_hinderklasse" ADD CONSTRAINT "PK_Enum_hinderklasse"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_stremmingstatus" ADD CONSTRAINT "PK_Enum_stremmingstatus"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Stremming" ADD CONSTRAINT "PK_Stremming"
	PRIMARY KEY ("StremmingID")
;

ALTER TABLE "Strooidag" ADD CONSTRAINT "PK_Strooidag"
	PRIMARY KEY ("StrooidagID")
;

ALTER TABLE "Strooiroute" ADD CONSTRAINT "PK_Strooiroute"
	PRIMARY KEY ("StrooirouteID")
;

ALTER TABLE "Strooirouteuitvoering" ADD CONSTRAINT "PK_Strooirouteuitvoering"
	PRIMARY KEY ("StrooirouteuitvoeringID")
;

ALTER TABLE "Verkeersbesluit" ADD CONSTRAINT "PK_Verkeersbesluit"
	PRIMARY KEY ("VerkeersbesluitID")
;

ALTER TABLE "Verkeerstelling" ADD CONSTRAINT "PK_Verkeerstelling"
	PRIMARY KEY ("VerkeerstellingID")
;

ALTER TABLE "Vloginfo" ADD CONSTRAINT "PK_Vloginfo"
	PRIMARY KEY ("VloginfoID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Kp_stremming_wegdeel" ADD CONSTRAINT "Fk_kp_stremming_wegdeel_stremming"
	FOREIGN KEY ("StremmingID") REFERENCES "Stremming" ("StremmingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_stremming_wegdeel" ADD CONSTRAINT "Fk_kp_stremming_wegdeel_wegdeel"
	FOREIGN KEY ("WegdeelID") REFERENCES "Wegdeel" ("WegdeelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stremming" ADD CONSTRAINT "fk_gewijzigdDoor_medewerker"
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stremming" ADD CONSTRAINT "fk_ingevoerdDoor_medewerker"
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Strooirouteuitvoering" ADD CONSTRAINT "FK_Strooirouteuitvoering_Strooidag"
	FOREIGN KEY ("StrooidagID") REFERENCES "Strooidag" ("StrooidagID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Strooirouteuitvoering" ADD CONSTRAINT "FK_Strooirouteuitvoering_Strooiroute"
	FOREIGN KEY ("StrooirouteID") REFERENCES "Strooiroute" ("StrooirouteID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Verkeerstelling" ADD CONSTRAINT "fk_gegenereerdDoor_sensor"
	FOREIGN KEY ("SensorID") REFERENCES "Sensor" ("SensorID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vloginfo" ADD CONSTRAINT "FK_Vloginfo_Kast"
	FOREIGN KEY ("KastID") REFERENCES "Kast" ("KastID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vloginfo" ADD CONSTRAINT "FK_Vloginfo_Paal"
	FOREIGN KEY ("PaalID") REFERENCES "Paal" ("PaalID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vloginfo" ADD CONSTRAINT "FK_Vloginfo_Sensor"
	FOREIGN KEY ("SensorID") REFERENCES "Sensor" ("SensorID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "Enum_hinderklasse"."Klasse 1: Kleine hinder"
	IS 'Geen file: vertraging < 5 minuten'
;

COMMENT ON COLUMN "Enum_hinderklasse"."Klasse 2: Matige hinder"
	IS '5 tot "10" minuten vertraging door file of omrijden'
;

COMMENT ON COLUMN "Enum_hinderklasse"."Klasse 3: Grote hinder"
	IS '10 tot "30" minuten vertraging door file of omrijden'
;

COMMENT ON COLUMN "Enum_hinderklasse"."Klasse 4: Zeer grote hinder"
	IS '> "30" minuten vertraging door file of omrijden'
;

COMMENT ON COLUMN "Kp_stremming_wegdeel"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_stremming_wegdeel"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_stremming_wegdeel"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_stremming_wegdeel"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_stremming_wegdeel"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_stremming_wegdeel"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_stremming_wegdeel"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_stremming_wegdeel"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Stremming"
	IS 'Situatie waarbij de doorstroming van het (vaar)wegverkeer plaatselijk is geblokkeerd als gevolg van een incident Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Stremming"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Stremming"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Stremming"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Stremming"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Stremming"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Stremming"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Stremming"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Stremming"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Strooidag"
	IS 'Dag waarop op wegen gestrooid wordt ter voorkoming van gladheid Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Strooidag"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Strooidag"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Strooidag"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Strooidag"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Strooidag"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Strooidag"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Strooidag"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Strooidag"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Strooiroute"
	IS 'Traject waarop het strooien plaatsvindt Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Strooiroute"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Strooiroute"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Strooiroute"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Strooiroute"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Strooiroute"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Strooiroute"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Strooiroute"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Strooiroute"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Strooirouteuitvoering"
	IS 'De route die uiteindelijk is gevolgd voor het strooien  Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Strooirouteuitvoering"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Strooirouteuitvoering"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Strooirouteuitvoering"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Strooirouteuitvoering"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Strooirouteuitvoering"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Strooirouteuitvoering"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Strooirouteuitvoering"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Strooirouteuitvoering"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Verkeersbesluit"
	IS 'Een besluit van een wegbeheerder om een bepaald verkeersteken te plaatsen, te wijzigen of in te trekken of een bepaalde fysieke maatregel te treffen.  Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Verkeersbesluit"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Verkeersbesluit"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Verkeersbesluit"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Verkeersbesluit"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Verkeersbesluit"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Verkeersbesluit"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Verkeersbesluit"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Verkeersbesluit"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Verkeerstelling"
	IS 'Een onderzoek om inzicht te krijgen in het verkeer, in de hoeveelheid verkeer, de verdeling en de gereden snelheid. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Verkeerstelling"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Verkeerstelling"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Verkeerstelling"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Verkeerstelling"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Verkeerstelling"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Verkeerstelling"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Verkeerstelling"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Verkeerstelling"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vloginfo"
	IS 'V-log is een open standaard voor datalogging van een verkeersregelinstallatie. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vloginfo"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vloginfo"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vloginfo"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vloginfo"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vloginfo"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vloginfo"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vloginfo"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vloginfo"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
