/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version "17".0 		*/
/*  Created On : "06"-mrt-2025 "13":30:55 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Belprovider" CASCADE
;

DROP TABLE IF EXISTS "Enum_doelgroepenplaatsen" CASCADE
;

DROP TABLE IF EXISTS "Enum_zonesoort" CASCADE
;

DROP TABLE IF EXISTS "Kp_parkeerrecht_perkeerzone" CASCADE
;

DROP TABLE IF EXISTS "Kp_parkeervergunning_perkeerzo" CASCADE
;

DROP TABLE IF EXISTS "Mulderfeit" CASCADE
;

DROP TABLE IF EXISTS "Naheffing" CASCADE
;

DROP TABLE IF EXISTS "Parkeergarage" CASCADE
;

DROP TABLE IF EXISTS "Parkeerrecht" CASCADE
;

DROP TABLE IF EXISTS "Parkeerscan" CASCADE
;

DROP TABLE IF EXISTS "Parkeervergunning" CASCADE
;

DROP TABLE IF EXISTS "Parkeervlak" CASCADE
;

DROP TABLE IF EXISTS "Perkeerzone" CASCADE
;

DROP TABLE IF EXISTS "Productgroep" CASCADE
;

DROP TABLE IF EXISTS "Productsoort" CASCADE
;

DROP TABLE IF EXISTS "Straatsectie" CASCADE
;

DROP TABLE IF EXISTS "Voertuig" CASCADE
;

/* Create Tables */

CREATE TABLE "Belprovider"
(
	"Code" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"BelproviderID" integer NOT NULL
)
;

CREATE TABLE "Enum_doelgroepenplaatsen"
(
	"DP01" varchar(50) NULL,	-- gehandicapten paarkeerplaatsen algemeen
	"DP02" varchar(50) NULL,	-- gehandicapten parkeerplaatsen kenteken
	"DP03" varchar(50) NULL,	-- deelautoplaatsen
	"DP04" varchar(50) NULL,	-- oplaadplaatsen elektrische auto's
	"DP05" varchar(50) NULL,	-- laad- en losplaatsen
	"Leeg" varchar(50) NULL,	-- Geen beperking
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_zonesoort"
(
	"GSM-Zone" varchar(50) NULL,
	"Vergunninghouderzone" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Kp_parkeerrecht_perkeerzone"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"PerkeerzoneID" integer NULL,
	"ParkeerrechtID" integer NULL
)
;

CREATE TABLE "Kp_parkeervergunning_perkeerzo"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"PerkeerzoneID" integer NULL,
	"ParkeervergunningID" integer NULL
)
;

CREATE TABLE "Mulderfeit"
(
	"Bedrag" double precision,
	"Bezwaarafgehandeld" date NULL,
	"Bezwaaringetrokken" date NULL,
	"Bezwaartoegewezen" date NULL,
	"Bonnummer" integer NULL,
	"Datumbetaling" date NULL,
	"Datumbezwaar" date NULL,
	"Datumgeseponeerd" date NULL,
	"Datumindiening" date NULL,
	"Dienstcd" varchar(40) NULL,
	"Organisatie" varchar(200) NULL,
	"Overtreding" varchar(80) NULL,
	"Parkeertarief" double precision,
	"Redenseponeren" varchar(300) NULL,
	"Vorderingnummer" integer NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"MulderfeitID" integer NOT NULL,
	"VoertuigID" integer NULL
)
;

CREATE TABLE "Naheffing"
(
	"Bedrag" double precision,
	"Bezwaarafgehandeld" date NULL,
	"Bezwaaringetrokken" date NULL,
	"Bezwaartoegewezen" date NULL,
	"Bonnummer" integer NULL,
	"Datumbetaling" date NULL,
	"Datumbezwaar" date NULL,
	"Datumgeseponeerd" date NULL,
	"Datumindiening" date NULL,
	"Dienstcd" varchar(40) NULL,
	"Fiscaal" boolean NULL,
	"Organisatie" varchar(200) NULL,
	"Overtreding" varchar(80) NULL,
	"Parkeertarief" double precision,
	"Redenseponeren" varchar(300) NULL,
	"Vorderingnummer" integer NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"NaheffingID" integer NOT NULL,
	"ParkeerscanID" integer NULL
)
;

CREATE TABLE "Parkeergarage"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ParkeergarageID" integer NOT NULL
)
;

CREATE TABLE "Parkeerrecht"
(
	"Aanmaaktijd" timestamp without time zone NULL,
	"Bedragaankoop" double precision,	-- Bedrag incl. BTW
	"Bedragbtw" double precision,
	"Datumtijdeinde" timestamp without time zone NULL,
	"Datumtijdstart" timestamp without time zone NULL,
	"Productnaam" varchar(80) NULL,
	"Productomschrijving" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ParkeerrechtID" integer NOT NULL,
	"BelproviderID" integer NULL,
	"VoertuigID" integer NULL,
	"ParkeerscanID" integer NULL,
	"ParkeervergunningID" integer NULL
)
;

CREATE TABLE "Parkeerscan"
(
	"Codegebruiker" varchar(40) NULL,
	"Codescanvoertuig" varchar(40) NULL,
	"Coordinaten_lat" double precision,
	"Coordinaten_long" double precision,
	"Coordinaten_rdx" double precision,
	"Coordinaten_rdy" double precision,
	"Foto" bytea NULL,
	"Kenteken" varchar(12) NULL,
	"Parkeerrecht" boolean NULL,
	"Tijdstip" timestamp without time zone NULL,
	"Transactieid" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ParkeerscanID" integer NOT NULL,
	"VoertuigID" integer NULL,
	"ParkeervlakID" integer NULL,
	"MedewerkerID" integer NULL
)
;

CREATE TABLE "Parkeervergunning"
(
	"Datumeindegeldigheid" timestamp without time zone NULL,
	"Datumreservering" date NULL,
	"Datumstart" timestamp without time zone NULL,
	"Kenteken" varchar(12) NULL,
	"Minutenafgeschreven" integer NULL,
	"Minutengeldig" integer NULL,
	"Minutenresterend" integer NULL,
	"Nummer" integer NULL,
	"Type" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ParkeervergunningID" integer NOT NULL,
	"ProductgroepID" integer NULL,
	"ProductsoortID" integer NULL,
	"IngezeteneID" integer NULL,
	"RechtspersoonID" integer NULL
)
;

CREATE TABLE "Parkeervlak"
(
	"Aantal" integer NULL,
	"Coordinaten_lat" double precision,
	"Coordinaten_long" double precision,
	"Coordinaten_rdx" double precision,
	"Coordinaten_rdy" double precision,
	"Doelgroep" varchar(50) NULL,
	"Fiscaal" boolean NULL,
	"Plaats" varchar(200) NULL,
	"Vlakid" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ParkeervlakID" integer NOT NULL,
	"PerkeerzoneID" integer NULL,
	"StraatsectieID" integer NULL
)
;

CREATE TABLE "Perkeerzone"
(
	"Aantalparkeervlakken" integer NULL,
	"Alleendagtarief" boolean NULL,
	"Dagtarief" double precision,
	"Eindedag" varchar(20) NULL,
	"Eindtijd" integer NULL,
	"Gebruik" varchar(250) NULL,
	"Geometrie" varchar(50) NULL,
	"Ipmcode" varchar(40) NULL,
	"Ipmnaam" varchar(250) NULL,
	"Naam" varchar(250) NULL,
	"Parkeergarage" boolean NULL,
	"Sectorcode" varchar(40) NULL,
	"Soortcode" varchar(40) NULL,
	"Startdag" varchar(20) NULL,
	"Starttarief" double precision,
	"Starttijd" integer NULL,
	"Typecode" varchar(40) NULL,
	"Typenaam" varchar(250) NULL,
	"Uurtarief" double precision,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"PerkeerzoneID" integer NOT NULL
)
;

CREATE TABLE "Productgroep"
(
	"Beslisboom" varchar(250) NULL,
	"Code" varchar(40) NULL,
	"Omschrijving" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ProductgroepID" integer NOT NULL
)
;

CREATE TABLE "Productsoort"
(
	"Code" varchar(40) NULL,
	"Omschrijving" varchar(250) NULL,
	"Tarief" double precision,
	"Tariefperiode" varchar(20) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ProductsoortID" integer NOT NULL,
	"ProductgroepID" integer NULL
)
;

CREATE TABLE "Straatsectie"
(
	"Code" varchar(40) NULL,
	"Omschrijving" varchar(500) NULL,
	"Zonecode" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"StraatsectieID" integer NOT NULL,
	"PerkeerzoneID" integer NULL
)
;

CREATE TABLE "Voertuig"
(
	"Kenteken" varchar(12) NULL,
	"Kleur" varchar(200) NULL,
	"Land" varchar(200) NULL,
	"Merk" varchar(200) NULL,
	"Type" varchar(200) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VoertuigID" integer NOT NULL,
	"ObjectID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Belprovider" ADD CONSTRAINT "PK_Belprovider"
	PRIMARY KEY ("BelproviderID")
;

ALTER TABLE "Enum_doelgroepenplaatsen" ADD CONSTRAINT "PK_Enum_doelgroepenplaatsen"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_zonesoort" ADD CONSTRAINT "PK_Enum_zonesoort"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Mulderfeit" ADD CONSTRAINT "PK_Mulderfeit"
	PRIMARY KEY ("MulderfeitID")
;

ALTER TABLE "Naheffing" ADD CONSTRAINT "PK_Naheffing"
	PRIMARY KEY ("NaheffingID")
;

ALTER TABLE "Parkeergarage" ADD CONSTRAINT "PK_Parkeergarage"
	PRIMARY KEY ("ParkeergarageID")
;

ALTER TABLE "Parkeerrecht" ADD CONSTRAINT "PK_Parkeerrecht"
	PRIMARY KEY ("ParkeerrechtID")
;

ALTER TABLE "Parkeerscan" ADD CONSTRAINT "PK_Parkeerscan"
	PRIMARY KEY ("ParkeerscanID")
;

ALTER TABLE "Parkeervergunning" ADD CONSTRAINT "PK_Parkeervergunning"
	PRIMARY KEY ("ParkeervergunningID")
;

ALTER TABLE "Parkeervlak" ADD CONSTRAINT "PK_Parkeervlak"
	PRIMARY KEY ("ParkeervlakID")
;

ALTER TABLE "Perkeerzone" ADD CONSTRAINT "PK_Perkeerzone"
	PRIMARY KEY ("PerkeerzoneID")
;

ALTER TABLE "Productgroep" ADD CONSTRAINT "PK_Productgroep"
	PRIMARY KEY ("ProductgroepID")
;

ALTER TABLE "Productsoort" ADD CONSTRAINT "PK_Productsoort"
	PRIMARY KEY ("ProductsoortID")
;

ALTER TABLE "Straatsectie" ADD CONSTRAINT "PK_Straatsectie"
	PRIMARY KEY ("StraatsectieID")
;

ALTER TABLE "Voertuig" ADD CONSTRAINT "PK_Voertuig"
	PRIMARY KEY ("VoertuigID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Belprovider" ADD CONSTRAINT "Fk_belprovider_leverancier"
	FOREIGN KEY ("BelproviderID") REFERENCES "Leverancier" ("LeverancierID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_parkeerrecht_perkeerzone" ADD CONSTRAINT "Fk_kp_parkeerrecht_perkeerzone_perkeerzone"
	FOREIGN KEY ("PerkeerzoneID") REFERENCES "Perkeerzone" ("PerkeerzoneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_parkeerrecht_perkeerzone" ADD CONSTRAINT "Fk_kp_parkeerrecht_perkeerzone_parkeerrecht"
	FOREIGN KEY ("ParkeerrechtID") REFERENCES "Parkeerrecht" ("ParkeerrechtID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_parkeervergunning_perkeerzo" ADD CONSTRAINT "Fk_kp_parkeervergunning_perkeerzo_perkeerzone"
	FOREIGN KEY ("PerkeerzoneID") REFERENCES "Perkeerzone" ("PerkeerzoneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_parkeervergunning_perkeerzo" ADD CONSTRAINT "Fk_kp_parkeervergunning_perkeerzo_parkeervergunning"
	FOREIGN KEY ("ParkeervergunningID") REFERENCES "Parkeervergunning" ("ParkeervergunningID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Mulderfeit" ADD CONSTRAINT "FK_Mulderfeit_Voertuig"
	FOREIGN KEY ("VoertuigID") REFERENCES "Voertuig" ("VoertuigID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Naheffing" ADD CONSTRAINT "fk_komtVoortUit_parkeerscan"
	FOREIGN KEY ("ParkeerscanID") REFERENCES "Parkeerscan" ("ParkeerscanID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeergarage" ADD CONSTRAINT "Fk_parkeergarage_perkeerzone"
	FOREIGN KEY ("ParkeergarageID") REFERENCES "Perkeerzone" ("PerkeerzoneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeerrecht" ADD CONSTRAINT "FK_Parkeerrecht_Belprovider"
	FOREIGN KEY ("BelproviderID") REFERENCES "Belprovider" ("BelproviderID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeerrecht" ADD CONSTRAINT "FK_Parkeerrecht_Voertuig"
	FOREIGN KEY ("VoertuigID") REFERENCES "Voertuig" ("VoertuigID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeerrecht" ADD CONSTRAINT fk_verificatie_parkeerscan
	FOREIGN KEY ("ParkeerscanID") REFERENCES "Parkeerscan" ("ParkeerscanID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeerrecht" ADD CONSTRAINT fk_resulteert_parkeervergunnin
	FOREIGN KEY ("ParkeervergunningID") REFERENCES "Parkeervergunning" ("ParkeervergunningID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeerscan" ADD CONSTRAINT "FK_Parkeerscan_Voertuig"
	FOREIGN KEY ("VoertuigID") REFERENCES "Voertuig" ("VoertuigID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeerscan" ADD CONSTRAINT "FK_Parkeerscan_Parkeervlak"
	FOREIGN KEY ("ParkeervlakID") REFERENCES "Parkeervlak" ("ParkeervlakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeerscan" ADD CONSTRAINT "FK_Parkeerscan_Medewerker"
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeervergunning" ADD CONSTRAINT fk_soort_productgroep
	FOREIGN KEY ("ProductgroepID") REFERENCES "Productgroep" ("ProductgroepID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeervergunning" ADD CONSTRAINT fk_soort_productsoort
	FOREIGN KEY ("ProductsoortID") REFERENCES "Productsoort" ("ProductsoortID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeervergunning" ADD CONSTRAINT "FK_Parkeervergunning_Ingezetene"
	FOREIGN KEY ("IngezeteneID") REFERENCES "Ingezetene" ("IngezeteneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeervergunning" ADD CONSTRAINT "FK_Parkeervergunning_Rechtspersoon"
	FOREIGN KEY ("RechtspersoonID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeervlak" ADD CONSTRAINT fk_bevat_perkeerzone
	FOREIGN KEY ("PerkeerzoneID") REFERENCES "Perkeerzone" ("PerkeerzoneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Parkeervlak" ADD CONSTRAINT fk_bevat_straatsectie
	FOREIGN KEY ("StraatsectieID") REFERENCES "Straatsectie" ("StraatsectieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Productsoort" ADD CONSTRAINT "FK_Productsoort_Productgroep"
	FOREIGN KEY ("ProductgroepID") REFERENCES "Productgroep" ("ProductgroepID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Straatsectie" ADD CONSTRAINT fk_bevat_perkeerzone
	FOREIGN KEY ("PerkeerzoneID") REFERENCES "Perkeerzone" ("PerkeerzoneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Voertuig" ADD CONSTRAINT fk_is_object
	FOREIGN KEY ("ObjectID") REFERENCES "Object" ("ObjectID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Belprovider"
	IS 'Leverancier of dienstverlener van modiele beldiensten Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Belprovider"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Belprovider"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Belprovider"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Belprovider"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Belprovider"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Belprovider"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Belprovider"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Belprovider"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Enum_doelgroepenplaatsen"."DP01"
	IS 'gehandicapten paarkeerplaatsen algemeen'
;

COMMENT ON COLUMN "Enum_doelgroepenplaatsen"."DP02"
	IS 'gehandicapten parkeerplaatsen kenteken'
;

COMMENT ON COLUMN "Enum_doelgroepenplaatsen"."DP03"
	IS 'deelautoplaatsen'
;

COMMENT ON COLUMN "Enum_doelgroepenplaatsen"."DP04"
	IS 'oplaadplaatsen elektrische auto''s'
;

COMMENT ON COLUMN "Enum_doelgroepenplaatsen"."DP05"
	IS 'laad- en losplaatsen'
;

COMMENT ON COLUMN "Enum_doelgroepenplaatsen"."Leeg"
	IS 'Geen beperking'
;

COMMENT ON COLUMN "Kp_parkeerrecht_perkeerzone"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_parkeerrecht_perkeerzone"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_parkeerrecht_perkeerzone"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_parkeerrecht_perkeerzone"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_parkeerrecht_perkeerzone"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_parkeerrecht_perkeerzone"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_parkeerrecht_perkeerzone"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_parkeerrecht_perkeerzone"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_parkeervergunning_perkeerzo"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_parkeervergunning_perkeerzo"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_parkeervergunning_perkeerzo"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_parkeervergunning_perkeerzo"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_parkeervergunning_perkeerzo"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_parkeervergunning_perkeerzo"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_parkeervergunning_perkeerzo"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_parkeervergunning_perkeerzo"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Mulderfeit"
	IS 'Een administratieve overtreding met betrekking tot parkeren, zoals bepaald onder de Wet administratiefrechtelijke handhaving verkeersvoorschriften (WAHV), ook wel bekend als de Mulderwet. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Mulderfeit"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Mulderfeit"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Mulderfeit"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Mulderfeit"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Mulderfeit"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Mulderfeit"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Mulderfeit"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Mulderfeit"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Naheffing"
	IS 'Het achteraf vorderen van te weinig betaalde belasting  Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Naheffing"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Naheffing"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Naheffing"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Naheffing"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Naheffing"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Naheffing"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Naheffing"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Naheffing"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Parkeergarage"
	IS 'Open constructie die geheel of gedeeltelijk in gebruik is als voorziening voor het parkeren van voertuigen Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Parkeergarage"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Parkeergarage"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Parkeergarage"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Parkeergarage"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Parkeergarage"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Parkeergarage"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Parkeergarage"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Parkeergarage"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Parkeerrecht"
	IS 'Het onder bepaalde voorwaarden (zoals betaling parkeerbelasting of parkeergeld) ontstane recht om een voertuig gedurende een bepaalde of onbepaalde periode op een daartoe benoemde parkeerplaats of in/op een daartoe benoemde parkeervoorziening te parkeren. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Parkeerrecht"."Bedragaankoop"
	IS 'Bedrag incl. BTW'
;

COMMENT ON COLUMN "Parkeerrecht"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Parkeerrecht"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Parkeerrecht"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Parkeerrecht"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Parkeerrecht"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Parkeerrecht"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Parkeerrecht"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Parkeerrecht"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Parkeerscan"
	IS 'Waarneming van een parkeeractie door een scanauto Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Parkeerscan"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Parkeerscan"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Parkeerscan"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Parkeerscan"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Parkeerscan"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Parkeerscan"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Parkeerscan"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Parkeerscan"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Parkeervergunning"
	IS 'Officiele toestemming dat je op een bepaalde plek mag parkeren Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Parkeervergunning"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Parkeervergunning"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Parkeervergunning"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Parkeervergunning"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Parkeervergunning"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Parkeervergunning"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Parkeervergunning"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Parkeervergunning"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Parkeervlak"
	IS 'Parkeergelegenheid bestemd voor het parkeren van een of meerdere voertuigen direct langs de doorgaande weg gelegen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Parkeervlak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Parkeervlak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Parkeervlak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Parkeervlak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Parkeervlak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Parkeervlak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Parkeervlak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Parkeervlak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Perkeerzone"
	IS 'Een afgebakend gebied binnen een gemeente  waar specifieke parkeerregels en -voorwaarden van toepassing zijn. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Perkeerzone"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Perkeerzone"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Perkeerzone"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Perkeerzone"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Perkeerzone"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Perkeerzone"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Perkeerzone"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Perkeerzone"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Productgroep"
	IS 'Groepering van producten Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Productgroep"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Productgroep"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Productgroep"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Productgroep"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Productgroep"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Productgroep"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Productgroep"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Productgroep"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Productsoort"
	IS 'Typologie van een product Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Productsoort"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Productsoort"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Productsoort"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Productsoort"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Productsoort"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Productsoort"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Productsoort"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Productsoort"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Straatsectie"
	IS 'Gedeelte van een straat Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Straatsectie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Straatsectie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Straatsectie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Straatsectie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Straatsectie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Straatsectie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Straatsectie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Straatsectie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Voertuig"
	IS 'Vervoermiddel bestemd voor het verkeer over wegen Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Voertuig"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Voertuig"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Voertuig"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Voertuig"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Voertuig"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Voertuig"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Voertuig"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Voertuig"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
