/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version "17".0 		*/
/*  Created On : "06"-mrt-2025 "13":35:54 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Contact" CASCADE
;

DROP TABLE IF EXISTS "Hotel" CASCADE
;

DROP TABLE IF EXISTS "Hotelbezoek" CASCADE
;

DROP TABLE IF EXISTS "Kp_contact_natuurlijkpersoon" CASCADE
;

DROP TABLE IF EXISTS "Verkooppunt" CASCADE
;

DROP TABLE IF EXISTS "Werkgelegenheid" CASCADE
;

DROP TABLE IF EXISTS "Winkelvloeroppervlak" CASCADE
;

/* Create Tables */

CREATE TABLE "Contact"
(
	"Contactsoort" varchar(80) NULL,
	"Datum" date NULL,
	"Tekst" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ContactID" integer NOT NULL,
	"VestigingID" integer NULL
)
;

CREATE TABLE "Hotel"
(
	"Aantalkamers" integer NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"HotelID" integer NOT NULL
)
;

CREATE TABLE "Hotelbezoek"
(
	"Datumeinde" date NULL,
	"Datumstart" date NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"HotelbezoekID" integer NOT NULL,
	"HotelID" integer NULL
)
;

CREATE TABLE "Kp_contact_natuurlijkpersoon"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ContactID" integer NULL,
	"NatuurlijkpersoonID" integer NULL
)
;

CREATE TABLE "Verkooppunt"
(
	"Winkelformule" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VerkooppuntID" integer NOT NULL
)
;

CREATE TABLE "Werkgelegenheid"
(
	"Aantalfulltimemannen" integer NULL,
	"Aantalfulltimevrouwen" integer NULL,
	"Aantalparttimemannen" integer NULL,
	"Aantalparttimevrouwen" integer NULL,
	"Grootteklasse" varchar(2) NULL,	-- Grootteklasse volgens handboek LISA, zie lisa.nl 
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"WerkgelegenheidID" integer NOT NULL,
	"VestigingID" integer NULL
)
;

CREATE TABLE "Winkelvloeroppervlak"
(
	"Aantalkassa" integer NULL,
	"Bronwvo" varchar(40) NULL,
	"Leegstand" boolean NULL,
	"Winkelvloeroppervlakte" integer NULL,
	"Wvoklasse" varchar(40) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"WinkelvloeroppervlakID" integer NOT NULL,
	"GebouwdobjectID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Contact" ADD CONSTRAINT "PK_Contact"
	PRIMARY KEY ("ContactID")
;

ALTER TABLE "Hotel" ADD CONSTRAINT "PK_Hotel"
	PRIMARY KEY ("HotelID")
;

ALTER TABLE "Hotelbezoek" ADD CONSTRAINT "PK_Hotelbezoek"
	PRIMARY KEY ("HotelbezoekID")
;

ALTER TABLE "Verkooppunt" ADD CONSTRAINT "PK_Verkooppunt"
	PRIMARY KEY ("VerkooppuntID")
;

ALTER TABLE "Werkgelegenheid" ADD CONSTRAINT "PK_Werkgelegenheid"
	PRIMARY KEY ("WerkgelegenheidID")
;

ALTER TABLE "Winkelvloeroppervlak" ADD CONSTRAINT "PK_Winkelvloeroppervlak"
	PRIMARY KEY ("WinkelvloeroppervlakID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Contact" ADD CONSTRAINT "FK_Contact_Vestiging"
	FOREIGN KEY ("VestigingID") REFERENCES "Vestiging" ("VestigingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Hotel" ADD CONSTRAINT "Fk_hotel_vestiging"
	FOREIGN KEY ("HotelID") REFERENCES "Vestiging" ("VestigingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Hotelbezoek" ADD CONSTRAINT fk_heeft_hotel
	FOREIGN KEY ("HotelID") REFERENCES "Hotel" ("HotelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_contact_natuurlijkpersoon" ADD CONSTRAINT "Fk_kp_contact_natuurlijkpersoon_contact"
	FOREIGN KEY ("ContactID") REFERENCES "Contact" ("ContactID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_contact_natuurlijkpersoon" ADD CONSTRAINT "Fk_kp_contact_natuurlijkpersoon_natuurlijkpersoon"
	FOREIGN KEY ("NatuurlijkpersoonID") REFERENCES "Natuurlijkpersoon" ("NatuurlijkpersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Verkooppunt" ADD CONSTRAINT "Fk_verkooppunt_vestiging"
	FOREIGN KEY ("VerkooppuntID") REFERENCES "Vestiging" ("VestigingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Werkgelegenheid" ADD CONSTRAINT fk_heeft_vestiging
	FOREIGN KEY ("VestigingID") REFERENCES "Vestiging" ("VestigingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Winkelvloeroppervlak" ADD CONSTRAINT fk_heeft_gebouwdobject
	FOREIGN KEY ("GebouwdobjectID") REFERENCES "Gebouwdobject" ("GebouwdobjectID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Contact"
	IS 'Persoon waarmee communicatie plaatsvindt Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Contact"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Contact"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Contact"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Contact"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Contact"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Contact"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Contact"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Contact"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Hotel"
	IS 'Gebouw waar je tegen betaling kunt logeren. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Hotel"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Hotel"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Hotel"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Hotel"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Hotel"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Hotel"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Hotel"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Hotel"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Hotelbezoek"
	IS 'Verblijf in een hotel Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Hotelbezoek"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Hotelbezoek"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Hotelbezoek"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Hotelbezoek"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Hotelbezoek"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Hotelbezoek"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Hotelbezoek"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Hotelbezoek"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_contact_natuurlijkpersoon"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_contact_natuurlijkpersoon"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_contact_natuurlijkpersoon"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_contact_natuurlijkpersoon"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_contact_natuurlijkpersoon"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_contact_natuurlijkpersoon"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_contact_natuurlijkpersoon"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_contact_natuurlijkpersoon"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Verkooppunt"
	IS 'Locatie waar iets wordt verkocht Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Verkooppunt"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Verkooppunt"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Verkooppunt"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Verkooppunt"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Verkooppunt"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Verkooppunt"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Verkooppunt"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Verkooppunt"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Werkgelegenheid"
	IS 'De vraag naar arbeid, te berekenen door de totale productie te delen door de arbeidsproductiviteit per persoon. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Werkgelegenheid"."Grootteklasse"
	IS 'Grootteklasse volgens handboek LISA, zie lisa.nl '
;

COMMENT ON COLUMN "Werkgelegenheid"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Werkgelegenheid"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Werkgelegenheid"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Werkgelegenheid"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Werkgelegenheid"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Werkgelegenheid"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Werkgelegenheid"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Werkgelegenheid"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Winkelvloeroppervlak"
	IS 'Gemeten oppervlakte in vierkante meters van een winkel Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Winkelvloeroppervlak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Winkelvloeroppervlak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Winkelvloeroppervlak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Winkelvloeroppervlak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Winkelvloeroppervlak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Winkelvloeroppervlak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Winkelvloeroppervlak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Winkelvloeroppervlak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
