/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version "17".0 		*/
/*  Created On : "06"-mrt-2025 "14":43:19 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Conclusie" CASCADE
;

DROP TABLE IF EXISTS "Indieningsvereisten" CASCADE
;

DROP TABLE IF EXISTS "Kp_toepasbareRegel_locatie" CASCADE
;

DROP TABLE IF EXISTS "Maatregelen" CASCADE
;

DROP TABLE IF EXISTS "ToepasbareRegel" CASCADE
;

DROP TABLE IF EXISTS "Toepasbareregelbestand" CASCADE
;

DROP TABLE IF EXISTS "Uitvoeringsregel" CASCADE
;

/* Create Tables */

CREATE TABLE "Conclusie"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ConclusieID" integer NOT NULL
)
;

CREATE TABLE "Indieningsvereisten"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"IndieningsvereistenID" integer NOT NULL
)
;

CREATE TABLE "Kp_toepasbareRegel_locatie"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ToepasbareRegelID" integer NULL,
	"LocatieID" integer NULL
)
;

CREATE TABLE "Maatregelen"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"MaatregelenID" integer NOT NULL
)
;

CREATE TABLE "ToepasbareRegel"
(
	"Datumbegingeldigheid" date NULL,
	"Datumeindegeldigheid" date NULL,
	"Domein" varchar(50) NULL,
	"Naam" varchar(200) NULL,
	"Omschrijving" text NULL,
	"Soortaansluitpunt" varchar(200) NULL,	--  uitbreiden, uitsluiten of vervangen
	"Toestemming" varchar(200) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ToepasbareRegelID" integer NOT NULL,
	"ToepasbareregelbestandID" integer NULL,
	"ActiviteitID" integer NULL
)
;

CREATE TABLE "Toepasbareregelbestand"
(
	"Datumeindegeldigheid" date NULL,
	"Datumstart" date NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ToepasbareregelbestandID" integer NOT NULL
)
;

CREATE TABLE "Uitvoeringsregel"
(
	"Naam" varchar(200) NULL,
	"Omschrijving" text NULL,
	"Regel" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"UitvoeringsregelID" integer NOT NULL,
	"ToepasbareRegelID" integer NULL,
	"ToepasbareregelbestandID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Conclusie" ADD CONSTRAINT "PK_Conclusie"
	PRIMARY KEY ("ConclusieID")
;

ALTER TABLE "Indieningsvereisten" ADD CONSTRAINT "PK_Indieningsvereisten"
	PRIMARY KEY ("IndieningsvereistenID")
;

ALTER TABLE "Maatregelen" ADD CONSTRAINT "PK_Maatregelen"
	PRIMARY KEY ("MaatregelenID")
;

ALTER TABLE "ToepasbareRegel" ADD CONSTRAINT "PK_ToepasbareRegel"
	PRIMARY KEY ("ToepasbareRegelID")
;

ALTER TABLE "Toepasbareregelbestand" ADD CONSTRAINT "PK_Toepasbareregelbestand"
	PRIMARY KEY ("ToepasbareregelbestandID")
;

ALTER TABLE "Uitvoeringsregel" ADD CONSTRAINT "PK_Uitvoeringsregel"
	PRIMARY KEY ("UitvoeringsregelID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Conclusie" ADD CONSTRAINT "Fk_conclusie_toepasbareRegel"
	FOREIGN KEY ("ConclusieID") REFERENCES "ToepasbareRegel" ("ToepasbareRegelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Indieningsvereisten" ADD CONSTRAINT "Fk_indieningsvereisten_toepasbareRegel"
	FOREIGN KEY ("IndieningsvereistenID") REFERENCES "ToepasbareRegel" ("ToepasbareRegelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_toepasbareRegel_locatie" ADD CONSTRAINT "Fk_kp_toepasbareregel_locatie_toepasbareRegel"
	FOREIGN KEY ("ToepasbareRegelID") REFERENCES "ToepasbareRegel" ("ToepasbareRegelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_toepasbareRegel_locatie" ADD CONSTRAINT "Fk_kp_toepasbareregel_locatie_locatie"
	FOREIGN KEY ("LocatieID") REFERENCES "Locatie" ("LocatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Maatregelen" ADD CONSTRAINT "Fk_maatregelen_toepasbareRegel"
	FOREIGN KEY ("MaatregelenID") REFERENCES "ToepasbareRegel" ("ToepasbareRegelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "ToepasbareRegel" ADD CONSTRAINT "FK_ToepasbareRegel_Toepasbareregelbestand"
	FOREIGN KEY ("ToepasbareregelbestandID") REFERENCES "Toepasbareregelbestand" ("ToepasbareregelbestandID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "ToepasbareRegel" ADD CONSTRAINT "FK_ToepasbareRegel_Activiteit"
	FOREIGN KEY ("ActiviteitID") REFERENCES "Activiteit" ("ActiviteitID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Uitvoeringsregel" ADD CONSTRAINT "fk_heeft_toepasbareRegel"
	FOREIGN KEY ("ToepasbareRegelID") REFERENCES "ToepasbareRegel" ("ToepasbareRegelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Uitvoeringsregel" ADD CONSTRAINT fk_bevat_toepasbareregelbestan
	FOREIGN KEY ("ToepasbareregelbestandID") REFERENCES "Toepasbareregelbestand" ("ToepasbareregelbestandID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Conclusie"
	IS 'Conclusie van de check. Antwoord op de vraag of ik een melding moet doen of een vergunning aan moet vragen voor een bepaalde activiteit. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Conclusie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Conclusie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Conclusie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Conclusie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Conclusie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Conclusie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Conclusie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Conclusie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Indieningsvereisten"
	IS 'Dat wat de initiatiefnemer moet aanleveren om het bevoegd gezag een aanvraag te kunnen laten beoordelen. De indieningsvereisten is de set aan informatie (gegevens en / of bijlagen) die aan een aanvraag moet worden toegevoegd voor een bepaalde vergunning of melding. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Indieningsvereisten"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Indieningsvereisten"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Indieningsvereisten"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Indieningsvereisten"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Indieningsvereisten"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Indieningsvereisten"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Indieningsvereisten"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Indieningsvereisten"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_toepasbareRegel_locatie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_toepasbareRegel_locatie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_toepasbareRegel_locatie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_toepasbareRegel_locatie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_toepasbareRegel_locatie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_toepasbareRegel_locatie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_toepasbareRegel_locatie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_toepasbareRegel_locatie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Maatregelen"
	IS 'Beschrijft welke handelingen iemand moet uitvoeren om aan Voorschriften te kunnen voldoen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Maatregelen"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Maatregelen"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Maatregelen"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Maatregelen"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Maatregelen"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Maatregelen"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Maatregelen"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Maatregelen"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "ToepasbareRegel"
	IS 'Vanwege de leesbaarheid wordt gewerkt met de term Toepasbare regel ipv regelbeheersobject

Een regelbeheerobject heeft een koppeling met een samenhangende set met regels om een afleiding te kunnen doen. Het regelbeheerobject ‘conclusie gevelaanpassing’ kan een vraag beantwoorden zoals: “Heb ik een vergunning nodig voor het veranderen van een kozijn, kozijninvulling of gevelpaneel”. Het regelbeheerobject ‘melding lozing’ beantwoordt de vraag “Wat moet ik aan informatie (gegevens en documenten) aanleveren als ik ga lozen vanuit particuliere huishoudens”. Het regelbeheerobject “Opslaan van gasolie smeerolie of afgewerkte olie in een bovengrondse opslagtank” geeft aan welke maatregelen genomen dienen te worden.
Het regelbeheerobject is onderdeel van de functionele structuur. De set met regels is gedefinieerd in het Toepasbare regelbestand2.
 Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "ToepasbareRegel"."Soortaansluitpunt"
	IS ' uitbreiden, uitsluiten of vervangen'
;

COMMENT ON COLUMN "ToepasbareRegel"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "ToepasbareRegel"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "ToepasbareRegel"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "ToepasbareRegel"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "ToepasbareRegel"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "ToepasbareRegel"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "ToepasbareRegel"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "ToepasbareRegel"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Toepasbareregelbestand"
	IS 'Bestand met aangeleverde toepasbare regels Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Toepasbareregelbestand"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Toepasbareregelbestand"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Toepasbareregelbestand"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Toepasbareregelbestand"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Toepasbareregelbestand"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Toepasbareregelbestand"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Toepasbareregelbestand"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Toepasbareregelbestand"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Uitvoeringsregel"
	IS 'De uitvoeringsregels bepalen hoe de benodigde gegevens (input data) wordt uitgevraagd. Dit kan op verschillende manieren gebeuren zoals een vraag aan een initiatiefnemer of een bevraging van een registratie. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Uitvoeringsregel"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Uitvoeringsregel"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Uitvoeringsregel"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Uitvoeringsregel"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Uitvoeringsregel"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Uitvoeringsregel"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Uitvoeringsregel"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Uitvoeringsregel"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
