/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version "17".0 		*/
/*  Created On : "06"-mrt-2025 "14":05:10 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Actie" CASCADE
;

DROP TABLE IF EXISTS "Areaal" CASCADE
;

DROP TABLE IF EXISTS "Crow_melding" CASCADE
;

DROP TABLE IF EXISTS "Deelplan_veld" CASCADE
;

DROP TABLE IF EXISTS "Enum_crow_kwaliteitsniveaus" CASCADE
;

DROP TABLE IF EXISTS "Enum_energielabel" CASCADE
;

DROP TABLE IF EXISTS "Enum_oppervlakteWoning" CASCADE
;

DROP TABLE IF EXISTS "Fase_oplevering" CASCADE
;

DROP TABLE IF EXISTS "Geo_object" CASCADE
;

DROP TABLE IF EXISTS "Grondbeheerder" CASCADE
;

DROP TABLE IF EXISTS "Inspectie" CASCADE
;

DROP TABLE IF EXISTS "Kadastralemutatie" CASCADE
;

DROP TABLE IF EXISTS "Kp_areaal_buurt" CASCADE
;

DROP TABLE IF EXISTS "Kp_areaal_schouwronde" CASCADE
;

DROP TABLE IF EXISTS "Kp_areaal_wijk" CASCADE
;

DROP TABLE IF EXISTS "Kp_kadastralemutatie_kadastral" CASCADE
;

DROP TABLE IF EXISTS "Kp_rechtspersoon_kadastralemut" CASCADE
;

DROP TABLE IF EXISTS "Kp_uitvoerderGraafwerkzaamhed" CASCADE
;

DROP TABLE IF EXISTS "KwaliteitscatalogusOpenbareR" CASCADE
;

DROP TABLE IF EXISTS "Kwaliteitskenmerken" CASCADE
;

DROP TABLE IF EXISTS "Logboek" CASCADE
;

DROP TABLE IF EXISTS "Melding" CASCADE
;

DROP TABLE IF EXISTS "Meldingongeval" CASCADE
;

DROP TABLE IF EXISTS "Moor_melding" CASCADE
;

DROP TABLE IF EXISTS "Omgevingsvergunning" CASCADE
;

DROP TABLE IF EXISTS "Onderhoud" CASCADE
;

DROP TABLE IF EXISTS "Opbreking" CASCADE
;

DROP TABLE IF EXISTS "Proces_verbaal_moor_melding" CASCADE
;

DROP TABLE IF EXISTS "Schouwronde" CASCADE
;

DROP TABLE IF EXISTS "Storing" CASCADE
;

DROP TABLE IF EXISTS "Taak" CASCADE
;

DROP TABLE IF EXISTS "UitvoerderGraafwerkzaamheden" CASCADE
;

DROP TABLE IF EXISTS "Verkeerslicht" CASCADE
;

/* Create Tables */

CREATE TABLE "Actie"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ActieID" integer NOT NULL
)
;

CREATE TABLE "Areaal"
(
	"Geometrie" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AreaalID" integer NOT NULL
)
;

CREATE TABLE "Crow_melding"
(
	"Kwaliteitsniveau" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Crow-meldingID" integer NOT NULL,
	"KwaliteitscatalogusOpenbareID" integer NULL,
	"Crow_meldingID" integer NULL
)
;

CREATE TABLE "Deelplan_veld"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Deelplan/veldID" integer NOT NULL
)
;

CREATE TABLE "Enum_crow_kwaliteitsniveaus"
(
	"Niveau A+" varchar(50) NULL,
	"Niveau A" varchar(50) NULL,
	"Niveau B" varchar(50) NULL,
	"Niveau C" varchar(50) NULL,
	"Niveau D" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_energielabel"
(
	"A" varchar(50) NULL,
	"B" varchar(50) NULL,
	"C" varchar(50) NULL,
	"D" varchar(50) NULL,
	"E" varchar(50) NULL,
	"F" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_oppervlakteWoning"
(
	"kleiner dan 15 m2" varchar(50) NULL,
	"15 - 49 m2" varchar(50) NULL,
	"50 - 74 m2" varchar(50) NULL,
	"75 - 99 m2" varchar(50) NULL,
	"100 - 124 m2" varchar(50) NULL,
	"125 - 149 m2" varchar(50) NULL,
	"150 en groter" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Fase_oplevering"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Fase/opleveringID" integer NOT NULL
)
;

CREATE TABLE "Geo_object"
(
	"Datumbegingeldigheid" date NULL,
	"Datumeindegeldigheid" date NULL,
	"Geometriesoort" varchar(40) NULL,
	"Identificatie" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Geo-objectID" integer NOT NULL
)
;

CREATE TABLE "Grondbeheerder"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"GrondbeheerderID" integer NOT NULL
)
;

CREATE TABLE "Inspectie"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"InspectieID" integer NOT NULL
)
;

CREATE TABLE "Kadastralemutatie"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KadastralemutatieID" integer NOT NULL
)
;

CREATE TABLE "Kp_areaal_buurt"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AreaalID" integer NULL,
	"BuurtID" integer NULL
)
;

CREATE TABLE "Kp_areaal_schouwronde"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SchouwrondeID" integer NULL,
	"AreaalID" integer NULL
)
;

CREATE TABLE "Kp_areaal_wijk"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AreaalID" integer NULL,
	"WijkID" integer NULL
)
;

CREATE TABLE "Kp_kadastralemutatie_kadastral"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KadastralemutatieID" integer NULL,
	"KadastraleonroerendezaakID" integer NULL
)
;

CREATE TABLE "Kp_rechtspersoon_kadastralemut"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KadastralemutatieID" integer NULL,
	"RechtspersoonID" integer NULL
)
;

CREATE TABLE "Kp_uitvoerderGraafwerkzaamhed"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OpbrekingID" integer NULL,
	"UitvoerderGraafwerkzaamhedeID" integer NULL
)
;

CREATE TABLE "KwaliteitscatalogusOpenbareR"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KwaliteitscatalogusOpenbareRuimteID" integer NOT NULL
)
;

CREATE TABLE "Kwaliteitskenmerken"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KwaliteitskenmerkenID" integer NOT NULL
)
;

CREATE TABLE "Logboek"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"LogboekID" integer NOT NULL,
	"BeheerobjectID" integer NULL
)
;

CREATE TABLE "Melding"
(
	"Advies" text NULL,
	"Categorie" varchar(80) NULL,
	"Constatering" text NULL,
	"Datumadvies" timestamp without time zone NULL,
	"Datummelding" timestamp without time zone NULL,
	"Datumuitvoering" timestamp without time zone NULL,
	"Foto" varchar(50) NULL,
	"Locatie" varchar(50) NULL,
	"Opmerkingen" text NULL,
	"Status" varchar(40) NULL,
	"Uitgevoerd" boolean NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"MeldingID" integer NOT NULL,
	"LogboekID" integer NULL,
	"SchouwrondeID" integer NULL,
	"LeverancierID" integer NULL,
	"MedewerkerID" integer NULL,
	"NatuurlijkpersoonID" integer NULL
)
;

CREATE TABLE "Meldingongeval"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"MeldingongevalID" integer NOT NULL
)
;

CREATE TABLE "Moor_melding"
(
	gemeentenaam VARCHAR(80) NULL,	-- Naam van de gemeente.
	straatnaam VARCHAR(200) NULL,	-- Straatnaam.
	huisnummer INTEGER NULL,	-- Huisnummer
	huisletter VARCHAR(1) NULL,	-- Huisletter
	huisnummertoevoeging VARCHAR(4) NULL,	-- Huisnummertoevoeging
	postcode VARCHAR(6) NULL,	-- Postcode
	"BAGID" VARCHAR(80) NULL,	-- BAGID
	"Datumaanmelding" timestamp without time zone NULL,
	"Datumgoedkeuring" timestamp without time zone NULL,
	"Eindtijd" timestamp without time zone NULL,
	"Goedgekeurd" boolean NULL,
	"Herstelwerkzaamhedenvereist" boolean NULL,
	"Omschrijvingherstelwerkzaamhed" text NULL,
	"Publiceren" boolean NULL,
	"Starttijd" timestamp without time zone NULL,
	"Wegbeheerder" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Moor-meldingID" integer NOT NULL,
	"OmgevingsvergunningID" integer NULL,
	"UitvoerderGraafwerkzaamhedeID" integer NULL
)
;

CREATE TABLE "Omgevingsvergunning"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OmgevingsvergunningID" integer NOT NULL,
	"PlanID" integer NULL
)
;

CREATE TABLE "Onderhoud"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OnderhoudID" integer NOT NULL
)
;

CREATE TABLE "Opbreking"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OpbrekingID" integer NOT NULL,
	"Moor_meldingID" integer NULL
)
;

CREATE TABLE "Proces_verbaal_moor_melding"
(
	"Datum" timestamp without time zone NULL,
	"Goedkeuring" boolean NULL,
	"Opmerkingen" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Proces-verbaal-moor-meldingID" integer NOT NULL,
	"Moor_meldingID" integer NULL,
	"DocumentID" integer NULL,
	"MedewerkerID" integer NULL
)
;

CREATE TABLE "Schouwronde"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SchouwrondeID" integer NOT NULL,
	"MedewerkerID" integer NULL
)
;

CREATE TABLE "Storing"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"StoringID" integer NOT NULL
)
;

CREATE TABLE "Taak"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"TaakID" integer NOT NULL
)
;

CREATE TABLE "UitvoerderGraafwerkzaamheden"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"UitvoerderGraafwerkzaamhedenID" integer NOT NULL,
	"UitvoerderGraafwerkzaamhedeID" integer NULL
)
;

CREATE TABLE "Verkeerslicht"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" TIMESTAMP NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" TIMESTAMP NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" TIMESTAMP NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VerkeerslichtID" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Actie" ADD CONSTRAINT "PK_Actie"
	PRIMARY KEY ("ActieID")
;

ALTER TABLE "Areaal" ADD CONSTRAINT "PK_Areaal"
	PRIMARY KEY ("AreaalID")
;

ALTER TABLE "Crow_melding" ADD CONSTRAINT "PK_Crow_melding"
	PRIMARY KEY ("Crow-meldingID")
;

ALTER TABLE "Deelplan_veld" ADD CONSTRAINT "PK_Deelplan_veld"
	PRIMARY KEY ("Deelplan/veldID")
;

ALTER TABLE "Enum_crow_kwaliteitsniveaus" ADD CONSTRAINT "PK_Enum_crow_kwaliteitsniveaus"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_energielabel" ADD CONSTRAINT "PK_Enum_energielabel"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_oppervlakteWoning" ADD CONSTRAINT "PK_Enum_oppervlakteWoning"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Fase_oplevering" ADD CONSTRAINT "PK_Fase_oplevering"
	PRIMARY KEY ("Fase/opleveringID")
;

ALTER TABLE "Geo_object" ADD CONSTRAINT "PK_Geo_object"
	PRIMARY KEY ("Geo-objectID")
;

ALTER TABLE "Grondbeheerder" ADD CONSTRAINT "PK_Grondbeheerder"
	PRIMARY KEY ("GrondbeheerderID")
;

ALTER TABLE "Inspectie" ADD CONSTRAINT "PK_Inspectie"
	PRIMARY KEY ("InspectieID")
;

ALTER TABLE "Kadastralemutatie" ADD CONSTRAINT "PK_Kadastralemutatie"
	PRIMARY KEY ("KadastralemutatieID")
;

ALTER TABLE "KwaliteitscatalogusOpenbareR" ADD CONSTRAINT "PK_KwaliteitscatalogusOpenbareR"
	PRIMARY KEY ("KwaliteitscatalogusOpenbareRuimteID")
;

ALTER TABLE "Kwaliteitskenmerken" ADD CONSTRAINT "PK_Kwaliteitskenmerken"
	PRIMARY KEY ("KwaliteitskenmerkenID")
;

ALTER TABLE "Logboek" ADD CONSTRAINT "PK_Logboek"
	PRIMARY KEY ("LogboekID")
;

ALTER TABLE "Melding" ADD CONSTRAINT "PK_Melding"
	PRIMARY KEY ("MeldingID")
;

ALTER TABLE "Meldingongeval" ADD CONSTRAINT "PK_Meldingongeval"
	PRIMARY KEY ("MeldingongevalID")
;

ALTER TABLE "Moor_melding" ADD CONSTRAINT "PK_Moor_melding"
	PRIMARY KEY ("Moor-meldingID")
;

ALTER TABLE "Omgevingsvergunning" ADD CONSTRAINT "PK_Omgevingsvergunning"
	PRIMARY KEY ("OmgevingsvergunningID")
;

ALTER TABLE "Onderhoud" ADD CONSTRAINT "PK_Onderhoud"
	PRIMARY KEY ("OnderhoudID")
;

ALTER TABLE "Opbreking" ADD CONSTRAINT "PK_Opbreking"
	PRIMARY KEY ("OpbrekingID")
;

ALTER TABLE "Proces_verbaal_moor_melding" ADD CONSTRAINT "PK_Proces_verbaal_moor_melding"
	PRIMARY KEY ("Proces-verbaal-moor-meldingID")
;

ALTER TABLE "Schouwronde" ADD CONSTRAINT "PK_Schouwronde"
	PRIMARY KEY ("SchouwrondeID")
;

ALTER TABLE "Storing" ADD CONSTRAINT "PK_Storing"
	PRIMARY KEY ("StoringID")
;

ALTER TABLE "Taak" ADD CONSTRAINT "PK_Taak"
	PRIMARY KEY ("TaakID")
;

ALTER TABLE "UitvoerderGraafwerkzaamheden" ADD CONSTRAINT "PK_UitvoerderGraafwerkzaamheden"
	PRIMARY KEY ("UitvoerderGraafwerkzaamhedenID")
;

ALTER TABLE "Verkeerslicht" ADD CONSTRAINT "PK_Verkeerslicht"
	PRIMARY KEY ("VerkeerslichtID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Actie" ADD CONSTRAINT "Fk_actie_melding"
	FOREIGN KEY ("ActieID") REFERENCES "Melding" ("MeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Crow_melding" ADD CONSTRAINT "FK_Crow_melding_KwaliteitscatalogusOpenbareR"
	FOREIGN KEY ("KwaliteitscatalogusOpenbareID") REFERENCES "KwaliteitscatalogusOpenbareR" ("KwaliteitscatalogusOpenbareRuimteID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Crow_melding" ADD CONSTRAINT "Fk_crow_melding_melding"
	FOREIGN KEY ("Crow_meldingID") REFERENCES "Melding" ("MeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Grondbeheerder" ADD CONSTRAINT "Fk_grondbeheerder_rechtspersoon"
	FOREIGN KEY ("GrondbeheerderID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Inspectie" ADD CONSTRAINT "Fk_inspectie_melding"
	FOREIGN KEY ("InspectieID") REFERENCES "Melding" ("MeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_areaal_buurt" ADD CONSTRAINT "Fk_kp_areaal_buurt_areaal"
	FOREIGN KEY ("AreaalID") REFERENCES "Areaal" ("AreaalID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_areaal_buurt" ADD CONSTRAINT "Fk_kp_areaal_buurt_buurt"
	FOREIGN KEY ("BuurtID") REFERENCES "Buurt" ("BuurtID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_areaal_schouwronde" ADD CONSTRAINT "Fk_kp_areaal_schouwronde_schouwronde"
	FOREIGN KEY ("SchouwrondeID") REFERENCES "Schouwronde" ("SchouwrondeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_areaal_schouwronde" ADD CONSTRAINT "Fk_kp_areaal_schouwronde_areaal"
	FOREIGN KEY ("AreaalID") REFERENCES "Areaal" ("AreaalID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_areaal_wijk" ADD CONSTRAINT "Fk_kp_areaal_wijk_areaal"
	FOREIGN KEY ("AreaalID") REFERENCES "Areaal" ("AreaalID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_areaal_wijk" ADD CONSTRAINT "Fk_kp_areaal_wijk_wijk"
	FOREIGN KEY ("WijkID") REFERENCES "Wijk" ("WijkID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_kadastralemutatie_kadastral" ADD CONSTRAINT "Fk_kp_kadastralemutatie_kadastral_kadastralemutatie"
	FOREIGN KEY ("KadastralemutatieID") REFERENCES "Kadastralemutatie" ("KadastralemutatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_kadastralemutatie_kadastral" ADD CONSTRAINT "Fk_kp_kadastralemutatie_kadastral_kadastraleonroerendezaak"
	FOREIGN KEY ("KadastraleonroerendezaakID") REFERENCES "Kadastraleonroerendezaak" ("KadastraleonroerendezaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_rechtspersoon_kadastralemut" ADD CONSTRAINT "Fk_kp_rechtspersoon_kadastralemut_kadastralemutatie"
	FOREIGN KEY ("KadastralemutatieID") REFERENCES "Kadastralemutatie" ("KadastralemutatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_rechtspersoon_kadastralemut" ADD CONSTRAINT "Fk_kp_rechtspersoon_kadastralemut_rechtspersoon"
	FOREIGN KEY ("RechtspersoonID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_uitvoerderGraafwerkzaamhed" ADD CONSTRAINT "Fk_kp_uitvoerdergraafwerkzaamhed_opbreking"
	FOREIGN KEY ("OpbrekingID") REFERENCES "Opbreking" ("OpbrekingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_uitvoerderGraafwerkzaamhed" ADD CONSTRAINT "Fk_kp_uitvoerdergraafwerkzaamhed_uitvoerderGraafwerkzaamhede"
	FOREIGN KEY ("UitvoerderGraafwerkzaamhedeID") REFERENCES "UitvoerderGraafwerkzaamheden" ("UitvoerderGraafwerkzaamhedenID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Logboek" ADD CONSTRAINT fk_heeft_beheerobject
	FOREIGN KEY ("BeheerobjectID") REFERENCES "Beheerobject" ("BeheerobjectID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Melding" ADD CONSTRAINT fk_bevat_logboek
	FOREIGN KEY ("LogboekID") REFERENCES "Logboek" ("LogboekID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Melding" ADD CONSTRAINT fk_heeft_schouwronde
	FOREIGN KEY ("SchouwrondeID") REFERENCES "Schouwronde" ("SchouwrondeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Melding" ADD CONSTRAINT "FK_Melding_Leverancier"
	FOREIGN KEY ("LeverancierID") REFERENCES "Leverancier" ("LeverancierID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Melding" ADD CONSTRAINT "FK_Melding_Medewerker"
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Melding" ADD CONSTRAINT "FK_Melding_Natuurlijkpersoon"
	FOREIGN KEY ("NatuurlijkpersoonID") REFERENCES "Natuurlijkpersoon" ("NatuurlijkpersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Meldingongeval" ADD CONSTRAINT "Fk_meldingongeval_melding"
	FOREIGN KEY ("MeldingongevalID") REFERENCES "Melding" ("MeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Moor_melding" ADD CONSTRAINT "FK_Moor_melding_Omgevingsvergunning"
	FOREIGN KEY ("OmgevingsvergunningID") REFERENCES "Omgevingsvergunning" ("OmgevingsvergunningID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Moor_melding" ADD CONSTRAINT "fk_doet_uitvoerderGraafwerkzaa"
	FOREIGN KEY ("UitvoerderGraafwerkzaamhedeID") REFERENCES "UitvoerderGraafwerkzaamheden" ("UitvoerderGraafwerkzaamhedenID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Omgevingsvergunning" ADD CONSTRAINT "FK_Omgevingsvergunning_Plan"
	FOREIGN KEY ("PlanID") REFERENCES "Plan" ("PlanID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Opbreking" ADD CONSTRAINT fk_betreft_moor_melding
	FOREIGN KEY ("Moor_meldingID") REFERENCES "Moor_melding" ("Moor-meldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Proces_verbaal_moor_melding" ADD CONSTRAINT fk_betreft_moor_melding
	FOREIGN KEY ("Moor_meldingID") REFERENCES "Moor_melding" ("Moor-meldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Proces_verbaal_moor_melding" ADD CONSTRAINT "FK_Proces_verbaal_moor_melding_Document"
	FOREIGN KEY ("DocumentID") REFERENCES "Document" ("DocumentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Proces_verbaal_moor_melding" ADD CONSTRAINT fk_verleent_medewerker
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Schouwronde" ADD CONSTRAINT "fk_voertUit_medewerker"
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Storing" ADD CONSTRAINT "Fk_storing_melding"
	FOREIGN KEY ("StoringID") REFERENCES "Melding" ("MeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "UitvoerderGraafwerkzaamheden" ADD CONSTRAINT "Fk_uitvoerderGraafwerkzaamhede_grondbeheerder"
	FOREIGN KEY ("UitvoerderGraafwerkzaamhedeID") REFERENCES "Grondbeheerder" ("GrondbeheerderID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "UitvoerderGraafwerkzaamheden" ADD CONSTRAINT "Fk_uitvoerderGraafwerkzaamhede_leverancier"
	FOREIGN KEY ("UitvoerderGraafwerkzaamhedeID") REFERENCES "Leverancier" ("LeverancierID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Actie"
	IS 'Kleinst mogelijke eenheid van werk die zinvol onderscheiden kan worden, uitgevoerd door een persoon of machine op 1 plek op 1 moment. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Actie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Actie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Actie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Actie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Actie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Actie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Actie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Actie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Areaal"
	IS 'Het verspreidingsgebied van een een soort, een levensgemeenschap of een biotooptype. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Areaal"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Areaal"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Areaal"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Areaal"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Areaal"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Areaal"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Areaal"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Areaal"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Crow_melding"
	IS 'BOR-MELD is een CROW-standaard voor het vastleggen van meldingen.  Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Crow_melding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Crow_melding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Crow_melding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Crow_melding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Crow_melding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Crow_melding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Crow_melding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Crow_melding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Deelplan_veld"
	IS 'Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Deelplan_veld"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Deelplan_veld"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Deelplan_veld"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Deelplan_veld"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Deelplan_veld"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Deelplan_veld"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Deelplan_veld"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Deelplan_veld"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Fase_oplevering"
	IS 'Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Fase_oplevering"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Fase_oplevering"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Fase_oplevering"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Fase_oplevering"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Fase_oplevering"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Fase_oplevering"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Fase_oplevering"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Fase_oplevering"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Geo_object"
	IS 'Abstractie van een fenomeen in de werkelijkheid, dat direct of indirect is geassocieerd met een locatie relatief ten opzichte van de aarde. [NEN "3610":2011] Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Geo_object"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Geo_object"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Geo_object"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Geo_object"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Geo_object"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Geo_object"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Geo_object"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Geo_object"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Grondbeheerder"
	IS 'Beheerder van grondgrondbeheer., oplossing voor duurzaam landbeheer en voedselproductie Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Grondbeheerder"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Grondbeheerder"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Grondbeheerder"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Grondbeheerder"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Grondbeheerder"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Grondbeheerder"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Grondbeheerder"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Grondbeheerder"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Inspectie"
	IS 'het inwinnen, verwerken en interpreteren van informatie met het doel om de momentane toestand van de boezemkade vast te stellen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Inspectie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Inspectie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Inspectie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Inspectie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Inspectie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Inspectie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Inspectie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Inspectie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Kadastralemutatie"
	IS 'Wijziging in de kadatrale registratie Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Kadastralemutatie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kadastralemutatie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kadastralemutatie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kadastralemutatie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kadastralemutatie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kadastralemutatie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kadastralemutatie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kadastralemutatie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_areaal_buurt"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_areaal_buurt"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_areaal_buurt"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_areaal_buurt"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_areaal_buurt"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_areaal_buurt"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_areaal_buurt"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_areaal_buurt"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_areaal_schouwronde"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_areaal_schouwronde"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_areaal_schouwronde"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_areaal_schouwronde"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_areaal_schouwronde"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_areaal_schouwronde"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_areaal_schouwronde"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_areaal_schouwronde"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_areaal_wijk"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_areaal_wijk"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_areaal_wijk"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_areaal_wijk"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_areaal_wijk"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_areaal_wijk"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_areaal_wijk"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_areaal_wijk"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_kadastralemutatie_kadastral"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_kadastralemutatie_kadastral"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_kadastralemutatie_kadastral"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_kadastralemutatie_kadastral"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_kadastralemutatie_kadastral"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_kadastralemutatie_kadastral"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_kadastralemutatie_kadastral"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_kadastralemutatie_kadastral"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_rechtspersoon_kadastralemut"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_rechtspersoon_kadastralemut"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_rechtspersoon_kadastralemut"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_rechtspersoon_kadastralemut"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_rechtspersoon_kadastralemut"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_rechtspersoon_kadastralemut"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_rechtspersoon_kadastralemut"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_rechtspersoon_kadastralemut"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_uitvoerderGraafwerkzaamhed"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_uitvoerderGraafwerkzaamhed"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_uitvoerderGraafwerkzaamhed"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_uitvoerderGraafwerkzaamhed"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_uitvoerderGraafwerkzaamhed"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_uitvoerderGraafwerkzaamhed"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_uitvoerderGraafwerkzaamhed"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_uitvoerderGraafwerkzaamhed"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "KwaliteitscatalogusOpenbareR"
	IS 'zie https://www.crow.nl/publicaties/kwaliteitscatalogus-openbare-ruimte-2018
 Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "KwaliteitscatalogusOpenbareR"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "KwaliteitscatalogusOpenbareR"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "KwaliteitscatalogusOpenbareR"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "KwaliteitscatalogusOpenbareR"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "KwaliteitscatalogusOpenbareR"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "KwaliteitscatalogusOpenbareR"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "KwaliteitscatalogusOpenbareR"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "KwaliteitscatalogusOpenbareR"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Kwaliteitskenmerken"
	IS 'Aanduiding van de hoedanigheid van uitvoering, bewerking en representativiteit van een meting, volgens een overeengekomen waarderingsschaal. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Kwaliteitskenmerken"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kwaliteitskenmerken"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kwaliteitskenmerken"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kwaliteitskenmerken"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kwaliteitskenmerken"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kwaliteitskenmerken"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kwaliteitskenmerken"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kwaliteitskenmerken"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Logboek"
	IS 'Registratie waarin gebeurtenissen worden bijgehouden. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Logboek"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Logboek"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Logboek"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Logboek"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Logboek"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Logboek"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Logboek"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Logboek"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Melding"
	IS 'De betekenisvolle formulering van een waargenomen feit, waaraan een waarde kan worden toegekend Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Melding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Melding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Melding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Melding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Melding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Melding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Melding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Melding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Meldingongeval"
	IS 'Aangifte vna een ongeval Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Meldingongeval"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Meldingongeval"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Meldingongeval"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Meldingongeval"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Meldingongeval"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Meldingongeval"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Meldingongeval"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Meldingongeval"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Moor_melding"
	IS 'Meldingsproces rondom werkzaamheden aan kabels en leidingen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Moor_melding".gemeentenaam
	IS 'Naam van de gemeente.'
;

COMMENT ON COLUMN "Moor_melding".straatnaam
	IS 'Straatnaam.'
;

COMMENT ON COLUMN "Moor_melding".huisnummer
	IS 'Huisnummer'
;

COMMENT ON COLUMN "Moor_melding".huisletter
	IS 'Huisletter'
;

COMMENT ON COLUMN "Moor_melding".huisnummertoevoeging
	IS 'Huisnummertoevoeging'
;

COMMENT ON COLUMN "Moor_melding".postcode
	IS 'Postcode'
;

COMMENT ON COLUMN "Moor_melding"."BAGID"
	IS 'BAGID'
;

COMMENT ON COLUMN "Moor_melding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Moor_melding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Moor_melding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Moor_melding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Moor_melding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Moor_melding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Moor_melding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Moor_melding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Omgevingsvergunning"
	IS 'Vergunning als bedoeld in afdeling 5.1 van de Omgevingswet Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Omgevingsvergunning"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Omgevingsvergunning"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Omgevingsvergunning"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Omgevingsvergunning"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Omgevingsvergunning"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Omgevingsvergunning"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Omgevingsvergunning"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Omgevingsvergunning"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Onderhoud"
	IS 'Maatregelen om de functionele kwaliteit in stand te houden of te herstellen en dus de levensduur van een (object)onderdeel te realiseren c.q. te verlengen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Onderhoud"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Onderhoud"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Onderhoud"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Onderhoud"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Onderhoud"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Onderhoud"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Onderhoud"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Onderhoud"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Opbreking"
	IS 'Vorm van wegwerkzaamheid  Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Opbreking"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Opbreking"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Opbreking"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Opbreking"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Opbreking"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Opbreking"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Opbreking"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Opbreking"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Proces_verbaal_moor_melding"
	IS 'Officieel op papier gesteld verslag met betrekking tot heen MOOR-melding Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Proces_verbaal_moor_melding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Proces_verbaal_moor_melding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Proces_verbaal_moor_melding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Proces_verbaal_moor_melding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Proces_verbaal_moor_melding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Proces_verbaal_moor_melding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Proces_verbaal_moor_melding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Proces_verbaal_moor_melding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Schouwronde"
	IS 'Activiteit om te controleren of de opdrachtnemer aan de afspraken voldoet. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Schouwronde"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Schouwronde"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Schouwronde"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Schouwronde"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Schouwronde"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Schouwronde"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Schouwronde"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Schouwronde"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Storing"
	IS 'Verlies van de mogelijkheid om volgens een specificatie te werken of om het vereiste resultaat te leveren. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Storing"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Storing"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Storing"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Storing"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Storing"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Storing"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Storing"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Storing"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Taak"
	IS 'Een samenhangende set activiteiten. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Taak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Taak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Taak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Taak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Taak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Taak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Taak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Taak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "UitvoerderGraafwerkzaamheden"
	IS 'Degene die op de bouwlocatie van een project de leiding heeft met betrekking tot de graafwerkzaamheden Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "UitvoerderGraafwerkzaamheden"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "UitvoerderGraafwerkzaamheden"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "UitvoerderGraafwerkzaamheden"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "UitvoerderGraafwerkzaamheden"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "UitvoerderGraafwerkzaamheden"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "UitvoerderGraafwerkzaamheden"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "UitvoerderGraafwerkzaamheden"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "UitvoerderGraafwerkzaamheden"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Verkeerslicht"
	IS 'Lichten die aangeven dat je moet stoppen, dat je mag doorrijden, of die je waarschuwen voor gevaar.  Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Verkeerslicht"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Verkeerslicht"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Verkeerslicht"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Verkeerslicht"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Verkeerslicht"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Verkeerslicht"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Verkeerslicht"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Verkeerslicht"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
