SELECT
    WVIND_B.DD_EIND AS Datumeinde,
    WVIND_B.DD_BEGIN AS Datumstart,
    WVIND_B.EENHEID AS Eenheid,
    WVIND_B.CODE_FREQUENTIE AS Frequentie,
    WVIND_B.VOLUME AS Omvang,
    WVIND_B.STATUS_INDICATIE AS Status,
    SZREGEL.OMSCHRYVING AS Wet,
    CONCAT(WVIND_B.BESLUITNR, WVIND_B.VOLGNR_IND) AS BeschikteVoorzieningID,
    WVBESL.BESLUITNR AS BeschikkingID,
    ABC_REFCOD.OMSCHRIJVING AS Redeneinde
FROM
    WVIND_B
LEFT JOIN
    SZREGEL ON WVIND_B.KODE_REGELING = SZREGEL.KODE_REGELING
LEFT JOIN
    WVBESL ON WVIND_B.BESLUITNR = WVBESL.BESLUITNR
LEFT JOIN
    WVDOS ON WVIND_B.BESLUITNR = WVDOS.BESLUITNR
           AND WVIND_B.VOLGNR_IND = WVDOS.VOLGNR_IND
LEFT JOIN
    ABC_REFCOD ON
        WVDOS.KODE_REDEN_EINDE_VOORZ = ABC_REFCOD.CODE
        AND (
            (SZREGEL.OMSCHRYVING = 'JEUGDWET' AND ABC_REFCOD.DOMEIN = 'JZG_REDEN_EINDE_PRODUCT')
            OR
            (SZREGEL.OMSCHRYVING <> 'JEUGDWET' AND ABC_REFCOD.DOMEIN = 'WVRTEIND')
        );
