-- Selectie van tabellen uit GGM, naar mapping Key2Burgerzaken BRP van Maarten-Jan-Kampen (Delft)

-- NATUURLIJKPERSOON; INGESCHREVENPERSOON;  
-- -> komen uit originele GGM DDL

-- ENUM_GEZINSRELATIE; VERBLIJFSADRESINGESCHREVENNATUURLIJKPERSOON; HUWELIJK 
-- -> is extra, komt niet voor in GGM DDL

-- Maarten-Jan-Kampen definieert ook 'PRE_HUWELIJK' (is CTE in query richting 'HUWELIJK'),
-- deze nemen we hier niet op als eigen tabel.

-- Uit: ggm/ddl (early release)/99_Kern/Generiek/Relatie_BRP_en_BAG_mssql.sql
CREATE TABLE [NATUURLIJKPERSOON] (
    [RECHTSPERSOON_ID] INT PRIMARY KEY,
    [AANDUIDINGBIJZONDERNEDERLANDERSCHAPPERSOON] VARCHAR(50),
    [AANDUIDINGNAAMGEBRUIK] VARCHAR(50),
    [AANHEFAANSCHRIJVING] VARCHAR(50),
    [ACADEMISCHETITEL] VARCHAR(80),
    [ACHTERNAAM] VARCHAR(100),
    [ADELLIJKETITELOFPREDIKAAT] VARCHAR(255),
    [ANUMMER] VARCHAR(20),
    [ATTRIBUTE] VARCHAR(255),
    [BURGERSERVICENUMMER] VARCHAR(255),
    [DATUMGEBOORTE] DATE,
    [DATUMOVERLIJDEN] DATE,
    [GEBOORTELAND] VARCHAR(255),
    [GEBOORTEPLAATS] VARCHAR(200),
    [GESLACHTSAANDUIDING] VARCHAR(255),
    [GESLACHTSNAAM] VARCHAR(200),
    [GESLACHTSNAAMAANSCHRIJVING] VARCHAR(200),
    [HANDLICHTING] VARCHAR(50),
    [INDICATIEAFSCHERMINGPERSOONSGEGEVENS] BIT,
    [INDICATIEOVERLEDEN] BIT,
    [LANDOVERLIJDEN] VARCHAR(255),
    [NATIONALITEIT] VARCHAR(100),
    [OVERLIJDENSPLAATS] VARCHAR(200),
    [VOORLETTERSAANSCHRIJVING] VARCHAR(20),
    [VOORNAMEN] VARCHAR(200),
    [VOORNAMENAANSCHRIJVING] VARCHAR(200),
    [VOORVOEGSELGESLACHTSNAAM] VARCHAR(80)
);

-- Uit: ggm/ddl (early release)/0_Bestuur__Politiek_en_Ondersteuning/Burgerzaken/Burgerzaken_mssql.sql
CREATE TABLE [INGESCHREVENPERSOON] (
    [INGESCHREVENPERSOON_ID] INT PRIMARY KEY,
    [ADRESHERKOMST] VARCHAR(255),
    [ANUMMER] VARCHAR(20),
    [BESCHRIJVINGLOCATIE] VARCHAR(200),
    [BUITENLANDSREISDOCUMENT] VARCHAR(80),
    [BURGERLIJKESTAAT] VARCHAR(255),
    [DATUMBEGINGELDIGHEIDVERBLIJFPLAATS] DATE,
    [DATUMEINDEGELDIGHEIDVERBLIJFSPLAATS] DATE,
    [DATUMINSCHRIJVINGGEMEENTE] DATE,
    [DATUMOPSCHORTINGBIJHOUDING] DATE,
    [DATUMVERTREKUITNEDERLAND] DATE,
    [DATUMVESTIGINGNEDERLAND] DATE,
    [GEMEENTEVANINSCHRIJVING] VARCHAR(80),
    [GEZINSRELATIE] VARCHAR(255),
    [INDICATIEGEHEIM] BIT,
    [INGEZETENE] BIT,
    [IS_VERSTREKT_AAN_REISDOCUMENT_ID] INT,
    [LANDWAARNAARVERTROKKEN] VARCHAR(255),
    [LANDWAARVANDAANINGESCHREVEN] VARCHAR(255),
    [OUDER1] VARCHAR(255),
    [OUDER2] VARCHAR(255),
    [OUDER_1_INGESCHREVENPERSOON_ID] INT,
    [OUDER_2_INGESCHREVENPERSOON_ID] INT,
    [PARTNERID] VARCHAR(255),
    [REDENEINDEBEWONING] DATE,
    [REDENOPSCHORTINGBIJHOUDING] VARCHAR(200),
    [SIGNALERINGREISDOCUMENT] BIT,
    [VERBLIJFSTITEL] VARCHAR(255)
);

-- Extra: enum voor gezinsrelatie
CREATE TABLE [ENUM_GEZINSRELATIE] (
    [ID] INT PRIMARY KEY,
    [WAARDE] VARCHAR(255)
);

-- Extra: verblijfsadres (deze relateert aan ADRESSEERBAAROBJECT in BAG ('woont in'))
CREATE TABLE [VERBLIJFSADRESINGESCHREVENNATUURLIJKPERSOON] (
    [adresHerkomst] VARCHAR(255),
    [beschrijvingLocatie] VARCHAR(200),
    [Huisnummer] INT,
    [Huisletter] VARCHAR(10),
    [Huisnummertoevoeging] VARCHAR(10),
    [HuisnummerAanduiding] VARCHAR(50),
    [postcode] VARCHAR(20),
    [straatnaam] VARCHAR(255),
    [plaats] VARCHAR(255),
    [datumBegin] DATE,
    [datumEinde] DATE,
    [RedenEindeBewoning] VARCHAR(200),
    [IngeschrevenpersoonId] INT,
    [BAGID_nummeraanduidingId] INT,
    [BAGID_adresseerbaarobject] VARCHAR(255),
    [VerblijfsAdresIngeschrevenpersoonId] INT,
    [DWH_IDENTIFICATIE] VARCHAR(255) NOT NULL
);

-- Extra: huwelijk
CREATE TABLE [HUWELIJK] (
    [volgnummerverbintenis] INT,
    [datumverbintenis] DATE,
    [datumontbinding] DATE,
    [aktenummer] VARCHAR(255),
    [redenontbinding] VARCHAR(255),
    [soortverbintenis] VARCHAR(255),
    [datumgeldigvanaf] DATE,
    [datumopname] DATE,
    [ingeschrevenpersoonid_partner] VARCHAR(255),
    [ingeschrevenpersoonid] VARCHAR(255),
    [huwelijkid] VARCHAR(255),
    [dwh_identificatie] VARCHAR(255)
);
