/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 06-mrt-2025 13:30:18 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Activiteit" CASCADE
;

DROP TABLE IF EXISTS "Aomstatus" CASCADE
;

DROP TABLE IF EXISTS "Bevinding" CASCADE
;

DROP TABLE IF EXISTS "Boa" CASCADE
;

DROP TABLE IF EXISTS "Combibon" CASCADE
;

DROP TABLE IF EXISTS "Enum_beoordelingsoort" CASCADE
;

DROP TABLE IF EXISTS "Enum_heffingsoort" CASCADE
;

DROP TABLE IF EXISTS "Enum_statusopenbareactiviteit" CASCADE
;

DROP TABLE IF EXISTS "Fietsregistratie" CASCADE
;

DROP TABLE IF EXISTS "Grondslag" CASCADE
;

DROP TABLE IF EXISTS "Heffinggrondslag" CASCADE
;

DROP TABLE IF EXISTS "Heffingsverordening" CASCADE
;

DROP TABLE IF EXISTS "Indiener" CASCADE
;

DROP TABLE IF EXISTS "Inspectie" CASCADE
;

DROP TABLE IF EXISTS "Kosten" CASCADE
;

DROP TABLE IF EXISTS "Kp_activiteit_vthzaak" CASCADE
;

DROP TABLE IF EXISTS "Kp_bevinding_inspectie" CASCADE
;

DROP TABLE IF EXISTS "Kp_grondslag_zaak" CASCADE
;

DROP TABLE IF EXISTS "Kp_inspectie_vthzaak" CASCADE
;

DROP TABLE IF EXISTS "Kp_kosten_vthzaak" CASCADE
;

DROP TABLE IF EXISTS "Kp_leges_grondslag_vthzaak" CASCADE
;

DROP TABLE IF EXISTS "Kp_subproducttype_vthzaak" CASCADE
;

DROP TABLE IF EXISTS "Kp_vordering_vorderingregel" CASCADE
;

DROP TABLE IF EXISTS "Kp_vordering_vthzaak" CASCADE
;

DROP TABLE IF EXISTS "Kp_vth_melding_object" CASCADE
;

DROP TABLE IF EXISTS "Leges_grondslag" CASCADE
;

DROP TABLE IF EXISTS "Ligplaatsontheffing" CASCADE
;

DROP TABLE IF EXISTS "Moraanvraagofmelding" CASCADE
;

DROP TABLE IF EXISTS "Openbareactiviteit" CASCADE
;

DROP TABLE IF EXISTS "Precario" CASCADE
;

DROP TABLE IF EXISTS "Producttype" CASCADE
;

DROP TABLE IF EXISTS "Subproducttype" CASCADE
;

DROP TABLE IF EXISTS "Vaartuig" CASCADE
;

DROP TABLE IF EXISTS "Vomaanvraagofmelding" CASCADE
;

DROP TABLE IF EXISTS "Vordering" CASCADE
;

DROP TABLE IF EXISTS "Vorderingregel" CASCADE
;

DROP TABLE IF EXISTS "Vth_aanvraagofmelding" CASCADE
;

DROP TABLE IF EXISTS "Vth_melding" CASCADE
;

DROP TABLE IF EXISTS "Vthzaak" CASCADE
;

DROP TABLE IF EXISTS "Waarneming" CASCADE
;

DROP TABLE IF EXISTS "Waboaanvraagofmelding" CASCADE
;

DROP TABLE IF EXISTS "Woonfraudeaanvraagofmelding" CASCADE
;

DROP TABLE IF EXISTS "Woonoverlastaanvraagofmelding" CASCADE
;

/* Create Tables */

CREATE TABLE "Activiteit"
(
	"Omschrijving" varchar(200) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ActiviteitID" integer NOT NULL
)
;

CREATE TABLE "Aomstatus"
(
	"Datumbeginstatus" date NULL,
	"Datumeindestatus" date NULL,
	"Status" varchar(80) NULL,
	"Statuscode" varchar(80) NULL,
	"Statusvolgorde" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AomstatusID" integer NOT NULL,
	"AanvraagofmeldingID" integer NOT NULL
)
;

CREATE TABLE "Bevinding"
(
	"Aangemaaktdoor" varchar(40) NULL,
	"Activiteit" varchar(50) NULL,
	"Controleelement" varchar(50) NULL,
	"Controleniveau" varchar(50) NULL,
	"Datumaanmaak" date NULL,
	"Datummutatie" date NULL,
	"Diepte" varchar(20) NULL,
	"Fase" varchar(20) NULL,
	"Gemuteerddoor" varchar(40) NULL,
	"Resultaat" varchar(50) NULL,
	"Risico" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"BevindingID" integer NOT NULL
)
;

CREATE TABLE "Boa"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"BoaID" integer NOT NULL
)
;

CREATE TABLE "Combibon"
(
	"Sanctie" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"CombibonID" integer NOT NULL
)
;

CREATE TABLE "Enum_beoordelingsoort"
(
	"Niet Relevant" varchar(50) NULL,
	"Oke" varchar(50) NULL,
	"Niet Oke" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_heffingsoort"
(
	leges varchar(50) NULL,
	precario varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_statusopenbareactiviteit"
(
	"Aangemeld" varchar(50) NULL,
	"Aangevraagd" varchar(50) NULL,
	"Verleend" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Fietsregistratie"
(
	"Gelabeld" boolean NULL,
	"Verwijderd" boolean NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"FietsregistratieID" integer NOT NULL
)
;

CREATE TABLE "Grondslag"
(
	"Code" varchar(10) NULL,
	"Omschrijving" varchar(200) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"GrondslagID" integer NOT NULL
)
;

CREATE TABLE "Heffinggrondslag"
(
	"Bedrag" double precision NULL,
	"Domein" varchar(80) NULL,
	"Hoofdstuk" integer NULL,
	"Omschrijving" varchar(250) NULL,
	"Paragraaf" varchar(8) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"HeffinggrondslagID" integer NOT NULL,
	"HeffingsverordeningID" integer NULL,
	"ZaaktypeID" integer NULL
)
;

CREATE TABLE "Heffingsverordening"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"HeffingsverordeningID" integer NOT NULL
)
;

CREATE TABLE "Indiener"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"IndienerID" integer NOT NULL
)
;

CREATE TABLE "Inspectie"
(
	"Aangemaaktdoor" varchar(50) NULL,
	"Datumaanmaak" date NULL,
	"Datumgepland" date NULL,
	"Datuminspectie" date NULL,
	"Datummutatie" date NULL,
	"Gemuteerddoor" varchar(50) NULL,
	"Inspectietype" varchar(50) NULL,
	"Kenmerk" varchar(20) NULL,
	"Omschrijving" varchar(80) NULL,
	"Opmerkingen" varchar(80) NULL,
	"Status" varchar(20) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"InspectieID" integer NOT NULL
)
;

CREATE TABLE "Kosten"
(
	"Aangemaaktdoor" varchar(50) NULL,
	"Aantal" varchar(20) NULL,
	"Bedrag" double precision NULL,
	"Bedragtotaal" double precision NULL,
	"Datumaanmaak" date NULL,
	"Datummutatie" date NULL,
	"Eenheid" varchar(20) NULL,
	"Geaccordeerd" varchar(20) NULL,
	"Gefactureerdop" date NULL,
	"Gemuteerddoor" varchar(50) NULL,
	"Naam" varchar(20) NULL,
	"Omschrijving" text NULL,
	"Opbasisvangrondslag" varchar(50) NULL,
	"Tarief" double precision NULL,
	"Type" varchar(50) NULL,
	"Vastgesteldbedrag" double precision NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"KostenID" integer NOT NULL
)
;

CREATE TABLE "Kp_activiteit_vthzaak"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VthzaakID" integer NULL,
	"ActiviteitID" integer NULL
)
;

CREATE TABLE "Kp_bevinding_inspectie"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"InspectieID" integer NULL,
	"BevindingID" integer NULL
)
;

CREATE TABLE "Kp_grondslag_zaak"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"GrondslagID" integer NULL,
	"ZaakID" integer NULL
)
;

CREATE TABLE "Kp_inspectie_vthzaak"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VthzaakID" integer NULL,
	"InspectieID" integer NULL
)
;

CREATE TABLE "Kp_kosten_vthzaak"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VthzaakID" integer NULL,
	"KostenID" integer NULL
)
;

CREATE TABLE "Kp_leges_grondslag_vthzaak"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VthzaakID" integer NULL,
	"Leges_grondslagID" integer NULL
)
;

CREATE TABLE "Kp_subproducttype_vthzaak"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VthzaakID" integer NULL,
	"SubproducttypeID" integer NULL
)
;

CREATE TABLE "Kp_vordering_vorderingregel"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VorderingregelID" integer NULL,
	"VorderingID" integer NULL
)
;

CREATE TABLE "Kp_vordering_vthzaak"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VthzaakID" integer NULL,
	"VorderingID" integer NULL
)
;

CREATE TABLE "Kp_vth_melding_object"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Vth_meldingID" integer NULL,
	"ObjectID" integer NULL
)
;

CREATE TABLE "Leges_grondslag"
(
	"Aangemaaktdoor" varchar(50) NULL,
	"Aantalopgegeven" varchar(20) NULL,
	"Aantalvastgesteld" varchar(20) NULL,
	"Automatisch" varchar(20) NULL,
	"Datumaanmaak" date NULL,
	"Datummutatie" date NULL,
	"Eenheid" varchar(20) NULL,
	"Gemuteerddoor" varchar(50) NULL,
	"Legesgrondslag" varchar(50) NULL,
	"Omschrijving" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Leges_grondslagID" integer NOT NULL,
	"ActiviteitID" integer NOT NULL,
	"GrondslagID" integer NOT NULL
)
;

CREATE TABLE "Ligplaatsontheffing"
(
	"Stickernummer" integer NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"LigplaatsontheffingID" integer NOT NULL
)
;

CREATE TABLE "Moraanvraagofmelding"
(
	"Crow" varchar(50) NULL,
	"Locatie_lat" double precision NULL,
	"Locatie_long" double precision NULL,
	"Locatie_rdx" double precision NULL,
	"Locatie_rdy" double precision NULL,
	"Locatieomschrijving" varchar(300) NULL,
	"Meldingomschrijving" varchar(40) NULL,
	"Meldingtekst" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"MoraanvraagofmeldingID" integer NOT NULL
)
;

CREATE TABLE "Openbareactiviteit"
(
	"Datumeinde" date NULL,
	"Datumstart" date NULL,
	"Evenmentnaam" varchar(250) NULL,
	"Locatieomschrijving" varchar(250) NULL,
	"Status" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OpenbareactiviteitID" integer NOT NULL
)
;

CREATE TABLE "Precario"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"PrecarioID" integer NOT NULL
)
;

CREATE TABLE "Producttype"
(
	"Omschrijving" varchar(200) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ProducttypeID" integer NOT NULL,
	"BedrijfsprocestypeID" integer NOT NULL,
	"ZaakID" integer NOT NULL,
	"ZaaktypeID" integer NOT NULL
)
;

CREATE TABLE "Subproducttype"
(
	"Omschrijving" varchar(200) NULL,
	"Prioriteit" varchar(2) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SubproducttypeID" integer NOT NULL,
	"ProducttypeID" integer NULL
)
;

CREATE TABLE "Vaartuig"
(
	"Breedte" integer NULL,
	"Hoogte" integer NULL,
	"Kleur" varchar(20) NULL,
	"Lengte" integer NULL,
	"Naamvaartuig" varchar(250) NULL,
	"Registratienummer" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VaartuigID" integer NOT NULL,
	"ObjectID" integer NULL
)
;

CREATE TABLE "Vomaanvraagofmelding"
(
	"Activiteiten" varchar(500) NULL,
	"Adres" varchar(500) NULL,
	"Bagid" varchar(50) NULL,
	"Dossiernummer" varchar(200) NULL,
	"Intaketype" varchar(80) NULL,
	"Internnummer" varchar(80) NULL,
	"Kadastraleaanduiding" varchar(30) NULL,
	"Kenmerk" varchar(80) NULL,
	"Locatie_lat" double precision NULL,
	"Locatie_long" double precision NULL,
	"Locatie_rdx" double precision NULL,
	"Locatie_rdy" double precision NULL,
	"Locatieomschrijving" varchar(300) NULL,
	"Toelichting" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VomaanvraagofmeldingID" integer NOT NULL
)
;

CREATE TABLE "Vordering"
(
	"Aangemaaktdoor" varchar(50) NULL,
	"Bedragbtw" double precision NULL,
	"Datumaanmaak" date NULL,
	"Datummutatie" date NULL,
	"Geaccordeerd" varchar(50) NULL,
	"Geaccordeerddoor" varchar(50) NULL,
	"Geaccordeerdop" date NULL,
	"Geexporteerd" varchar(50) NULL,
	"Gemuteerddoor" varchar(50) NULL,
	"Omschrijving" text NULL,
	"Totaalbedrag" double precision NULL,
	"Totaalbedraginclusief" double precision NULL,
	"Vorderingnummer" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VorderingID" integer NOT NULL
)
;

CREATE TABLE "Vorderingregel"
(
	"Aangemaakt_door" varchar(50) NULL,
	"Aanmaakdatum" date NULL,
	"Bedrag_excl_btw" double precision NULL,
	"Bedrag_incl_btw" double precision NULL,
	"Btwcategorie" varchar(50) NULL,
	"Gemuteerd_door" varchar(50) NULL,
	"Mutatiedatum" date NULL,
	"Omschrijving" varchar(50) NULL,
	"Periodiek" varchar(50) NULL,
	"Type" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VorderingregelID" integer NOT NULL,
	"KostenID" integer NULL
)
;

CREATE TABLE "Vth_aanvraagofmelding"
(
	"Omschrijving" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Vth-aanvraagofmeldingID" integer NOT NULL,
	"Vth_aanvraagofmeldingID" integer NULL
)
;

CREATE TABLE "Vth_melding"
(
	"Activiteit" varchar(80) NULL,
	"Beoordeling" varchar(50) NULL,
	"Datumseponering" date NULL,
	"Datumtijdtot" timestamp without time zone NULL,
	"Geseponeerd" boolean NULL,
	"Locatie_lat" double precision NULL,
	"Locatie_long" double precision NULL,
	"Locatie_rdx" double precision NULL,
	"Locatie_rdy" double precision NULL,
	"Organisatieonderdeel" varchar(80) NULL,
	"Overtredingscode" varchar(20) NULL,
	"Overtredingsgroep" varchar(200) NULL,
	"Referentienummer" varchar(80) NULL,
	"Resultaat" varchar(80) NULL,
	"Soortvthmelding" varchar(80) NULL,
	"Status" varchar(40) NULL,
	"Straatnaam" varchar(250) NULL,
	"Taaktype" varchar(80) NULL,
	"Zaaknummer" varchar(20) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Vth-meldingID" integer NOT NULL,
	"BoaID" integer NULL,
	"Vth_meldingID" integer NULL
)
;

CREATE TABLE "Vthzaak"
(
	"Behandelaar" varchar(20) NULL,
	"Bevoegdgezag" varchar(50) NULL,
	"Prioritering" integer NULL,
	"Teambehandelaar" varchar(20) NULL,
	"Uitvoerendeinstantie" varchar(50) NULL,
	"Verkamering" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VthzaakID" integer NOT NULL,
	"ProducttypeID" integer NOT NULL
)
;

CREATE TABLE "Waarneming"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"WaarnemingID" integer NOT NULL
)
;

CREATE TABLE "Waboaanvraagofmelding"
(
	"Bouwkosten" double precision NULL,
	"Olonummer" varchar(80) NULL,
	"Omschrijving" text NULL,
	"Projectkosten" double precision NULL,
	"Registratienummer" varchar(100) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"WaboaanvraagofmeldingID" integer NOT NULL
)
;

CREATE TABLE "Woonfraudeaanvraagofmelding"
(
	gemeentenaam VARCHAR(80) NULL,	-- Naam van de gemeente.
	straatnaam VARCHAR(200) NULL,	-- Straatnaam.
	huisnummer INTEGER NULL,	-- Huisnummer
	huisletter VARCHAR(1) NULL,	-- Huisletter
	huisnummertoevoeging VARCHAR(4) NULL,	-- Huisnummertoevoeging
	postcode VARCHAR(6) NULL,	-- Postcode
	"BAGID" VARCHAR(80) NULL,	-- BAGID
	"Categorie" varchar(80) NULL,
	"Locatieomschrijving" varchar(300) NULL,
	"Meldingomschrijving" varchar(40) NULL,
	"Meldingtekst" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"WoonfraudeaanvraagofmeldingID" integer NOT NULL
)
;

CREATE TABLE "Woonoverlastaanvraagofmelding"
(
	"Locatie_lat" double precision NULL,
	"Locatie_long" double precision NULL,
	"Locatie_rdx" double precision NULL,
	"Locatie_rdy" double precision NULL,
	"Locatieomschrijving" varchar(300) NULL,
	"Meldingomschrijving" varchar(40) NULL,
	"Meldingtekst" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"WoonoverlastaanvraagofmeldingID" integer NOT NULL,
	"WoonoverlastaanvraagofmeldinID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Activiteit" ADD CONSTRAINT "PK_Activiteit"
	PRIMARY KEY ("ActiviteitID")
;

ALTER TABLE "Aomstatus" ADD CONSTRAINT "PK_Aomstatus"
	PRIMARY KEY ("AomstatusID")
;

ALTER TABLE "Bevinding" ADD CONSTRAINT "PK_Bevinding"
	PRIMARY KEY ("BevindingID")
;

ALTER TABLE "Boa" ADD CONSTRAINT "PK_Boa"
	PRIMARY KEY ("BoaID")
;

ALTER TABLE "Combibon" ADD CONSTRAINT "PK_Combibon"
	PRIMARY KEY ("CombibonID")
;

ALTER TABLE "Enum_beoordelingsoort" ADD CONSTRAINT "PK_Enum_beoordelingsoort"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_heffingsoort" ADD CONSTRAINT "PK_Enum_heffingsoort"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_statusopenbareactiviteit" ADD CONSTRAINT "PK_Enum_statusopenbareactiviteit"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Fietsregistratie" ADD CONSTRAINT "PK_Fietsregistratie"
	PRIMARY KEY ("FietsregistratieID")
;

ALTER TABLE "Grondslag" ADD CONSTRAINT "PK_Grondslag"
	PRIMARY KEY ("GrondslagID")
;

ALTER TABLE "Heffinggrondslag" ADD CONSTRAINT "PK_Heffinggrondslag"
	PRIMARY KEY ("HeffinggrondslagID")
;

ALTER TABLE "Heffingsverordening" ADD CONSTRAINT "PK_Heffingsverordening"
	PRIMARY KEY ("HeffingsverordeningID")
;

ALTER TABLE "Indiener" ADD CONSTRAINT "PK_Indiener"
	PRIMARY KEY ("IndienerID")
;

ALTER TABLE "Inspectie" ADD CONSTRAINT "PK_Inspectie"
	PRIMARY KEY ("InspectieID")
;

ALTER TABLE "Kosten" ADD CONSTRAINT "PK_Kosten"
	PRIMARY KEY ("KostenID")
;

ALTER TABLE "Leges_grondslag" ADD CONSTRAINT "PK_Leges_grondslag"
	PRIMARY KEY ("Leges_grondslagID")
;

ALTER TABLE "Ligplaatsontheffing" ADD CONSTRAINT "PK_Ligplaatsontheffing"
	PRIMARY KEY ("LigplaatsontheffingID")
;

ALTER TABLE "Moraanvraagofmelding" ADD CONSTRAINT "PK_Moraanvraagofmelding"
	PRIMARY KEY ("MoraanvraagofmeldingID")
;

ALTER TABLE "Openbareactiviteit" ADD CONSTRAINT "PK_Openbareactiviteit"
	PRIMARY KEY ("OpenbareactiviteitID")
;

ALTER TABLE "Precario" ADD CONSTRAINT "PK_Precario"
	PRIMARY KEY ("PrecarioID")
;

ALTER TABLE "Producttype" ADD CONSTRAINT "PK_Producttype"
	PRIMARY KEY ("ProducttypeID")
;

ALTER TABLE "Subproducttype" ADD CONSTRAINT "PK_Subproducttype"
	PRIMARY KEY ("SubproducttypeID")
;

ALTER TABLE "Vaartuig" ADD CONSTRAINT "PK_Vaartuig"
	PRIMARY KEY ("VaartuigID")
;

ALTER TABLE "Vomaanvraagofmelding" ADD CONSTRAINT "PK_Vomaanvraagofmelding"
	PRIMARY KEY ("VomaanvraagofmeldingID")
;

ALTER TABLE "Vordering" ADD CONSTRAINT "PK_Vordering"
	PRIMARY KEY ("VorderingID")
;

ALTER TABLE "Vorderingregel" ADD CONSTRAINT "PK_Vorderingregel"
	PRIMARY KEY ("VorderingregelID")
;

ALTER TABLE "Vth_aanvraagofmelding" ADD CONSTRAINT "PK_Vth_aanvraagofmelding"
	PRIMARY KEY ("Vth-aanvraagofmeldingID")
;

ALTER TABLE "Vth_melding" ADD CONSTRAINT "PK_Vth_melding"
	PRIMARY KEY ("Vth-meldingID")
;

ALTER TABLE "Vthzaak" ADD CONSTRAINT "PK_Vthzaak"
	PRIMARY KEY ("VthzaakID")
;

ALTER TABLE "Waarneming" ADD CONSTRAINT "PK_Waarneming"
	PRIMARY KEY ("WaarnemingID")
;

ALTER TABLE "Waboaanvraagofmelding" ADD CONSTRAINT "PK_Waboaanvraagofmelding"
	PRIMARY KEY ("WaboaanvraagofmeldingID")
;

ALTER TABLE "Woonfraudeaanvraagofmelding" ADD CONSTRAINT "PK_Woonfraudeaanvraagofmelding"
	PRIMARY KEY ("WoonfraudeaanvraagofmeldingID")
;

ALTER TABLE "Woonoverlastaanvraagofmelding" ADD CONSTRAINT "PK_Woonoverlastaanvraagofmelding"
	PRIMARY KEY ("WoonoverlastaanvraagofmeldingID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Aomstatus" ADD CONSTRAINT fk_heeft_aanvraagofmelding
	FOREIGN KEY ("AanvraagofmeldingID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Bevinding" ADD CONSTRAINT fk_bevinding_bevinding
	FOREIGN KEY ("BevindingID") REFERENCES "Bevinding" ("BevindingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Combibon" ADD CONSTRAINT "Fk_combibon_vth_melding"
	FOREIGN KEY ("CombibonID") REFERENCES "Vth_melding" ("Vth-meldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Fietsregistratie" ADD CONSTRAINT "Fk_fietsregistratie_vth_melding"
	FOREIGN KEY ("FietsregistratieID") REFERENCES "Vth_melding" ("Vth-meldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Heffinggrondslag" ADD CONSTRAINT "fk_vermeldIn_heffingsverordeni"
	FOREIGN KEY ("HeffingsverordeningID") REFERENCES "Heffingsverordening" ("HeffingsverordeningID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Heffinggrondslag" ADD CONSTRAINT fk_heeft_zaaktype
	FOREIGN KEY ("ZaaktypeID") REFERENCES "Zaaktype" ("ZaaktypeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Heffingsverordening" ADD CONSTRAINT "Fk_heffingsverordening_document"
	FOREIGN KEY ("HeffingsverordeningID") REFERENCES "Document" ("DocumentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Indiener" ADD CONSTRAINT "Fk_indiener_rechtspersoon"
	FOREIGN KEY ("IndienerID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_activiteit_vthzaak" ADD CONSTRAINT "Fk_kp_activiteit_vthzaak_vthzaak"
	FOREIGN KEY ("VthzaakID") REFERENCES "Vthzaak" ("VthzaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_activiteit_vthzaak" ADD CONSTRAINT "Fk_kp_activiteit_vthzaak_activiteit"
	FOREIGN KEY ("ActiviteitID") REFERENCES "Activiteit" ("ActiviteitID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_bevinding_inspectie" ADD CONSTRAINT "Fk_kp_bevinding_inspectie_inspectie"
	FOREIGN KEY ("InspectieID") REFERENCES "Inspectie" ("InspectieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_bevinding_inspectie" ADD CONSTRAINT "Fk_kp_bevinding_inspectie_bevinding"
	FOREIGN KEY ("BevindingID") REFERENCES "Bevinding" ("BevindingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_grondslag_zaak" ADD CONSTRAINT "Fk_kp_grondslag_zaak_grondslag"
	FOREIGN KEY ("GrondslagID") REFERENCES "Grondslag" ("GrondslagID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_grondslag_zaak" ADD CONSTRAINT "Fk_kp_grondslag_zaak_zaak"
	FOREIGN KEY ("ZaakID") REFERENCES "Zaak" ("ZaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_inspectie_vthzaak" ADD CONSTRAINT "Fk_kp_inspectie_vthzaak_vthzaak"
	FOREIGN KEY ("VthzaakID") REFERENCES "Vthzaak" ("VthzaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_inspectie_vthzaak" ADD CONSTRAINT "Fk_kp_inspectie_vthzaak_inspectie"
	FOREIGN KEY ("InspectieID") REFERENCES "Inspectie" ("InspectieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_kosten_vthzaak" ADD CONSTRAINT "Fk_kp_kosten_vthzaak_vthzaak"
	FOREIGN KEY ("VthzaakID") REFERENCES "Vthzaak" ("VthzaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_kosten_vthzaak" ADD CONSTRAINT "Fk_kp_kosten_vthzaak_kosten"
	FOREIGN KEY ("KostenID") REFERENCES "Kosten" ("KostenID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_leges_grondslag_vthzaak" ADD CONSTRAINT "Fk_kp_leges_grondslag_vthzaak_vthzaak"
	FOREIGN KEY ("VthzaakID") REFERENCES "Vthzaak" ("VthzaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_leges_grondslag_vthzaak" ADD CONSTRAINT "Fk_kp_leges_grondslag_vthzaak_leges_grondslag"
	FOREIGN KEY ("Leges_grondslagID") REFERENCES "Leges_grondslag" ("Leges_grondslagID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_subproducttype_vthzaak" ADD CONSTRAINT "Fk_kp_subproducttype_vthzaak_vthzaak"
	FOREIGN KEY ("VthzaakID") REFERENCES "Vthzaak" ("VthzaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_subproducttype_vthzaak" ADD CONSTRAINT "Fk_kp_subproducttype_vthzaak_subproducttype"
	FOREIGN KEY ("SubproducttypeID") REFERENCES "Subproducttype" ("SubproducttypeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_vordering_vorderingregel" ADD CONSTRAINT "Fk_kp_vordering_vorderingregel_vorderingregel"
	FOREIGN KEY ("VorderingregelID") REFERENCES "Vorderingregel" ("VorderingregelID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_vordering_vorderingregel" ADD CONSTRAINT "Fk_kp_vordering_vorderingregel_vordering"
	FOREIGN KEY ("VorderingID") REFERENCES "Vordering" ("VorderingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_vordering_vthzaak" ADD CONSTRAINT "Fk_kp_vordering_vthzaak_vthzaak"
	FOREIGN KEY ("VthzaakID") REFERENCES "Vthzaak" ("VthzaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_vordering_vthzaak" ADD CONSTRAINT "Fk_kp_vordering_vthzaak_vordering"
	FOREIGN KEY ("VorderingID") REFERENCES "Vordering" ("VorderingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_vth_melding_object" ADD CONSTRAINT "Fk_kp_vth_melding_object_vth_melding"
	FOREIGN KEY ("Vth_meldingID") REFERENCES "Vth_melding" ("Vth-meldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_vth_melding_object" ADD CONSTRAINT "Fk_kp_vth_melding_object_object"
	FOREIGN KEY ("ObjectID") REFERENCES "Object" ("ObjectID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Leges_grondslag" ADD CONSTRAINT fk_heeft_activiteit
	FOREIGN KEY ("ActiviteitID") REFERENCES "Activiteit" ("ActiviteitID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Leges_grondslag" ADD CONSTRAINT fk_heeft_grondslag
	FOREIGN KEY ("GrondslagID") REFERENCES "Grondslag" ("GrondslagID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Moraanvraagofmelding" ADD CONSTRAINT "Fk_moraanvraagofmelding_aanvraagofmelding"
	FOREIGN KEY ("MoraanvraagofmeldingID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Producttype" ADD CONSTRAINT fk_heeft_bedrijfsprocestype
	FOREIGN KEY ("BedrijfsprocestypeID") REFERENCES "Bedrijfsprocestype" ("BedrijfsprocestypeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Producttype" ADD CONSTRAINT "fk_heeftProduct_zaak"
	FOREIGN KEY ("ZaakID") REFERENCES "Zaak" ("ZaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Producttype" ADD CONSTRAINT fk_heeft_zaaktype
	FOREIGN KEY ("ZaaktypeID") REFERENCES "Zaaktype" ("ZaaktypeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subproducttype" ADD CONSTRAINT "FK_Subproducttype_Producttype"
	FOREIGN KEY ("ProducttypeID") REFERENCES "Producttype" ("ProducttypeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vaartuig" ADD CONSTRAINT fk_is_object
	FOREIGN KEY ("ObjectID") REFERENCES "Object" ("ObjectID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vomaanvraagofmelding" ADD CONSTRAINT "Fk_vomaanvraagofmelding_aanvraagofmelding"
	FOREIGN KEY ("VomaanvraagofmeldingID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vorderingregel" ADD CONSTRAINT "FK_Vorderingregel_Kosten"
	FOREIGN KEY ("KostenID") REFERENCES "Kosten" ("KostenID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vth_aanvraagofmelding" ADD CONSTRAINT "Fk_vth_aanvraagofmelding_vomaanvraagofmelding"
	FOREIGN KEY ("Vth_aanvraagofmeldingID") REFERENCES "Vomaanvraagofmelding" ("VomaanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vth_melding" ADD CONSTRAINT fk_verbalisant_boa
	FOREIGN KEY ("BoaID") REFERENCES "Boa" ("BoaID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vth_melding" ADD CONSTRAINT "Fk_vth_melding_aanvraagofmelding"
	FOREIGN KEY ("Vth_meldingID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vthzaak" ADD CONSTRAINT fk_heeft_producttype
	FOREIGN KEY ("ProducttypeID") REFERENCES "Producttype" ("ProducttypeID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vthzaak" ADD CONSTRAINT "Fk_vthzaak_zaak"
	FOREIGN KEY ("VthzaakID") REFERENCES "Zaak" ("ZaakID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Waarneming" ADD CONSTRAINT "Fk_waarneming_vth_melding"
	FOREIGN KEY ("WaarnemingID") REFERENCES "Vth_melding" ("Vth-meldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Waboaanvraagofmelding" ADD CONSTRAINT "Fk_waboaanvraagofmelding_vomaanvraagofmelding"
	FOREIGN KEY ("WaboaanvraagofmeldingID") REFERENCES "Vomaanvraagofmelding" ("VomaanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Woonfraudeaanvraagofmelding" ADD CONSTRAINT "Fk_woonfraudeaanvraagofmelding_aanvraagofmelding"
	FOREIGN KEY ("WoonfraudeaanvraagofmeldingID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Woonoverlastaanvraagofmelding" ADD CONSTRAINT "Fk_woonoverlastaanvraagofmeldin_aanvraagofmelding"
	FOREIGN KEY ("WoonoverlastaanvraagofmeldinID") REFERENCES "Aanvraagofmelding" ("AanvraagofmeldingID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Activiteit"
	IS 'Ieder menselijk handelen waarbij, of ieder menselijk nalaten waardoor een verandering of effect in de (fysieke) leefomgeving wordt of kan worden bewerkstelligd.  Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Activiteit"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Activiteit"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Activiteit"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Activiteit"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Activiteit"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Activiteit"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Activiteit"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Activiteit"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Aomstatus"
	IS 'Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Aomstatus"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Aomstatus"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Aomstatus"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Aomstatus"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Aomstatus"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Aomstatus"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Aomstatus"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Aomstatus"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Bevinding"
	IS 'Een waarneming of conclusie die voortkomt uit een inspectie, controle of onderzoek uitgevoerd door de gemeente. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Bevinding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Bevinding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Bevinding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Bevinding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Bevinding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Bevinding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Bevinding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Bevinding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Boa"
	IS 'Een buitengewoon opsporingsambtenaar (boa) is een ambtenaar met een specifieke opsporingsbevoegdheid. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Boa"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Boa"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Boa"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Boa"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Boa"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Boa"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Boa"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Boa"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Combibon"
	IS 'Arjen deze  is voor jou Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Combibon"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Combibon"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Combibon"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Combibon"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Combibon"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Combibon"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Combibon"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Combibon"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Fietsregistratie"
	IS 'Adminstreren van fietsen Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Fietsregistratie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Fietsregistratie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Fietsregistratie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Fietsregistratie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Fietsregistratie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Fietsregistratie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Fietsregistratie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Fietsregistratie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Grondslag"
	IS 'De juridische of beleidsmatige basis waarop gemeentelijke besluiten, regels of handelingen zijn gebaseerd. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Grondslag"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Grondslag"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Grondslag"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Grondslag"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Grondslag"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Grondslag"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Grondslag"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Grondslag"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Heffinggrondslag"
	IS 'De maatstaf waarop een belasting is gebaseerd, het bedrag op basis waarvan een bepaalde belasting wordt geheven of de premie voor sociale zekerheid wordt vastgesteld. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Heffinggrondslag"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Heffinggrondslag"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Heffinggrondslag"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Heffinggrondslag"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Heffinggrondslag"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Heffinggrondslag"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Heffinggrondslag"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Heffinggrondslag"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Heffingsverordening"
	IS 'Een vastgestelde regeling waarin de grondslagen, tarieven en voorwaarden voor belastingen en heffingen zijn vastgelegd. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Heffingsverordening"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Heffingsverordening"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Heffingsverordening"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Heffingsverordening"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Heffingsverordening"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Heffingsverordening"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Heffingsverordening"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Heffingsverordening"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Indiener"
	IS 'Persoon die meldiing of aanvraag doet Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Indiener"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Indiener"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Indiener"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Indiener"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Indiener"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Indiener"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Indiener"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Indiener"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Inspectie"
	IS 'het inwinnen, verwerken en interpreteren van informatie met het doel om de momentane toestand van de boezemkade vast te stellen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Inspectie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Inspectie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Inspectie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Inspectie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Inspectie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Inspectie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Inspectie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Inspectie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Kosten"
	IS 'De uitgaven of lasten die de gemeente maakt in het kader van haar taken en dienstverlening. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Kosten"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kosten"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kosten"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kosten"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kosten"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kosten"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kosten"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kosten"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_activiteit_vthzaak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_activiteit_vthzaak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_activiteit_vthzaak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_activiteit_vthzaak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_activiteit_vthzaak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_activiteit_vthzaak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_activiteit_vthzaak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_activiteit_vthzaak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_bevinding_inspectie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_bevinding_inspectie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_bevinding_inspectie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_bevinding_inspectie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_bevinding_inspectie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_bevinding_inspectie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_bevinding_inspectie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_bevinding_inspectie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_grondslag_zaak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_grondslag_zaak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_grondslag_zaak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_grondslag_zaak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_grondslag_zaak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_grondslag_zaak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_grondslag_zaak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_grondslag_zaak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_inspectie_vthzaak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_inspectie_vthzaak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_inspectie_vthzaak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_inspectie_vthzaak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_inspectie_vthzaak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_inspectie_vthzaak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_inspectie_vthzaak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_inspectie_vthzaak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_kosten_vthzaak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_kosten_vthzaak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_kosten_vthzaak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_kosten_vthzaak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_kosten_vthzaak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_kosten_vthzaak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_kosten_vthzaak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_kosten_vthzaak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_leges_grondslag_vthzaak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_leges_grondslag_vthzaak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_leges_grondslag_vthzaak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_leges_grondslag_vthzaak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_leges_grondslag_vthzaak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_leges_grondslag_vthzaak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_leges_grondslag_vthzaak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_leges_grondslag_vthzaak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_subproducttype_vthzaak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_subproducttype_vthzaak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_subproducttype_vthzaak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_subproducttype_vthzaak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_subproducttype_vthzaak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_subproducttype_vthzaak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_subproducttype_vthzaak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_subproducttype_vthzaak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_vordering_vorderingregel"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_vordering_vorderingregel"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_vordering_vorderingregel"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_vordering_vorderingregel"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_vordering_vorderingregel"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_vordering_vorderingregel"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_vordering_vorderingregel"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_vordering_vorderingregel"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_vordering_vthzaak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_vordering_vthzaak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_vordering_vthzaak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_vordering_vthzaak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_vordering_vthzaak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_vordering_vthzaak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_vordering_vthzaak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_vordering_vthzaak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_vth_melding_object"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_vth_melding_object"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_vth_melding_object"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_vth_melding_object"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_vth_melding_object"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_vth_melding_object"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_vth_melding_object"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_vth_melding_object"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Leges_grondslag"
	IS 'Leges zijn kosten die officiële overheidsinstanties in rekening brengen voor een dienst. Grondslag is een gegeven waarop het oordeel gebaseerd is. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Leges_grondslag"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Leges_grondslag"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Leges_grondslag"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Leges_grondslag"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Leges_grondslag"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Leges_grondslag"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Leges_grondslag"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Leges_grondslag"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Ligplaatsontheffing"
	IS 'Tijdelijke toestemming voor het innemen van een ligplaats op een locatie in een gebied met een verbod op ligplaatsen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Ligplaatsontheffing"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Ligplaatsontheffing"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Ligplaatsontheffing"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Ligplaatsontheffing"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Ligplaatsontheffing"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Ligplaatsontheffing"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Ligplaatsontheffing"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Ligplaatsontheffing"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Moraanvraagofmelding"
	IS 'Een door een burger of organisatie ingediend verzoek een besluit te nemen of om informatie te verstrekken, of een ingediende melding betreffende een waargenomen probleem, gebrek of gevaar in de openbare ruimte, die valt onder de verantwoordelijkheid van de lokale overheid voor onderhoud, beheer of handhaving. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Moraanvraagofmelding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Moraanvraagofmelding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Moraanvraagofmelding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Moraanvraagofmelding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Moraanvraagofmelding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Moraanvraagofmelding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Moraanvraagofmelding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Moraanvraagofmelding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Openbareactiviteit"
	IS 'Activiteit in het publieke domein Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Openbareactiviteit"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Openbareactiviteit"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Openbareactiviteit"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Openbareactiviteit"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Openbareactiviteit"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Openbareactiviteit"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Openbareactiviteit"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Openbareactiviteit"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Precario"
	IS 'Belasting die specifiek wordt geheven voor het plaatsen van voorwerpen onder, op of boven voor de openbare dienst bestemde gemeentegrond.  Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Precario"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Precario"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Precario"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Precario"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Precario"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Precario"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Precario"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Precario"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Producttype"
	IS 'Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Producttype"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Producttype"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Producttype"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Producttype"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Producttype"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Producttype"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Producttype"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Producttype"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Subproducttype"
	IS 'Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Subproducttype"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Subproducttype"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Subproducttype"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Subproducttype"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Subproducttype"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Subproducttype"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Subproducttype"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Subproducttype"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vaartuig"
	IS 'Een zee- of binnenvaartuig, tot de vaart gebruikt of bestemd, daaronder begrepen drijvende werktuigen, zoals baggerwerktuigen, kranen, bokken, elevators, alsmede woonschepen, glijboten en ponten. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vaartuig"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vaartuig"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vaartuig"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vaartuig"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vaartuig"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vaartuig"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vaartuig"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vaartuig"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vomaanvraagofmelding"
	IS 'VOM staat voor Vergunning, Ontheffing of Melding. Het betreft hier een melding of een aanvraag voor een vergunning of een ontheffing. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vomaanvraagofmelding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vomaanvraagofmelding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vomaanvraagofmelding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vomaanvraagofmelding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vomaanvraagofmelding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vomaanvraagofmelding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vomaanvraagofmelding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vomaanvraagofmelding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vordering"
	IS 'Een recht om een bedrag aan geld te ontvangen van een natuurlijke persoon of rechtspersoon, vaak voortvloeiend uit belastingaanslagen, heffingen of andere diensten. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vordering"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vordering"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vordering"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vordering"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vordering"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vordering"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vordering"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vordering"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vorderingregel"
	IS 'Een voorschrift of juridische bepaling die de voorwaarden, termijnen en procedures bepaalt waaronder een schuldeiser een vordering kan uitoefenen tegen een schuldenaar. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vorderingregel"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vorderingregel"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vorderingregel"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vorderingregel"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vorderingregel"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vorderingregel"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vorderingregel"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vorderingregel"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vth_aanvraagofmelding"
	IS 'VTH staat voor Vergunning, Toezicht en Handhaving. Het betreft hier een melding of een aanvraag voor een vergunning of een melding voor Toezicht en/of Handhaving. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vth_aanvraagofmelding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vth_aanvraagofmelding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vth_aanvraagofmelding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vth_aanvraagofmelding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vth_aanvraagofmelding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vth_aanvraagofmelding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vth_aanvraagofmelding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vth_aanvraagofmelding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vth_melding"
	IS 'Melding met betrekking tot Vergunningen, Toezicht en Handhaving Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vth_melding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vth_melding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vth_melding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vth_melding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vth_melding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vth_melding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vth_melding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vth_melding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vthzaak"
	IS 'Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vthzaak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vthzaak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vthzaak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vthzaak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vthzaak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vthzaak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vthzaak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vthzaak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Waarneming"
	IS 'Handhavende taak in het kader van VTH Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Waarneming"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Waarneming"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Waarneming"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Waarneming"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Waarneming"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Waarneming"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Waarneming"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Waarneming"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Waboaanvraagofmelding"
	IS 'Aanvraag of medling in het kader van de Wet algemene bepalingen omgevingsrecht (WABO) Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Waboaanvraagofmelding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Waboaanvraagofmelding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Waboaanvraagofmelding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Waboaanvraagofmelding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Waboaanvraagofmelding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Waboaanvraagofmelding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Waboaanvraagofmelding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Waboaanvraagofmelding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Woonfraudeaanvraagofmelding"
	IS 'Melding of aanvraag van woonfraude Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding".gemeentenaam
	IS 'Naam van de gemeente.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding".straatnaam
	IS 'Straatnaam.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding".huisnummer
	IS 'Huisnummer'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding".huisletter
	IS 'Huisletter'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding".huisnummertoevoeging
	IS 'Huisnummertoevoeging'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding".postcode
	IS 'Postcode'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."BAGID"
	IS 'BAGID'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Woonfraudeaanvraagofmelding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Woonoverlastaanvraagofmelding"
	IS 'Melding of aanvraag met betrekking tot Woonoverlast Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Woonoverlastaanvraagofmelding"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Woonoverlastaanvraagofmelding"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Woonoverlastaanvraagofmelding"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Woonoverlastaanvraagofmelding"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Woonoverlastaanvraagofmelding"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Woonoverlastaanvraagofmelding"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Woonoverlastaanvraagofmelding"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Woonoverlastaanvraagofmelding"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
