/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 06-mrt-2025 13:58:09 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Bankrekening" CASCADE
;

DROP TABLE IF EXISTS "Hypotheek" CASCADE
;

DROP TABLE IF EXISTS "Kp_client_bankrekening" CASCADE
;

DROP TABLE IF EXISTS "Kp_hypotheek_onroerendGoed" CASCADE
;

DROP TABLE IF EXISTS "Kp_profiel_vermogenscomponent" CASCADE
;

DROP TABLE IF EXISTS "Kp_vermogenscomponent_waardepe" CASCADE
;

DROP TABLE IF EXISTS "Motorvoertuig" CASCADE
;

DROP TABLE IF EXISTS "OnroerendGoed" CASCADE
;

DROP TABLE IF EXISTS "Vermogenscomponent" CASCADE
;

DROP TABLE IF EXISTS "Waardepeiling" CASCADE
;

/* Create Tables */

CREATE TABLE "Bankrekening"
(
	"BankrekeningId" varchar(50) NULL,
	"Bankrekeningnummer" varchar(50) NULL,
	"Brontype" varchar(50) NULL,
	"DatumAanvangBankrekening" date NULL,
	"DatumEindeBankrekening" date NULL,
	"Iban" varchar(50) NULL,
	"Rekeningtype" varchar(50) NULL,
	"Tenaamstelling" varchar(50) NULL,
	"VoorkeurBankrekening" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"BankrekeningID" integer NOT NULL
)
;

CREATE TABLE "Hypotheek"
(
	"Overwaarde" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"HypotheekID" integer NOT NULL
)
;

CREATE TABLE "Kp_client_bankrekening"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"BankrekeningID" integer NULL
)
;

CREATE TABLE "Kp_hypotheek_onroerendGoed"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OnroerendGoedID" integer NULL,
	"HypotheekID" integer NULL
)
;

CREATE TABLE "Kp_profiel_vermogenscomponent"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VermogenscomponentID" integer NULL
)
;

CREATE TABLE "Kp_vermogenscomponent_waardepe"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"WaardepeilingID" integer NULL,
	"VermogenscomponentID" integer NULL
)
;

CREATE TABLE "Motorvoertuig"
(
	"Kenteken" varchar(50) NULL,
	"SoortMotorvoertuig" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"MotorvoertuigID" integer NOT NULL
)
;

CREATE TABLE "OnroerendGoed"
(
	"Overwaarde" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"OnroerendGoedID" integer NOT NULL
)
;

CREATE TABLE "Vermogenscomponent"
(
	"CodeSoortVermogenscomponent" varchar(50) NULL,
	"DatumVaststellingVermogencom" date NULL,
	"NogAanTeSprekenVermogen" varchar(50) NULL,
	"VermogenscomponentId" integer NULL,
	"VrijTeLatenVermogen" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VermogenscomponentID" integer NOT NULL
)
;

CREATE TABLE "Waardepeiling"
(
	"BijgevoegdBewijs" varchar(50) NULL,
	"Brontype" varchar(50) NULL,
	"DatumAanspraakVermogenscompo" date NULL,
	"LinkNaarBewijs" varchar(50) NULL,
	"Peilmoment" date NULL,
	"WaardeVermogenscomponent" varchar(50) NULL,
	"Waardepeilingid" varchar(50) NULL,
	"WaardesoortVermogenscomponent" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"WaardepeilingID" integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Bankrekening" ADD CONSTRAINT "PK_Bankrekening"
	PRIMARY KEY ("BankrekeningID")
;

ALTER TABLE "Hypotheek" ADD CONSTRAINT "PK_Hypotheek"
	PRIMARY KEY ("HypotheekID")
;

ALTER TABLE "Motorvoertuig" ADD CONSTRAINT "PK_Motorvoertuig"
	PRIMARY KEY ("MotorvoertuigID")
;

ALTER TABLE "OnroerendGoed" ADD CONSTRAINT "PK_OnroerendGoed"
	PRIMARY KEY ("OnroerendGoedID")
;

ALTER TABLE "Vermogenscomponent" ADD CONSTRAINT "PK_Vermogenscomponent"
	PRIMARY KEY ("VermogenscomponentID")
;

ALTER TABLE "Waardepeiling" ADD CONSTRAINT "PK_Waardepeiling"
	PRIMARY KEY ("WaardepeilingID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Bankrekening" ADD CONSTRAINT "Fk_bankrekening_vermogenscomponent"
	FOREIGN KEY ("BankrekeningID") REFERENCES "Vermogenscomponent" ("VermogenscomponentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Hypotheek" ADD CONSTRAINT "Fk_hypotheek_vermogenscomponent"
	FOREIGN KEY ("HypotheekID") REFERENCES "Vermogenscomponent" ("VermogenscomponentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_client_bankrekening" ADD CONSTRAINT "Fk_kp_client_bankrekening_bankrekening"
	FOREIGN KEY ("BankrekeningID") REFERENCES "Bankrekening" ("BankrekeningID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_hypotheek_onroerendGoed" ADD CONSTRAINT "Fk_kp_hypotheek_onroerendgoed_onroerendGoed"
	FOREIGN KEY ("OnroerendGoedID") REFERENCES "OnroerendGoed" ("OnroerendGoedID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_hypotheek_onroerendGoed" ADD CONSTRAINT "Fk_kp_hypotheek_onroerendgoed_hypotheek"
	FOREIGN KEY ("HypotheekID") REFERENCES "Hypotheek" ("HypotheekID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_profiel_vermogenscomponent" ADD CONSTRAINT "Fk_kp_profiel_vermogenscomponent_vermogenscomponent"
	FOREIGN KEY ("VermogenscomponentID") REFERENCES "Vermogenscomponent" ("VermogenscomponentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_vermogenscomponent_waardepe" ADD CONSTRAINT "Fk_kp_vermogenscomponent_waardepe_waardepeiling"
	FOREIGN KEY ("WaardepeilingID") REFERENCES "Waardepeiling" ("WaardepeilingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_vermogenscomponent_waardepe" ADD CONSTRAINT "Fk_kp_vermogenscomponent_waardepe_vermogenscomponent"
	FOREIGN KEY ("VermogenscomponentID") REFERENCES "Vermogenscomponent" ("VermogenscomponentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Motorvoertuig" ADD CONSTRAINT "Fk_motorvoertuig_vermogenscomponent"
	FOREIGN KEY ("MotorvoertuigID") REFERENCES "Vermogenscomponent" ("VermogenscomponentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "OnroerendGoed" ADD CONSTRAINT "Fk_onroerendGoed_vermogenscomponent"
	FOREIGN KEY ("OnroerendGoedID") REFERENCES "Vermogenscomponent" ("VermogenscomponentID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Bankrekening"
	IS 'De gegevens die betrekking hebben op een bankrekening van een PERSOON of een RECHTSPERSOON.Bron: SGR 16.0We kiezen er voor om bankrekening als zelfstandig concept op te nemen, omdat het mogelijk is dat eenzelfde bankrekening gekoppeld kan zijn aan meerdere personen. Voor rechtspersonen geldt dat een bankrekening maar aan ten hoogste 1 ORGANISATORISCHE EENHEID gekoppeld kan zijn. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Bankrekening"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Bankrekening"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Bankrekening"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Bankrekening"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Bankrekening"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Bankrekening"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Bankrekening"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Bankrekening"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Hypotheek"
	IS 'Een hypotheek is een lening waarbij een onroerend goed, zoals een woning, dient als onderpand voor de schuld. Het wordt doorgaans verstrekt door een financiële instelling, zoals een bank, en stelt de lener in staat om een woning te kopen of te bouwen. De lening wordt over een afgesproken periode terugbetaald, inclusief rente. Als de lener niet aan de betalingsverplichtingen voldoet, heeft de kredietverstrekker het recht om het onderpand te verkopen om de openstaande schuld te vereffenen. Een hypotheek is daarmee zowel een financieringsvorm als een juridische zekerheid voor de kredietverstrekker. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Hypotheek"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Hypotheek"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Hypotheek"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Hypotheek"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Hypotheek"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Hypotheek"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Hypotheek"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Hypotheek"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_client_bankrekening"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_client_bankrekening"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_client_bankrekening"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_client_bankrekening"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_client_bankrekening"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_client_bankrekening"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_client_bankrekening"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_client_bankrekening"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_hypotheek_onroerendGoed"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_hypotheek_onroerendGoed"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_hypotheek_onroerendGoed"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_hypotheek_onroerendGoed"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_hypotheek_onroerendGoed"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_hypotheek_onroerendGoed"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_hypotheek_onroerendGoed"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_hypotheek_onroerendGoed"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_profiel_vermogenscomponent"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_profiel_vermogenscomponent"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_profiel_vermogenscomponent"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_profiel_vermogenscomponent"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_profiel_vermogenscomponent"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_profiel_vermogenscomponent"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_profiel_vermogenscomponent"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_profiel_vermogenscomponent"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_vermogenscomponent_waardepe"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_vermogenscomponent_waardepe"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_vermogenscomponent_waardepe"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_vermogenscomponent_waardepe"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_vermogenscomponent_waardepe"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_vermogenscomponent_waardepe"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_vermogenscomponent_waardepe"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_vermogenscomponent_waardepe"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Motorvoertuig"
	IS 'Een motorvoertuig is een voertuig dat is uitgerust met een motor als krachtbron en bedoeld is voor het vervoer van personen, goederen of het uitvoeren van specifieke taken. Het kan zich zelfstandig voortbewegen zonder de directe fysieke inspanning van een bestuurder of passagier. Voorbeelden van motorvoertuigen zijn auto’s, vrachtwagens, motorfietsen en bussen. Motorvoertuigen zijn doorgaans voorzien van wielen en rijden op de weg, en het gebruik ervan is vaak gebonden aan wettelijke regels, zoals registratie, verzekering en rijbewijsvereisten. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Motorvoertuig"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Motorvoertuig"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Motorvoertuig"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Motorvoertuig"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Motorvoertuig"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Motorvoertuig"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Motorvoertuig"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Motorvoertuig"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "OnroerendGoed"
	IS 'Onroerend goed is een juridische term die verwijst naar fysieke objecten die duurzaam met de grond zijn verbonden en niet zonder schade kunnen worden verplaatst. Dit omvat gronden, gebouwen, woningen en andere constructies die vast met de grond zijn verbonden, zoals bruggen of schuren. Onroerend goed wordt vaak onderscheiden van roerende zaken, die wel verplaatsbaar zijn. Het eigendom en de overdracht van onroerend goed zijn gebonden aan specifieke wettelijke regels, zoals registratie in openbare registers en het opstellen van notariële akten. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "OnroerendGoed"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "OnroerendGoed"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "OnroerendGoed"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "OnroerendGoed"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "OnroerendGoed"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "OnroerendGoed"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "OnroerendGoed"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "OnroerendGoed"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vermogenscomponent"
	IS 'Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vermogenscomponent"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vermogenscomponent"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vermogenscomponent"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vermogenscomponent"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vermogenscomponent"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vermogenscomponent"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vermogenscomponent"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vermogenscomponent"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Waardepeiling"
	IS 'Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Waardepeiling"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Waardepeiling"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Waardepeiling"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Waardepeiling"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Waardepeiling"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Waardepeiling"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Waardepeiling"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Waardepeiling"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
