/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 06-mrt-2025 14:44:14 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Betaalmoment" CASCADE
;

DROP TABLE IF EXISTS "Enum_subsidieniveau" CASCADE
;

DROP TABLE IF EXISTS "Rapportagemoment" CASCADE
;

DROP TABLE IF EXISTS "Sector" CASCADE
;

DROP TABLE IF EXISTS "Subsidie" CASCADE
;

DROP TABLE IF EXISTS "Subsidieaanvraag" CASCADE
;

DROP TABLE IF EXISTS "Subsidiebeschikking" CASCADE
;

DROP TABLE IF EXISTS "Subsidiecomponent" CASCADE
;

DROP TABLE IF EXISTS "Subsidieprogramma" CASCADE
;

DROP TABLE IF EXISTS "Taak" CASCADE
;

/* Create Tables */

CREATE TABLE "Betaalmoment"
(
	"Bedrag" double precision NULL,
	"Datum" date NULL,
	"Voorschot" boolean NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"BetaalmomentID" integer NOT NULL,
	"SubsidiecomponentID" integer NOT NULL
)
;

CREATE TABLE "Enum_subsidieniveau"
(
	"Gemeente" varchar(50) NULL,
	"Provincie" varchar(50) NULL,
	"Nationaal" varchar(50) NULL,
	"Europees" varchar(50) NULL,
	"Regionaal" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Rapportagemoment"
(
	"Datum" date NULL,
	"Naam" varchar(200) NULL,
	"Omschrijving" text NULL,
	"Termijn" integer NULL,	-- Termijn in dagen
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"RapportagemomentID" integer NOT NULL,
	"SubsidieID" integer NULL,
	"RechtspersoonID" integer NULL
)
;

CREATE TABLE "Sector"
(
	"Naam" varchar(200) NULL,
	"Omschrijving" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SectorID" integer NOT NULL
)
;

CREATE TABLE "Subsidie"
(
	"Accountantscontrole" boolean NULL,
	"Cofinanciering" double precision NULL,
	"Datumbehandeltermijn" date NULL,
	"Datumbewaartermijn" date NULL,
	"Datumeinde" date NULL,
	"Datumstart" date NULL,
	"Datumsubsidievaststelling" date NULL,
	"Datumverzendingeindeafrekening" date NULL,
	"Deadlineindiening" date NULL,
	"Doelstelling" varchar(200) NULL,
	"Gerealiseerdeprojectkosten" date NULL,
	"Hoogtesubsidie" double precision NULL,
	"Niveau" varchar(50) NULL,
	"Onderwerp" varchar(200) NULL,
	"Ontvangenbedrag" double precision NULL,
	"Opmerkingen" text NULL,
	"Opmerkingenvoorschotten" text NULL,
	"Prestatiesubsidie" boolean NULL,	-- Als Nee dan is het een stimuleringssubsidie  Alleen bij uitgaande subsidies, anders NULL!
	"Socialreturnbedrag" double precision NULL,
	"Socialreturnnagekomen" boolean NULL,
	"Socialreturnverplichting" boolean NULL,
	"Status" varchar(80) NULL,
	"Subsidiebedrag" double precision NULL,
	"Subsidiesoort" varchar(80) NULL,
	"Subsidievaststellingbedrag" double precision NULL,
	"Uitgaandesubsidie" boolean NULL,
	"Verantwoordenop" date NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SubsidieID" integer NOT NULL,
	"SectorID" integer NULL,
	"SubsidieaanvraagID" integer NOT NULL,
	"SubsidiebeschikkingID" integer NULL,
	"SubsidieprogrammaID" integer NULL,
	"KostenplaatsID" integer NULL,
	"DocumentID" integer NULL,
	"MedewerkerID" integer NULL,
	"RechtspersoonID" integer NULL
)
;

CREATE TABLE "Subsidieaanvraag"
(
	"Aangevraagdbedrag" double precision NULL,
	"Datumindiening" date NULL,
	"Kenmerk" varchar(80) NULL,
	"Ontvangstbevestiging" date NULL,
	"Verwachtebeschikking" date NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SubsidieaanvraagID" integer NOT NULL
)
;

CREATE TABLE "Subsidiebeschikking"
(
	"Beschikkingsnummer" varchar(80) NULL,
	"Beschiktbedrag" double precision NULL,
	"Besluit" varchar(80) NULL,
	"Internkenmerk" varchar(80) NULL,
	"Kenmerk" varchar(80) NULL,
	"Ontvangen" date NULL,
	"Opmerkingen" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SubsidiebeschikkingID" integer NOT NULL,
	"SubsidieaanvraagID" integer NULL
)
;

CREATE TABLE "Subsidiecomponent"
(
	"Gereserveerdbedrag" double precision NULL,
	"Toegekendbedrag" double precision NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SubsidiecomponentID" integer NOT NULL,
	"KostenplaatsID" integer NULL
)
;

CREATE TABLE "Subsidieprogramma"
(
	"Datumeinde" date NULL,
	"Datumstart" date NULL,
	"Naam" varchar(200) NULL,
	"Omschrijving" text NULL,
	"Programmabegroting" double precision NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"SubsidieprogrammaID" integer NOT NULL,
	"OrganisatorischeeenheidID" integer NULL
)
;

CREATE TABLE "Taak"
(
	"Datumeinde" date NULL,
	"Datumstart" date NULL,
	"Taakomschrijving" text NULL,
	"Termijn" integer NULL,	-- Termijn in dagen 
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"TaakID" integer NOT NULL,
	"SubsidieID" integer NULL,
	"RechtspersoonID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Betaalmoment" ADD CONSTRAINT "PK_Betaalmoment"
	PRIMARY KEY ("BetaalmomentID")
;

ALTER TABLE "Enum_subsidieniveau" ADD CONSTRAINT "PK_Enum_subsidieniveau"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Rapportagemoment" ADD CONSTRAINT "PK_Rapportagemoment"
	PRIMARY KEY ("RapportagemomentID")
;

ALTER TABLE "Sector" ADD CONSTRAINT "PK_Sector"
	PRIMARY KEY ("SectorID")
;

ALTER TABLE "Subsidie" ADD CONSTRAINT "PK_Subsidie"
	PRIMARY KEY ("SubsidieID")
;

ALTER TABLE "Subsidieaanvraag" ADD CONSTRAINT "PK_Subsidieaanvraag"
	PRIMARY KEY ("SubsidieaanvraagID")
;

ALTER TABLE "Subsidiebeschikking" ADD CONSTRAINT "PK_Subsidiebeschikking"
	PRIMARY KEY ("SubsidiebeschikkingID")
;

ALTER TABLE "Subsidiecomponent" ADD CONSTRAINT "PK_Subsidiecomponent"
	PRIMARY KEY ("SubsidiecomponentID")
;

ALTER TABLE "Subsidieprogramma" ADD CONSTRAINT "PK_Subsidieprogramma"
	PRIMARY KEY ("SubsidieprogrammaID")
;

ALTER TABLE "Taak" ADD CONSTRAINT "PK_Taak"
	PRIMARY KEY ("TaakID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Betaalmoment" ADD CONSTRAINT fk_heeft_subsidiecomponent
	FOREIGN KEY ("SubsidiecomponentID") REFERENCES "Subsidiecomponent" ("SubsidiecomponentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Rapportagemoment" ADD CONSTRAINT fk_heeft_subsidie
	FOREIGN KEY ("SubsidieID") REFERENCES "Subsidie" ("SubsidieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Rapportagemoment" ADD CONSTRAINT fk_projectleider_rechtspersoon
	FOREIGN KEY ("RechtspersoonID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT "FK_Subsidie_Sector"
	FOREIGN KEY ("SectorID") REFERENCES "Sector" ("SectorID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT fk_betreft_subsidieaanvraag
	FOREIGN KEY ("SubsidieaanvraagID") REFERENCES "Subsidieaanvraag" ("SubsidieaanvraagID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT fk_betreft_subsidiebeschikking
	FOREIGN KEY ("SubsidiebeschikkingID") REFERENCES "Subsidiebeschikking" ("SubsidiebeschikkingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT "fk_gaatOver_subsidieprogramma"
	FOREIGN KEY ("SubsidieprogrammaID") REFERENCES "Subsidieprogramma" ("SubsidieprogrammaID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT "FK_Subsidie_Kostenplaats"
	FOREIGN KEY ("KostenplaatsID") REFERENCES "Kostenplaats" ("KostenplaatsID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT "FK_Subsidie_Document"
	FOREIGN KEY ("DocumentID") REFERENCES "Document" ("DocumentID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT fk_aanvrager_medewerker
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT "FK_Subsidie_Medewerker"
	FOREIGN KEY ("MedewerkerID") REFERENCES "Medewerker" ("MedewerkerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT fk_aanvrager_rechtspersoon
	FOREIGN KEY ("RechtspersoonID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidie" ADD CONSTRAINT "FK_Subsidie_Rechtspersoon"
	FOREIGN KEY ("RechtspersoonID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidiebeschikking" ADD CONSTRAINT "fk_mondtUit_subsidieaanvraag"
	FOREIGN KEY ("SubsidieaanvraagID") REFERENCES "Subsidieaanvraag" ("SubsidieaanvraagID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidiecomponent" ADD CONSTRAINT "FK_Subsidiecomponent_Kostenplaats"
	FOREIGN KEY ("KostenplaatsID") REFERENCES "Kostenplaats" ("KostenplaatsID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Subsidieprogramma" ADD CONSTRAINT "FK_Subsidieprogramma_Organisatorischeeenheid"
	FOREIGN KEY ("OrganisatorischeeenheidID") REFERENCES "Organisatorischeeenheid" ("OrganisatorischeeenheidID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Taak" ADD CONSTRAINT fk_heeft_subsidie
	FOREIGN KEY ("SubsidieID") REFERENCES "Subsidie" ("SubsidieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Taak" ADD CONSTRAINT "FK_Taak_Rechtspersoon"
	FOREIGN KEY ("RechtspersoonID") REFERENCES "Rechtspersoon" ("RechtspersoonID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Betaalmoment"
	IS 'Moment waarop er een bepaald deel van de subsidie betaald moet worden. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Betaalmoment"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Betaalmoment"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Betaalmoment"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Betaalmoment"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Betaalmoment"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Betaalmoment"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Betaalmoment"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Betaalmoment"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Rapportagemoment"
	IS 'Een vantevoren bepaald tijdstip waarom een gegevensanalyse wordt uitgevoerd Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Rapportagemoment"."Termijn"
	IS 'Termijn in dagen'
;

COMMENT ON COLUMN "Rapportagemoment"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Rapportagemoment"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Rapportagemoment"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Rapportagemoment"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Rapportagemoment"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Rapportagemoment"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Rapportagemoment"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Rapportagemoment"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Sector"
	IS 'Sector is de verzameling van werkzaamheden, gericht op de productie van bepaalde goederen en diensten. Het gaat hierbij niet alleen om activiteiten van het bedrijfsleven, maar ook om activiteiten van niet op winst gerichte instellingen en de overheid. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Sector"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Sector"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Sector"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Sector"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Sector"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Sector"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Sector"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Sector"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Subsidie"
	IS 'Aan derden toegekende financiele middelen, bestemd voor het uitvoeren van bepaalde activiteiten Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Subsidie"."Prestatiesubsidie"
	IS 'Als Nee dan is het een stimuleringssubsidie

Alleen bij uitgaande subsidies, anders NULL!'
;

COMMENT ON COLUMN "Subsidie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Subsidie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Subsidie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Subsidie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Subsidie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Subsidie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Subsidie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Subsidie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Subsidieaanvraag"
	IS 'Aanvraag voor een subsidie Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Subsidieaanvraag"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Subsidieaanvraag"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Subsidieaanvraag"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Subsidieaanvraag"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Subsidieaanvraag"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Subsidieaanvraag"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Subsidieaanvraag"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Subsidieaanvraag"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Subsidiebeschikking"
	IS 'Besluit over het al dan niet toekennen van een subsidie Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Subsidiebeschikking"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Subsidiebeschikking"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Subsidiebeschikking"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Subsidiebeschikking"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Subsidiebeschikking"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Subsidiebeschikking"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Subsidiebeschikking"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Subsidiebeschikking"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Subsidiecomponent"
	IS 'Onderdeel van een subisidie met een eigen kostenplaats. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Subsidiecomponent"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Subsidiecomponent"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Subsidiecomponent"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Subsidiecomponent"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Subsidiecomponent"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Subsidiecomponent"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Subsidiecomponent"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Subsidiecomponent"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Subsidieprogramma"
	IS 'Programma waarin meerdere subsidies worden verleend vanuit een bepaalde samenhang Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Subsidieprogramma"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Subsidieprogramma"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Subsidieprogramma"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Subsidieprogramma"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Subsidieprogramma"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Subsidieprogramma"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Subsidieprogramma"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Subsidieprogramma"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Taak"
	IS 'Een samenhangende set activiteiten in het kader van een subsidie. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Taak"."Termijn"
	IS 'Termijn in dagen '
;

COMMENT ON COLUMN "Taak"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Taak"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Taak"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Taak"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Taak"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Taak"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Taak"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Taak"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
