/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 06-mrt-2025 15:01:31 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Foto" CASCADE
;

DROP TABLE IF EXISTS "Gebied" CASCADE
;

DROP TABLE IF EXISTS "Gebiedengroep" CASCADE
;

DROP TABLE IF EXISTS "Lijn" CASCADE
;

DROP TABLE IF EXISTS "Lijnengroep" CASCADE
;

DROP TABLE IF EXISTS "Locatie" CASCADE
;

DROP TABLE IF EXISTS "Punt" CASCADE
;

DROP TABLE IF EXISTS "Puntengroep" CASCADE
;

DROP TABLE IF EXISTS "Video_opname" CASCADE
;

/* Create Tables */

CREATE TABLE "Foto"
(
	"Bestandsgrootte" integer NULL,	-- Bestandsgrootte in bytes
	"Bestandsnaam" varchar(200) NULL,
	"Bestandstype" varchar(80) NULL,
	"Datumtijd" timestamp without time zone NULL,
	"Locatie_lat" double precision NULL,
	"Locatie_long" double precision NULL,
	"Locatie_rdx" double precision NULL,
	"Locatie_rdy" double precision NULL,
	"Pixelsx" integer NULL,
	"Pixelsy" integer NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"FotoID" integer NOT NULL,
	"BeschermdeStatusID" integer NULL,
	"Vth_meldingID" integer NULL
)
;

CREATE TABLE "Gebied"
(
	"Gebied" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"GebiedID" integer NOT NULL,
	"GebiedengroepID" integer NULL
)
;

CREATE TABLE "Gebiedengroep"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"GebiedengroepID" integer NOT NULL
)
;

CREATE TABLE "Lijn"
(
	"Lijn" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"LijnID" integer NOT NULL,
	"LijnengroepID" integer NULL
)
;

CREATE TABLE "Lijnengroep"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"LijnengroepID" integer NOT NULL
)
;

CREATE TABLE "Locatie"
(
	"Hoogte" integer NULL,	-- Hoogte in meters. Negatief is onder het maaiveld en positief boven het maaiveld
	"Naam" varchar(200) NULL,
	"Nen3610id" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"LocatieID" integer NOT NULL
)
;

CREATE TABLE "Punt"
(
	"Punt_lat" double precision NULL,
	"Punt_long" double precision NULL,
	"Punt_rdx" double precision NULL,
	"Punt_rdy" double precision NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"PuntID" integer NOT NULL,
	"PuntengroepID" integer NULL
)
;

CREATE TABLE "Puntengroep"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"PuntengroepID" integer NOT NULL
)
;

CREATE TABLE "Video_opname"
(
	"Bestandsgrootte" integer NULL,
	"Datumtijd" timestamp without time zone NULL,
	"Lengte" integer NULL,
	"Videoformaat" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"Video-opnameID" integer NOT NULL,
	"VergaderingID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Foto" ADD CONSTRAINT "PK_Foto"
	PRIMARY KEY ("FotoID")
;

ALTER TABLE "Gebied" ADD CONSTRAINT "PK_Gebied"
	PRIMARY KEY ("GebiedID")
;

ALTER TABLE "Gebiedengroep" ADD CONSTRAINT "PK_Gebiedengroep"
	PRIMARY KEY ("GebiedengroepID")
;

ALTER TABLE "Lijn" ADD CONSTRAINT "PK_Lijn"
	PRIMARY KEY ("LijnID")
;

ALTER TABLE "Lijnengroep" ADD CONSTRAINT "PK_Lijnengroep"
	PRIMARY KEY ("LijnengroepID")
;

ALTER TABLE "Locatie" ADD CONSTRAINT "PK_Locatie"
	PRIMARY KEY ("LocatieID")
;

ALTER TABLE "Punt" ADD CONSTRAINT "PK_Punt"
	PRIMARY KEY ("PuntID")
;

ALTER TABLE "Puntengroep" ADD CONSTRAINT "PK_Puntengroep"
	PRIMARY KEY ("PuntengroepID")
;

ALTER TABLE "Video_opname" ADD CONSTRAINT "PK_Video_opname"
	PRIMARY KEY ("Video-opnameID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Foto" ADD CONSTRAINT "fk_monumentFotos_beschermdeSta"
	FOREIGN KEY ("BeschermdeStatusID") REFERENCES "BeschermdeStatus" ("BeschermdeStatusID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Foto" ADD CONSTRAINT fk_heeft_vth_melding
	FOREIGN KEY ("Vth_meldingID") REFERENCES "Vth_melding" ("Vth-meldingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Gebied" ADD CONSTRAINT "Fk_gebied_locatie"
	FOREIGN KEY ("GebiedID") REFERENCES "Locatie" ("LocatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Gebied" ADD CONSTRAINT fk_omvat_gebiedengroep
	FOREIGN KEY ("GebiedengroepID") REFERENCES "Gebiedengroep" ("GebiedengroepID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Gebiedengroep" ADD CONSTRAINT "Fk_gebiedengroep_locatie"
	FOREIGN KEY ("GebiedengroepID") REFERENCES "Locatie" ("LocatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lijn" ADD CONSTRAINT "Fk_lijn_locatie"
	FOREIGN KEY ("LijnID") REFERENCES "Locatie" ("LocatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lijn" ADD CONSTRAINT fk_omvat_lijnengroep
	FOREIGN KEY ("LijnengroepID") REFERENCES "Lijnengroep" ("LijnengroepID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Lijnengroep" ADD CONSTRAINT "Fk_lijnengroep_locatie"
	FOREIGN KEY ("LijnengroepID") REFERENCES "Locatie" ("LocatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Punt" ADD CONSTRAINT "Fk_punt_locatie"
	FOREIGN KEY ("PuntID") REFERENCES "Locatie" ("LocatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Punt" ADD CONSTRAINT fk_omvat_puntengroep
	FOREIGN KEY ("PuntengroepID") REFERENCES "Puntengroep" ("PuntengroepID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Puntengroep" ADD CONSTRAINT "Fk_puntengroep_locatie"
	FOREIGN KEY ("PuntengroepID") REFERENCES "Locatie" ("LocatieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Video_opname" ADD CONSTRAINT fk_betreft_vergadering
	FOREIGN KEY ("VergaderingID") REFERENCES "Vergadering" ("VergaderingID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Foto"
	IS 'Afbeelding op een plat vlak vervaardigd door middel van fotografie Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Foto"."Bestandsgrootte"
	IS 'Bestandsgrootte in bytes'
;

COMMENT ON COLUMN "Foto"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Foto"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Foto"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Foto"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Foto"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Foto"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Foto"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Foto"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Gebied"
	IS 'Een aaneengesloten gedeelte van een wijk, waarvan de grenzen zo veel mogelijk gebaseerd zijn op topografische elementen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Gebied"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Gebied"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Gebied"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Gebied"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Gebied"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Gebied"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Gebied"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Gebied"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Gebiedengroep"
	IS 'Verzameling van gebieden Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Gebiedengroep"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Gebiedengroep"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Gebiedengroep"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Gebiedengroep"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Gebiedengroep"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Gebiedengroep"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Gebiedengroep"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Gebiedengroep"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Lijn"
	IS 'Denkbeeldige streep op de aardoppervlakte Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Lijn"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Lijn"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Lijn"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Lijn"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Lijn"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Lijn"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Lijn"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Lijn"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Lijnengroep"
	IS 'Verzameling van lijnen Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Lijnengroep"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Lijnengroep"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Lijnengroep"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Lijnengroep"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Lijnengroep"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Lijnengroep"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Lijnengroep"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Lijnengroep"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Locatie"
	IS 'De locatie beschrijft middels co√∂rdinaten de ruimtelijke dimensie of ruimtelijke afbakening van een regel of van een objecttype die in de regel beschreven wordt. (CIMOW) Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Locatie"."Hoogte"
	IS 'Hoogte in meters. Negatief is onder het maaiveld en positief boven het maaiveld'
;

COMMENT ON COLUMN "Locatie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Locatie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Locatie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Locatie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Locatie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Locatie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Locatie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Locatie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Punt"
	IS 'Plaats in de ruimte Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Punt"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Punt"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Punt"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Punt"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Punt"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Punt"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Punt"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Punt"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Puntengroep"
	IS 'Verzameling van punten Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Puntengroep"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Puntengroep"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Puntengroep"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Puntengroep"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Puntengroep"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Puntengroep"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Puntengroep"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Puntengroep"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Video_opname"
	IS 'Opnametechniek om bewegende beelden als een elektronisch signaal te registreren en weer te geven. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Video_opname"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Video_opname"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Video_opname"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Video_opname"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Video_opname"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Video_opname"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Video_opname"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Video_opname"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
