/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 17.0 		*/
/*  Created On : 06-mrt-2025 13:29:13 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "AanwezigeDeelnemer" CASCADE
;

DROP TABLE IF EXISTS "Agendapunt" CASCADE
;

DROP TABLE IF EXISTS "Categorie" CASCADE
;

DROP TABLE IF EXISTS "Collegelid" CASCADE
;

DROP TABLE IF EXISTS "Dossier" CASCADE
;

DROP TABLE IF EXISTS "Enum_deelnemersrol" CASCADE
;

DROP TABLE IF EXISTS "Enum_stemmingsresultaattype" CASCADE
;

DROP TABLE IF EXISTS "Enum_stemmingstype" CASCADE
;

DROP TABLE IF EXISTS "Indiener" CASCADE
;

DROP TABLE IF EXISTS "Kp_dossier_raadsstuk" CASCADE
;

DROP TABLE IF EXISTS "Kp_indiener_raadsstuk" CASCADE
;

DROP TABLE IF EXISTS "Kp_raadslid_raadscommissie" CASCADE
;

DROP TABLE IF EXISTS "Kp_raadsstuk_agendapunt" CASCADE
;

DROP TABLE IF EXISTS "Kp_raadsstuk_programma" CASCADE
;

DROP TABLE IF EXISTS "Kp_raadsstuk_vergadering" CASCADE
;

DROP TABLE IF EXISTS "Programma" CASCADE
;

DROP TABLE IF EXISTS "Raadscommissie" CASCADE
;

DROP TABLE IF EXISTS "Raadslid" CASCADE
;

DROP TABLE IF EXISTS "Raadsstuk" CASCADE
;

DROP TABLE IF EXISTS "Stemming" CASCADE
;

DROP TABLE IF EXISTS "Taakveld" CASCADE
;

DROP TABLE IF EXISTS "Vergadering" CASCADE
;

/* Create Tables */

CREATE TABLE "AanwezigeDeelnemer"
(
	"Aanvangaanwezigheid" timestamp without time zone NULL,
	"Eindeaanwezigheid" timestamp without time zone NULL,
	"Naam" varchar(250) NULL,
	"Rol" varchar(50) NULL,
	"Vertegenwoordigtorganisatie" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AanwezigeDeelnemerID" integer NOT NULL,
	"RaadslidID" integer NULL,
	"VergaderingID" integer NULL
)
;

CREATE TABLE "Agendapunt"
(
	"Nummer" integer NULL,
	"Omschrijving" text NULL,
	"Titel" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AgendapuntID" integer NOT NULL,
	"VergaderingID" integer NULL,
	"Video_opnameID" integer NULL
)
;

CREATE TABLE "Categorie"
(
	"Naam" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"CategorieID" integer NOT NULL
)
;

CREATE TABLE "Collegelid"
(
	"Achternaam" varchar(250) NULL,
	"Datumaanstelling" date NULL,
	"Datumuittreding" date NULL,
	"Fractie" varchar(250) NULL,
	"Portefeuille" varchar(200) NULL,
	"Titel" varchar(80) NULL,
	"Voornaam" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"CollegelidID" integer NOT NULL,
	"AanwezigeDeelnemerID" integer NULL,
	"IndienerID" integer NULL
)
;

CREATE TABLE "Dossier"
(
	"Naam" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"DossierID" integer NOT NULL
)
;

CREATE TABLE "Enum_deelnemersrol"
(
	"Voorzitter" varchar(50) NULL,
	"Vice-voorzitter" varchar(50) NULL,
	"Raadslid" varchar(50) NULL,
	"Inspreker" varchar(50) NULL,
	"Overig" varchar(50) NULL,
	"Portefeuillehouder" varchar(50) NULL,
	"Statenlid" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_stemmingsresultaattype"
(
	"Voor" varchar(50) NULL,
	"Tegen" varchar(50) NULL,
	"Gelijk" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Enum_stemmingstype"
(
	"Hoofdelijk" varchar(50) NULL,
	"Regulier" varchar(50) NULL,
	"Schriftelijk" varchar(50) NULL,
	"ID" INTEGER NOT NULL
)
;

CREATE TABLE "Indiener"
(
	"Naam" varchar(250) NULL,
	"Omschrijving" text NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"IndienerID" integer NOT NULL
)
;

CREATE TABLE "Kp_dossier_raadsstuk"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"RaadsstukID" integer NULL,
	"DossierID" integer NULL
)
;

CREATE TABLE "Kp_indiener_raadsstuk"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"RaadsstukID" integer NULL,
	"IndienerID" integer NULL
)
;

CREATE TABLE "Kp_raadslid_raadscommissie"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"RaadscommissieID" integer NULL,
	"RaadslidID" integer NULL
)
;

CREATE TABLE "Kp_raadsstuk_agendapunt"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"AgendapuntID" integer NULL,
	"RaadsstukID" integer NULL
)
;

CREATE TABLE "Kp_raadsstuk_programma"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ProgrammaID" integer NULL,
	"RaadsstukID" integer NULL
)
;

CREATE TABLE "Kp_raadsstuk_vergadering"
(
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VergaderingID" integer NULL,
	"RaadsstukID" integer NULL
)
;

CREATE TABLE "Programma"
(
	"Naam" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"ProgrammaID" integer NOT NULL
)
;

CREATE TABLE "Raadscommissie"
(
	"Naam" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"RaadscommissieID" integer NOT NULL
)
;

CREATE TABLE "Raadslid"
(
	"Achternaam" varchar(250) NULL,
	"Datumaanstelling" date NULL,
	"Datumuittreding" date NULL,
	"Fractie" varchar(250) NULL,
	"Titel" varchar(80) NULL,
	"Voornaam" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"RaadslidID" integer NOT NULL,
	"IndienerID" integer NULL
)
;

CREATE TABLE "Raadsstuk"
(
	"Besloten" boolean NULL,
	"Datumexpiratie" timestamp without time zone NULL,
	"Datumpublicatie" timestamp without time zone NULL,
	"Datumregistratie" timestamp without time zone NULL,
	"Typeraadsstuk" varchar(80) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"RaadsstukID" integer NOT NULL,
	"CategorieID" integer NULL,
	"TaakveldID" integer NULL,
	"StemmingID" integer NULL,
	"VergaderingID" integer NULL
)
;

CREATE TABLE "Stemming"
(
	"Resultaat" varchar(50) NULL,
	"Stemmingstype" varchar(50) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"StemmingID" integer NOT NULL,
	"AgendapuntID" integer NULL
)
;

CREATE TABLE "Taakveld"
(
	"Naam" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"TaakveldID" integer NOT NULL
)
;

CREATE TABLE "Vergadering"
(
	"Eindtijd" timestamp without time zone NULL,
	"Locatie" varchar(250) NULL,
	"Starttijd" timestamp without time zone NULL,
	"Titel" varchar(250) NULL,
	"DWH_RECORD_ID" int NULL,	-- GGM primaire sleutel.
	"DWH_ODS_RECORD_ID" int NULL,	-- ODS primaire sleutel.
	"DWH_START_DT" DATETIME NULL,	-- Startdatum van het record.
	"DWH_EIND_DT" DATETIME NULL,	-- Einddatum van het record.
	"DWH_RUN_ID" int NULL,	-- Unieke volgnummer van het laadproces.
	"DWH_BRON" VARCHAR(200) NULL,	-- Omschrijving van de bron waaruit het het gegeven is ontsloten.
	"DWH_LAAD_DT" DATETIME NULL,	-- Moment waarop het gegeven in het GGM is geladen.
	"DWH_ACTUEEL" int NULL,	-- Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.
	"VergaderingID" integer NOT NULL,
	"RaadscommissieID" integer NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "AanwezigeDeelnemer" ADD CONSTRAINT "PK_AanwezigeDeelnemer"
	PRIMARY KEY ("AanwezigeDeelnemerID")
;

ALTER TABLE "Agendapunt" ADD CONSTRAINT "PK_Agendapunt"
	PRIMARY KEY ("AgendapuntID")
;

ALTER TABLE "Categorie" ADD CONSTRAINT "PK_Categorie"
	PRIMARY KEY ("CategorieID")
;

ALTER TABLE "Collegelid" ADD CONSTRAINT "PK_Collegelid"
	PRIMARY KEY ("CollegelidID")
;

ALTER TABLE "Dossier" ADD CONSTRAINT "PK_Dossier"
	PRIMARY KEY ("DossierID")
;

ALTER TABLE "Enum_deelnemersrol" ADD CONSTRAINT "PK_Enum_deelnemersrol"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_stemmingsresultaattype" ADD CONSTRAINT "PK_Enum_stemmingsresultaattype"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Enum_stemmingstype" ADD CONSTRAINT "PK_Enum_stemmingstype"
	PRIMARY KEY ("ID")
;

ALTER TABLE "Indiener" ADD CONSTRAINT "PK_Indiener"
	PRIMARY KEY ("IndienerID")
;

ALTER TABLE "Programma" ADD CONSTRAINT "PK_Programma"
	PRIMARY KEY ("ProgrammaID")
;

ALTER TABLE "Raadscommissie" ADD CONSTRAINT "PK_Raadscommissie"
	PRIMARY KEY ("RaadscommissieID")
;

ALTER TABLE "Raadslid" ADD CONSTRAINT "PK_Raadslid"
	PRIMARY KEY ("RaadslidID")
;

ALTER TABLE "Raadsstuk" ADD CONSTRAINT "PK_Raadsstuk"
	PRIMARY KEY ("RaadsstukID")
;

ALTER TABLE "Stemming" ADD CONSTRAINT "PK_Stemming"
	PRIMARY KEY ("StemmingID")
;

ALTER TABLE "Taakveld" ADD CONSTRAINT "PK_Taakveld"
	PRIMARY KEY ("TaakveldID")
;

ALTER TABLE "Vergadering" ADD CONSTRAINT "PK_Vergadering"
	PRIMARY KEY ("VergaderingID")
;

/* Create Foreign Key Constraints */

ALTER TABLE "AanwezigeDeelnemer" ADD CONSTRAINT fk_is_raadslid
	FOREIGN KEY ("RaadslidID") REFERENCES "Raadslid" ("RaadslidID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "AanwezigeDeelnemer" ADD CONSTRAINT "fk_vergadering_aanwezigeDeelne"
	FOREIGN KEY ("VergaderingID") REFERENCES "Vergadering" ("VergaderingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Agendapunt" ADD CONSTRAINT fk_heeft_vergadering
	FOREIGN KEY ("VergaderingID") REFERENCES "Vergadering" ("VergaderingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Agendapunt" ADD CONSTRAINT fk_betreft_video_opname
	FOREIGN KEY ("Video_opnameID") REFERENCES "Video_opname" ("Video-opnameID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Collegelid" ADD CONSTRAINT "fk_is_aanwezigeDeelnemer"
	FOREIGN KEY ("AanwezigeDeelnemerID") REFERENCES "AanwezigeDeelnemer" ("AanwezigeDeelnemerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Collegelid" ADD CONSTRAINT fk_is_indiener
	FOREIGN KEY ("IndienerID") REFERENCES "Indiener" ("IndienerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Collegelid" ADD CONSTRAINT "Fk_collegelid_ingezetene"
	FOREIGN KEY ("CollegelidID") REFERENCES "Ingezetene" ("IngezeteneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_dossier_raadsstuk" ADD CONSTRAINT "Fk_kp_dossier_raadsstuk_raadsstuk"
	FOREIGN KEY ("RaadsstukID") REFERENCES "Raadsstuk" ("RaadsstukID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_dossier_raadsstuk" ADD CONSTRAINT "Fk_kp_dossier_raadsstuk_dossier"
	FOREIGN KEY ("DossierID") REFERENCES "Dossier" ("DossierID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_indiener_raadsstuk" ADD CONSTRAINT "Fk_kp_indiener_raadsstuk_raadsstuk"
	FOREIGN KEY ("RaadsstukID") REFERENCES "Raadsstuk" ("RaadsstukID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_indiener_raadsstuk" ADD CONSTRAINT "Fk_kp_indiener_raadsstuk_indiener"
	FOREIGN KEY ("IndienerID") REFERENCES "Indiener" ("IndienerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_raadslid_raadscommissie" ADD CONSTRAINT "Fk_kp_raadslid_raadscommissie_raadscommissie"
	FOREIGN KEY ("RaadscommissieID") REFERENCES "Raadscommissie" ("RaadscommissieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_raadslid_raadscommissie" ADD CONSTRAINT "Fk_kp_raadslid_raadscommissie_raadslid"
	FOREIGN KEY ("RaadslidID") REFERENCES "Raadslid" ("RaadslidID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_raadsstuk_agendapunt" ADD CONSTRAINT "Fk_kp_raadsstuk_agendapunt_agendapunt"
	FOREIGN KEY ("AgendapuntID") REFERENCES "Agendapunt" ("AgendapuntID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_raadsstuk_agendapunt" ADD CONSTRAINT "Fk_kp_raadsstuk_agendapunt_raadsstuk"
	FOREIGN KEY ("RaadsstukID") REFERENCES "Raadsstuk" ("RaadsstukID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_raadsstuk_programma" ADD CONSTRAINT "Fk_kp_raadsstuk_programma_programma"
	FOREIGN KEY ("ProgrammaID") REFERENCES "Programma" ("ProgrammaID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_raadsstuk_programma" ADD CONSTRAINT "Fk_kp_raadsstuk_programma_raadsstuk"
	FOREIGN KEY ("RaadsstukID") REFERENCES "Raadsstuk" ("RaadsstukID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_raadsstuk_vergadering" ADD CONSTRAINT "Fk_kp_raadsstuk_vergadering_vergadering"
	FOREIGN KEY ("VergaderingID") REFERENCES "Vergadering" ("VergaderingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Kp_raadsstuk_vergadering" ADD CONSTRAINT "Fk_kp_raadsstuk_vergadering_raadsstuk"
	FOREIGN KEY ("RaadsstukID") REFERENCES "Raadsstuk" ("RaadsstukID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Raadslid" ADD CONSTRAINT fk_is_indiener
	FOREIGN KEY ("IndienerID") REFERENCES "Indiener" ("IndienerID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Raadslid" ADD CONSTRAINT "Fk_raadslid_ingezetene"
	FOREIGN KEY ("RaadslidID") REFERENCES "Ingezetene" ("IngezeteneID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Raadsstuk" ADD CONSTRAINT fk_heeft_categorie
	FOREIGN KEY ("CategorieID") REFERENCES "Categorie" ("CategorieID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Raadsstuk" ADD CONSTRAINT "FK_Raadsstuk_Taakveld"
	FOREIGN KEY ("TaakveldID") REFERENCES "Taakveld" ("TaakveldID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Raadsstuk" ADD CONSTRAINT fk_betreft_stemming
	FOREIGN KEY ("StemmingID") REFERENCES "Stemming" ("StemmingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Raadsstuk" ADD CONSTRAINT "fk_heeftVerslag_vergadering"
	FOREIGN KEY ("VergaderingID") REFERENCES "Vergadering" ("VergaderingID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Stemming" ADD CONSTRAINT "FK_Stemming_Agendapunt"
	FOREIGN KEY ("AgendapuntID") REFERENCES "Agendapunt" ("AgendapuntID") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Vergadering" ADD CONSTRAINT fk_heeft_raadscommissie
	FOREIGN KEY ("RaadscommissieID") REFERENCES "Raadscommissie" ("RaadscommissieID") ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "AanwezigeDeelnemer"
	IS 'iemand die meedoet aan eencollege- of raadsvergadering Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "AanwezigeDeelnemer"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "AanwezigeDeelnemer"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "AanwezigeDeelnemer"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "AanwezigeDeelnemer"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "AanwezigeDeelnemer"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "AanwezigeDeelnemer"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "AanwezigeDeelnemer"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "AanwezigeDeelnemer"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Agendapunt"
	IS 'Een onderwerp dat in de vergadering wordt behandeld. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Agendapunt"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Agendapunt"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Agendapunt"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Agendapunt"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Agendapunt"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Agendapunt"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Agendapunt"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Agendapunt"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Categorie"
	IS 'Categorie waarop leveranciers zich voor de levering van personeel voor kunnen kwalificeren Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Categorie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Categorie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Categorie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Categorie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Categorie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Categorie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Categorie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Categorie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Collegelid"
	IS 'Iemand die behoort het college van burgemeester en wethouders Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Collegelid"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Collegelid"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Collegelid"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Collegelid"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Collegelid"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Collegelid"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Collegelid"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Collegelid"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Dossier"
	IS 'Samenhangende set gegevens en informatie voor een specifiek doel Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Dossier"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Dossier"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Dossier"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Dossier"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Dossier"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Dossier"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Dossier"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Dossier"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Indiener"
	IS 'Persoon die meldiing of aanvraag doet Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Indiener"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Indiener"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Indiener"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Indiener"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Indiener"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Indiener"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Indiener"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Indiener"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_dossier_raadsstuk"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_dossier_raadsstuk"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_dossier_raadsstuk"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_dossier_raadsstuk"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_dossier_raadsstuk"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_dossier_raadsstuk"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_dossier_raadsstuk"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_dossier_raadsstuk"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_indiener_raadsstuk"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_indiener_raadsstuk"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_indiener_raadsstuk"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_indiener_raadsstuk"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_indiener_raadsstuk"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_indiener_raadsstuk"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_indiener_raadsstuk"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_indiener_raadsstuk"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_raadslid_raadscommissie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_raadslid_raadscommissie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_raadslid_raadscommissie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_raadslid_raadscommissie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_raadslid_raadscommissie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_raadslid_raadscommissie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_raadslid_raadscommissie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_raadslid_raadscommissie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_raadsstuk_agendapunt"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_raadsstuk_agendapunt"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_raadsstuk_agendapunt"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_raadsstuk_agendapunt"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_raadsstuk_agendapunt"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_raadsstuk_agendapunt"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_raadsstuk_agendapunt"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_raadsstuk_agendapunt"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_raadsstuk_programma"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_raadsstuk_programma"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_raadsstuk_programma"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_raadsstuk_programma"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_raadsstuk_programma"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_raadsstuk_programma"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_raadsstuk_programma"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_raadsstuk_programma"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON COLUMN "Kp_raadsstuk_vergadering"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Kp_raadsstuk_vergadering"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Kp_raadsstuk_vergadering"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Kp_raadsstuk_vergadering"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Kp_raadsstuk_vergadering"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Kp_raadsstuk_vergadering"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Kp_raadsstuk_vergadering"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Kp_raadsstuk_vergadering"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Programma"
	IS 'Een tijdelijke, flexibele organisatiestructuur, die is opgezet om de implementatie van een verzameling met elkaar samenhangende projecten en activiteiten te co√∂rdineren, te sturen en te controleren teneinde te zorgen voor de realisatie van de eindresultaten en benefits die zijn gerelateerd aan de strategische doelstellingen van de organisatie. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Programma"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Programma"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Programma"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Programma"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Programma"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Programma"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Programma"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Programma"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Raadscommissie"
	IS 'Een raadscommissie binnen de Nederlandse gemeenteraad is een groep raadsleden die zich buigt over specifieke thema''s of beleidsonderwerpen om de besluitvorming in de volledige raad voor te bereiden en te ondersteunen. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Raadscommissie"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Raadscommissie"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Raadscommissie"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Raadscommissie"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Raadscommissie"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Raadscommissie"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Raadscommissie"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Raadscommissie"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Raadslid"
	IS 'Iemand die behoort de gemeenteraad Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Raadslid"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Raadslid"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Raadslid"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Raadslid"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Raadslid"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Raadslid"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Raadslid"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Raadslid"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Raadsstuk"
	IS 'Stuk dat door de gemeenteraad wordt behandeld Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Raadsstuk"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Raadsstuk"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Raadsstuk"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Raadsstuk"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Raadsstuk"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Raadsstuk"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Raadsstuk"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Raadsstuk"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Stemming"
	IS 'Stem (openbaring van iemands mening (voor of tegen)),  uitbrengen bij verkiezingen of bij een vergadering Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Stemming"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Stemming"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Stemming"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Stemming"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Stemming"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Stemming"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Stemming"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Stemming"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Taakveld"
	IS 'Een samenhangend geheel van activiteiten en taken en hangt onder een programma. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Taakveld"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Taakveld"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Taakveld"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Taakveld"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Taakveld"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Taakveld"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Taakveld"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Taakveld"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;

COMMENT ON TABLE "Vergadering"
	IS 'Een bijeenkomst van meerdere mensen (meestal van eenzelfde organisatie) die met elkaar spreken en/of afspraken maken over de gemeenschappelijke toekomst. Naam alias (gebruikt bij koppeltabellen en foreignkeys): '
;

COMMENT ON COLUMN "Vergadering"."DWH_RECORD_ID"
	IS 'GGM primaire sleutel.'
;

COMMENT ON COLUMN "Vergadering"."DWH_ODS_RECORD_ID"
	IS 'ODS primaire sleutel.'
;

COMMENT ON COLUMN "Vergadering"."DWH_START_DT"
	IS 'Startdatum van het record.'
;

COMMENT ON COLUMN "Vergadering"."DWH_EIND_DT"
	IS 'Einddatum van het record.'
;

COMMENT ON COLUMN "Vergadering"."DWH_RUN_ID"
	IS 'Unieke volgnummer van het laadproces.'
;

COMMENT ON COLUMN "Vergadering"."DWH_BRON"
	IS 'Omschrijving van de bron waaruit het het gegeven is ontsloten.'
;

COMMENT ON COLUMN "Vergadering"."DWH_LAAD_DT"
	IS 'Moment waarop het gegeven in het GGM is geladen.'
;

COMMENT ON COLUMN "Vergadering"."DWH_ACTUEEL"
	IS 'Geeft aan of dit een actuele (1) of een historische (0) presentatie van het record is.'
;
