name: Fast tests (pytest)

on:
  push:
    branches:
      [main]
  pull_request:
    branches:
      [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fast:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v5

      - name: Set up uv + Python
        uses: astral-sh/setup-uv@v7.1.1
        with:
          python-version: '3.12.10'
          enable-cache: true

      - name: Run tests
        run: uv run --frozen -m pytest -q 

